Graphene Attestation Inside AKS
gramineproject/graphene pull request #2473
Opened 2021-06-23 14:26 UTC by veenasai2

Signed-off-by: Veena Saini <veena.saini@intel.com>

## Description of the changes 

This PR provides a reference implementation to show how graphene attestation (DCAP) samples works inside AKS cluster. We have created two docker images for ra-tls-secret-prov server and ra-tls-secret-prov client. Both images are deployed as part of AKS confidential compute cluster and both quote generation and quote verification are successful inside AKS cluster.

For ra-tls-secret-prov client we have Tools/gsc/images/aks-client-deployment.yaml and for server Tools/gsc/images/aks-server-deployment.yaml file.

For more details, we have created a readme file.  

## How to test this PR? 
Please follow Tools/gsc/images/graphene_attestation_inside_aks_readme.rst.

2021-06-28 14:01 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2473)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @veenasai2)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2473#-MdHuCOcDQz2AT4JlXRI:-MdHuCOcDQz2AT4JlXRJ:b-9q49po) (no related file):*
This feels like a contribution to https://github.com/oscarlab/graphene-contrib. From what I understand, this contribution takes the `graphene/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov` example and runs it in the Azure Kubernetes Service (AKS) cloud.

@veenasai2 Do you think this PR can be moved to graphene-contrib? Or is there any particular reason to keep it in the core Graphene repository?

---


<!-- Sent from Reviewable.io -->

2021-06-29 05:52 UTC, aneessahib commented
@dimakuv we put it here since all the past AKS stuff also came here. Also there's one more image that has been added which can be used for other cloud deployments (aks-ra-tls-secret-prov-server.dockerfile). makes sense?

2021-07-21 10:06 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2473)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @veenasai2)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2473#-MdHuCOcDQz2AT4JlXRI:-Mf7OgKW1rjwzU83wV3I:baem5m3) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This feels like a contribution to https://github.com/oscarlab/graphene-contrib. From what I understand, this contribution takes the `graphene/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov` example and runs it in the Azure Kubernetes Service (AKS) cloud.

@veenasai2 Do you think this PR can be moved to graphene-contrib? Or is there any particular reason to keep it in the core Graphene repository?
</blockquote></details>

@veenasai2 For future: please always reply using Reviewable, not GitHub itself. Otherwise your comment just "hangs" in the wrong place when opening Reviewable.

Anyway, we agreed to review and merge this PR now, because this will get split into a new `gsc` repository soon. So it's better to merge this code into GSC now and then move everything in one go (instead of moving `gsc` now and moving this PR as well).

---
___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7PGhc95UC7m9VAYkt:-Mf7PGhc95UC7m9VAYku:b-milz0z) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L5)):*
> ```Dockerfile
> # STEP 1: Prepare Server certificate
> #         1.1 Create server certificate signed by your trusted root CA. Ensure Common Name
> #	      field in the server certificate corresponds to <AKS-DNS-NAME> used in STEP 5.
> ```

Please replace all tabs with spaces.
___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7Pf283EWCbitozCVy:-Mf7Pf294YjKXVf8mFNu:bmig9yr) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L9)):*
> ```Dockerfile
> #	      graphene/Examples/ra-tls-secret-prov/certs directory with existing naming convention.
> #         1.3 Provide password for your server key to mbedtls_pk_parse_keyfile(,,pwd) API call,
> #	      available at graphene/Pal/src/host/Linux-SGX/tools/ra-tls/tools/secret_prov_verify.c.
> ```

You're talking about this line: https://github.com/oscarlab/graphene/blob/e921589b871fe31a536dc19b37106b0cf9008938/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c#L184

But this is wrong. A user must modify Graphene source code and rebuild it just to use AKS? We cannot advise users doing this, we need to fix it ourselves.

So, why is this "password for your server key" is required at all? Can one create certificates + key in AKS without this password protection?

If *not*, then we need to change our Graphene source code such that `mbedtls_pk_parse_keyfile()` may optionally get the password from an environment variable or something. In general, I find this whole password protection very surprising.
___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7R9pqD5eYeIt3MGOb:-Mf7R9pqD5eYeIt3MGOc:b-lz7dft) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L27)):*
> ```Dockerfile
> #         Reference deployment file: graphene/Tools/gsc/images/aks-server-deployment.yaml
> #
> # NOTE:  Server can be deployed at non-confidential compute node as well. However, in that
> ```

`in that case`
___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7S3VsAhUGjuWap9q3:-Mf7S3VsAhUGjuWap9q4:bco9qz) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L38)):*
> ```Dockerfile
>     libcurl3-gnutls \
>     gnupg2 \
>     libcurl4-openssl-dev
> ```

Could you sort alphabetically these dependencies?
___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7TGwo-t_nNz2iV5GW:-Mf7TGwo-t_nNz2iV5GX:bt777m2) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L43)):*
> ```Dockerfile
> 
> RUN wget https://github.com/microsoft/Azure-DCAP-Client/releases/download/1.8/az-dcap-client_1.8_amd64_18.04.deb \
>     && chmod u+x az-dcap-client_1.8_amd64_18.04.deb \
> ```

Why do you need this? I thought there is no need in "execute" permission.
___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 93 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7TjVg59Hb_65BZB-e:-Mf7TjVh9rgBdxljPDcV:b-bd42pr) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L93)):*
> ```Dockerfile
> ENV PATH = "${PATH}:/graphene/Examples/ra-tls-secret-prov"
> 
> ENTRYPOINT ["/graphene/Examples/ra-tls-secret-prov/secret_prov_server_dcap","&"]
> ```

Why do you want to run it in background mode (`&`)? Why not just normal foreground monde?
___
*[Tools/gsc/images/aks-server-deployment.yaml, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7UhMF2IpbZMbx7_sz:-Mf7UhMF2IpbZMbx7_t-:b-d9cuwa) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-server-deployment.yaml#L35)):*
> ```YAML
>   - port: 4433
>   selector:
>     app: ra-tls-secret-prov-server
> ```

So the server doesn't need access to `aesmd` service?
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7UqY55Du21Y1HIZC2:-Mf7UqY55Du21Y1HIZC3:b58egeu) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L1)):*
> ```reStructuredText
> This guide demonstrates how Graphene DCAP attestation quote can be verified inside AKS cluster.
> ```

Could you explain a bit more? Why do we want to do such deployment?
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7VFsGEXR6Jo53X3Ol:-Mf7VFsGEXR6Jo53X3Om:b52co1d) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L1)):*
> ```reStructuredText
> This guide demonstrates how Graphene DCAP attestation quote can be verified inside AKS cluster.
> ```

This whole file is unreadable after RST rendering: https://github.com/veenasai2/graphene/blob/veenasai/graphene-attestation-inside-AKS/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst

Please fix. Or switch to Markdown (MD) syntax if RST is too complicated.
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7Uz-tD9tUk834djdM:-Mf7Uz-tD9tUk834djdN:b-z5k93i) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L6)):*
> ```reStructuredText
> Create client and server images for graphene attestation samples
> ================================================================
> This demonstration is created for graphene/Examples/ra-tls-secret-prov sample.
> [...]

2021-07-22 12:16 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2473)* status: 3 of 4 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @veenasai2)

___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7PGhc95UC7m9VAYkt:-MfD6JSjCmwSxOkXViX0:b-p1mmlj) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace all tabs with spaces.
</blockquote></details>

sure. Thanks.
___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7Pf283EWCbitozCVy:-MfD6N8H6fbOB82LmGuF:b-o0qeaa) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're talking about this line: https://github.com/oscarlab/graphene/blob/e921589b871fe31a536dc19b37106b0cf9008938/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_verify.c#L184

But this is wrong. A user must modify Graphene source code and rebuild it just to use AKS? We cannot advise users doing this, we need to fix it ourselves.

So, why is this "password for your server key" is required at all? Can one create certificates + key in AKS without this password protection?

If *not*, then we need to change our Graphene source code such that `mbedtls_pk_parse_keyfile()` may optionally get the password from an environment variable or something. In general, I find this whole password protection very surprising.
</blockquote></details>

Keys for the server can be generated with pass phrase or without pass phrase. So, we can keep the code as is. I removed the step 1.3.
___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7R9pqD5eYeIt3MGOb:-MfD7G6X3eIu65HzQngE:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`in that case`
</blockquote></details>

done, thanks.
___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7S3VsAhUGjuWap9q3:-MfD7Idi-70Z8-D3gUJw:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you sort alphabetically these dependencies?
</blockquote></details>

done, thanks.
___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7TGwo-t_nNz2iV5GW:-MfD7sRPE131bUq3jgUx:b-z2d5t8) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need this? I thought there is no need in "execute" permission.
</blockquote></details>

Removed execute permission. Thanks.
___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 93 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7TjVg59Hb_65BZB-e:-MfD7Kc66506IOfZIyTZ:be3kvpx) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L93)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you want to run it in background mode (`&`)? Why not just normal foreground monde?
</blockquote></details>

I was following the existing convention described at https://github.com/oscarlab/graphene/blob/master/Examples/ra-tls-secret-prov/README.md#L90. But, of course we can use the foreground mode too. Thanks.


<!-- Sent from Reviewable.io -->

2021-07-22 12:51 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2473)* status: 3 of 4 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2473#-MdHuCOcDQz2AT4JlXRI:-MfD8zuh5GYxtQuhy8Q5:b-54avio) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@veenasai2 For future: please always reply using Reviewable, not GitHub itself. Otherwise your comment just "hangs" in the wrong place when opening Reviewable.

Anyway, we agreed to review and merge this PR now, because this will get split into a new `gsc` repository soon. So it's better to merge this code into GSC now and then move everything in one go (instead of moving `gsc` now and moving this PR as well).
</blockquote></details>

Ok, thanks.

---
___
*[Tools/gsc/images/aks-server-deployment.yaml, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7UhMF2IpbZMbx7_sz:-MfD9zpe7bosu6VrXN29:b-kn3z62) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-server-deployment.yaml#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So the server doesn't need access to `aesmd` service?
</blockquote></details>

The out-of-proc mode quote generation APIs are relying upon aesmd service for quote generation.  Quote verification (at server side) does not require access to aesmd. 

Both quote generation and quote verification libraries communicates with Quote Provider Library (QPL).  Azure implemented their own version of QPL (aka az-dcap-client). Az-dcap-client will talk to a caching server for fetching the platfrom collateral. 

QuoteGen API -> Aesmd Funs() -> QPL (here az-dcap-client) --> Caching Server --> Intel PCS.

QuoteVer API -> QPL (here az-dcap-client) --> Caching Server --> Intel PCS
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7VFsGEXR6Jo53X3Ol:-MfDFwVz7m1FWf6mY4r4:b-67antj) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This whole file is unreadable after RST rendering: https://github.com/veenasai2/graphene/blob/veenasai/graphene-attestation-inside-AKS/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst

Please fix. Or switch to Markdown (MD) syntax if RST is too complicated.
</blockquote></details>

Sure, thanks. 
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7UqY55Du21Y1HIZC2:-MfDFzVW6jEgrtDIJZxf:bkf6n13) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you explain a bit more? Why do we want to do such deployment?
</blockquote></details>

Sure, thanks.
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7Uz-tD9tUk834djdM:-MfDFuUF6Jw6YbNc8SQu:bz110jb) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add double-backticks around the sample name.
</blockquote></details>

Sure, thanks
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7WJji3ExbqTpPigyr:-MfDDqVc5lX8IJpq-x2X:b8j37mv) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like that the user must modify the example manually. I would prefer to change our Secret Prov Client example such that it takes these values from an environment variable.
</blockquote></details>

Currently we have hardcoded  server dns name inside secret_prov_client.c, I was following  the same format. For secret_prov_min_client and secret_prov_pf_client we are providing the  dns name using loader.env.SECRET_PROVISION_SERVERS inside manifest file. 

I can provide the dns name either at build time using one env variable or can put as part of manifest file just like the other two client implementations.  Which one would you like to suggest? 
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 36 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7Vlyh3LuUcDSDRp2G:-MfDFkZ521eOpLT3LnXY:b-67antj) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this comment because you describe it anyhow below.
</blockquote></details>

Sure, thanks. 
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 39 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7VaEI0v9oEB7tlAWj:-MfDFiwU7bVxcaXRpYWg:b-4xd3j1) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the dot (` .`) at the end, looks weird.
</blockquote></details>

Sure , thanks
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7VsCECX8vFOp2R2Ev:-MfDFfmYBxC4UFvnXEcE:bwb726v) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It is typically called `out-of-proc` ("out of process"), not `out-proc`. Please fix everywhere.
</blockquote></details>

sure, thanks


<!-- Sent from Reviewable.io -->

2021-07-22 12:56 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2473)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @veenasai2)

___
*[Tools/gsc/images/aks-server-deployment.yaml, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7UhMF2IpbZMbx7_sz:-MfDH6u3BczMVIUFgoQ9:bd96loz) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/aks-server-deployment.yaml#L35)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

The out-of-proc mode quote generation APIs are relying upon aesmd service for quote generation.  Quote verification (at server side) does not require access to aesmd. 

Both quote generation and quote verification libraries communicates with Quote Provider Library (QPL).  Azure implemented their own version of QPL (aka az-dcap-client). Az-dcap-client will talk to a caching server for fetching the platfrom collateral. 

QuoteGen API -> Aesmd Funs() -> QPL (here az-dcap-client) --> Caching Server --> Intel PCS.

QuoteVer API -> QPL (here az-dcap-client) --> Caching Server --> Intel PCS


</blockquote></details>

Thanks for the great explanation!
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7WJji3ExbqTpPigyr:-MfDHMtcBqfLmxu6P4iZ:b1flqfi) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L17)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Currently we have hardcoded  server dns name inside secret_prov_client.c, I was following  the same format. For secret_prov_min_client and secret_prov_pf_client we are providing the  dns name using loader.env.SECRET_PROVISION_SERVERS inside manifest file. 

I can provide the dns name either at build time using one env variable or can put as part of manifest file just like the other two client implementations.  Which one would you like to suggest? 
</blockquote></details>

I suggest to do like the other two client implementations.


<!-- Sent from Reviewable.io -->

2021-07-22 13:00 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2473)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7WJji3ExbqTpPigyr:-MfDI-FYE42LoivPdhrG:b-67antj) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to do like the other two client implementations.
</blockquote></details>

Sure, thanks. 


<!-- Sent from Reviewable.io -->

2021-07-23 04:05 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2473)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7UqY55Du21Y1HIZC2:-MfGXOnPEa4_s6EQrKoZ:b-z7t65e) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L1)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Sure, thanks.
</blockquote></details>

This PR provides an end to end example to help CSPs integrate graphene’s RA TLS attestation and secret provisioning feature with a confidential compute cluster managed by the Azure Kubernetes Service. The PR provides the necessary reference wrappers that will enable graphene to use the AKS components such as the AESMD and quote provider libraries. A microservice deployment is also provided for the RA-TLS verifier module that can be readily deployed to the AKS cluster.


<!-- Sent from Reviewable.io -->

2021-07-26 07:12 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2473)* status: 4 of 6 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @veenasai2)

___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7UqY55Du21Y1HIZC2:-MfWcFhwE4NWdRqZB-gk:b-ttenfw) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L1)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

This PR provides an end to end example to help CSPs integrate graphene’s RA TLS attestation and secret provisioning feature with a confidential compute cluster managed by the Azure Kubernetes Service. The PR provides the necessary reference wrappers that will enable graphene to use the AKS components such as the AESMD and quote provider libraries. A microservice deployment is also provided for the RA-TLS verifier module that can be readily deployed to the AKS cluster.
</blockquote></details>

More changes - 
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 56 at r3](https://reviewable.io/reviews/oscarlab/graphene/2473#-MfWdD8t8RE3GHvuR_io:-MfWdD8t8RE3GHvuR_ip:b-e3brms) ([raw file](https://github.com/oscarlab/graphene/blob/dc1f1a424cb339e50f1a6efa8485fdd2dcdfee7b/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L56)):*
> ```reStructuredText
> Azure-internal caching service https://global.acccache.azure.net/sgx/certificates/.
> The aks-server-deployment.yaml is utilizing az-dcap-client library instead of
> libsgx-dcap-default-qpl.
> ```

In the ra-tls-secret-prov example, the client will generate out-of-proc mode sgx quote that will be embedded inside RA-TLS certificate. On receiving the quote, the server will internally verify it using libsgx-dcap-quote-verify library via az-dcap-client library. Here, aks-server-deployment.yaml will deploy a ra-tls-secret-prov server container inside AKS cluster.
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 65 at r3](https://reviewable.io/reviews/oscarlab/graphene/2473#-MfWdg9f6slTXBlphsqi:-MfWdg9f6slTXBlphsqj:b2c8r9p) ([raw file](https://github.com/oscarlab/graphene/blob/dc1f1a424cb339e50f1a6efa8485fdd2dcdfee7b/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L65)):*
> ```reStructuredText
> Once the server container is in running state,
> $ kubectl apply -f aks-client-deployment.yaml
> ```

At this stage, a successful RA-TLS verification would be completed, and the secrets have been provisioned from the server to the client container
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 67 at r3](https://reviewable.io/reviews/oscarlab/graphene/2473#-MfWd3GG3SOzOO2jIUMi:-MfWd3GG3SOzOO2jIUMj:b-wdyk9e) ([raw file](https://github.com/oscarlab/graphene/blob/dc1f1a424cb339e50f1a6efa8485fdd2dcdfee7b/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L67)):*
> ```reStructuredText
> 
> Ensure the quote generation and verification is successful inside AKS cluster
> =============================================================================
> ```

Ensure both quote generation and verification are successful inside AKS cluster -> Steps to verify successful quote generation and quote verification using logs


<!-- Sent from Reviewable.io -->

2021-07-26 07:28 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2473)* status: 3 of 8 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @dimakuv)

___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2473#-Mf7UqY55Du21Y1HIZC2:-MfWgvfl17j_NXjbY7-8:b-67anu5) ([raw file](https://github.com/oscarlab/graphene/blob/0a85062d9ba3e14bd11c9aadd33dba5ce9ea7555/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L1)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

More changes - 
</blockquote></details>

Sure, thanks.
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 56 at r3](https://reviewable.io/reviews/oscarlab/graphene/2473#-MfWdD8t8RE3GHvuR_io:-MfWhkvk9qHKviVn18q7:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/dc1f1a424cb339e50f1a6efa8485fdd2dcdfee7b/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L56)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

In the ra-tls-secret-prov example, the client will generate out-of-proc mode sgx quote that will be embedded inside RA-TLS certificate. On receiving the quote, the server will internally verify it using libsgx-dcap-quote-verify library via az-dcap-client library. Here, aks-server-deployment.yaml will deploy a ra-tls-secret-prov server container inside AKS cluster.
</blockquote></details>

done, thanks.
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 65 at r3](https://reviewable.io/reviews/oscarlab/graphene/2473#-MfWdg9f6slTXBlphsqi:-MfWhjPx-6PXPKocS621:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/dc1f1a424cb339e50f1a6efa8485fdd2dcdfee7b/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L65)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

At this stage, a successful RA-TLS verification would be completed, and the secrets have been provisioned from the server to the client container
</blockquote></details>

done, thanks.
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.rst, line 67 at r3](https://reviewable.io/reviews/oscarlab/graphene/2473#-MfWd3GG3SOzOO2jIUMi:-MfWhmQX5YecDdPFXcw5:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/dc1f1a424cb339e50f1a6efa8485fdd2dcdfee7b/Tools/gsc/images/graphene_attestation_inside_aks_readme.rst#L67)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Ensure both quote generation and verification are successful inside AKS cluster -> Steps to verify successful quote generation and quote verification using logs
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-07-29 06:26 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2473)* status: 3 of 8 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, and @veenasai2)

___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.md, line 3 at r4](https://reviewable.io/reviews/oscarlab/graphene/2473#-MfkwHBC46UX6bxehvi8:-MfkwHBC46UX6bxehvi9:bsy6up5) ([raw file](https://github.com/oscarlab/graphene/blob/8f983d20ecd15982c135afe4d76ebfeb5790a18f/Tools/gsc/images/graphene_attestation_inside_aks_readme.md#L3)):*
> ```Markdown
> # Graphene Attestation Inside AKS cluster
> 
> This guide demonstrates how Graphene DCAP attestation quote can be verified inside AKS cluster.
> ```

can be generated and verified from within an AKS cluster.


<!-- Sent from Reviewable.io -->

2021-07-29 06:41 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2473)* status: 3 of 8 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @dimakuv)

___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.md, line 3 at r4](https://reviewable.io/reviews/oscarlab/graphene/2473#-MfkwHBC46UX6bxehvi8:-Mfkzjcw2NgeoAG4B_zz:b-dtkdrq) ([raw file](https://github.com/oscarlab/graphene/blob/8f983d20ecd15982c135afe4d76ebfeb5790a18f/Tools/gsc/images/graphene_attestation_inside_aks_readme.md#L3)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

can be generated and verified from within an AKS cluster.
</blockquote></details>

Done, thanks.


<!-- Sent from Reviewable.io -->

2021-07-30 03:21 UTC, aneessahib commented
@veenasai2 lets enhance this example to reflect a prod scenario where a simple main program is started after a successful attestation. The attestation code first runs in this case, and loads the application code after the RA-TLS and platform attestation has passed.

2021-07-30 05:53 UTC, veenasai2 reviewed
ok, sure. Thanks.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2473#-:-MfpyPal6IAogzSKH1VV:b-fg6it3)* status: 3 of 8 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @dimakuv)



<!-- Sent from Reviewable.io -->

2021-07-30 10:29 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2473)* status: 3 of 8 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, and @veenasai2)

___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.md, line 4 at r5](https://reviewable.io/reviews/oscarlab/graphene/2473#-MfqxP7UC0p2ERlYACrn:-MfqxP7UC0p2ERlYACro:b-k5urx2) ([raw file](https://github.com/oscarlab/graphene/blob/dd99b8cb82a0fa73f14b0d7c4d6f021e4674b719/Tools/gsc/images/graphene_attestation_inside_aks_readme.md#L4)):*
> ```Markdown
> 
> This guide demonstrates how Graphene DCAP attestation quote can be generated and verified from
> within an AKS cluster. Here, we provide an end to end example to help CSPs integrate graphene’s
> ```

expand CSP to Cloud Solution Providers


<!-- Sent from Reviewable.io -->

2021-09-21 09:00 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2473)* status: 3 of 8 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, and @veenasai2)

___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 9 at r5](https://reviewable.io/reviews/gramineproject/graphene/2473#-Mk6_AyG19bGTcEWJPJK:-Mk6_AyG19bGTcEWJPJL:b-d5wdlt) ([raw file](https://github.com/gramineproject/graphene/blob/dd99b8cb82a0fa73f14b0d7c4d6f021e4674b719/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L9)):*
> ```Dockerfile
> #             graphene/Examples/ra-tls-secret-prov/certs directory with existing naming convention.
> #
> # STEP 2: Make sure RA-TLS DCAP libraries are built in Graphene via:
> ```

Just say RA-TLS libraries. Do mention this example is demonstrates dcap attestation flow in the beginning


<!-- Sent from Reviewable.io -->

2021-09-21 09:22 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2473)* status: 3 of 8 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, and @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2473#-Mk6dK1r4y96_EZcPklB:-Mk6dK1sC3k3EzkPqkS3:boyw11w) (no related file):*
@mkow We were asked to have this PR in GSC as part of the Gramine release. Could we expedite this PR?

---
___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 61 at r5](https://reviewable.io/reviews/gramineproject/graphene/2473#-Mk6cvO5-t_r3r7MfzIn:-Mk6cvO5-t_r3r7MfzIo:b-ix8m1f) ([raw file](https://github.com/gramineproject/graphene/blob/dd99b8cb82a0fa73f14b0d7c4d6f021e4674b719/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L61)):*
> ```Dockerfile
>     && mkdir -p /graphene/Pal/src/host/Linux-SGX/tools/common \
>     && mkdir -p /graphene/Pal/src/host/Linux-SGX/tools/ra-tls \
>     && mkdir -p /graphene/Examples/ra-tls-secret-prov
> ```

This kind of stuff shouldn't be needed any more because we recently merged the PR in Gramine that adds all these RA-TLS / Secret Prov libraries. So no need to copy all these directories and files.

This comment concerns everything in this PR -- please remove all the redundant copies of files.
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.md, line 1 at r5](https://reviewable.io/reviews/gramineproject/graphene/2473#-Mk6eJ2nBGeJWz3Y9miJ:-Mk6eJ2oE9Mso5-wAcux:b-p465nr) ([raw file](https://github.com/gramineproject/graphene/blob/dd99b8cb82a0fa73f14b0d7c4d6f021e4674b719/Tools/gsc/images/graphene_attestation_inside_aks_readme.md#L1)):*
> ```Markdown
> # Graphene Attestation Inside AKS cluster
> ```

All `Graphene` should be renamed to `Gramine` in documentation
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.md, line 22 at r5](https://reviewable.io/reviews/gramineproject/graphene/2473#-Mk6eR10Cnl8dXrmyE-M:-Mk6eR10Cnl8dXrmyE-N:bfl6yxg) ([raw file](https://github.com/gramineproject/graphene/blob/dd99b8cb82a0fa73f14b0d7c4d6f021e4674b719/Tools/gsc/images/graphene_attestation_inside_aks_readme.md#L22)):*
> ```Markdown
> - Steps to create ra-tls-secret-prov-client gsc image for AKS:
> 
> ```sh
> ```

This looks ugly. Please just use the nested lists in Markdown instead of this code-like listing.


<!-- Sent from Reviewable.io -->

2021-09-21 09:30 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2473)* status: 3 of 8 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, and @veenasai2)

___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 9 at r5](https://reviewable.io/reviews/gramineproject/graphene/2473#-Mk6_AyG19bGTcEWJPJK:-Mk6furZB0iFsbBF7Oad:bkf6n13) ([raw file](https://github.com/gramineproject/graphene/blob/dd99b8cb82a0fa73f14b0d7c4d6f021e4674b719/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L9)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Just say RA-TLS libraries. Do mention this example is demonstrates dcap attestation flow in the beginning
</blockquote></details>

Sure, thanks.
___
*[Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile, line 61 at r5](https://reviewable.io/reviews/gramineproject/graphene/2473#-Mk6cvO5-t_r3r7MfzIn:-Mk6ftL2-_QVCwMKX0Le:b77i4af) ([raw file](https://github.com/gramineproject/graphene/blob/dd99b8cb82a0fa73f14b0d7c4d6f021e4674b719/Tools/gsc/images/aks-ra-tls-secret-prov-server.dockerfile#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This kind of stuff shouldn't be needed any more because we recently merged the PR in Gramine that adds all these RA-TLS / Secret Prov libraries. So no need to copy all these directories and files.

This comment concerns everything in this PR -- please remove all the redundant copies of files.
</blockquote></details>

sure, thanks.
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.md, line 1 at r5](https://reviewable.io/reviews/gramineproject/graphene/2473#-Mk6eJ2nBGeJWz3Y9miJ:-Mk6fYau5gG9e9w5BQuk:b4pz2ab) ([raw file](https://github.com/gramineproject/graphene/blob/dd99b8cb82a0fa73f14b0d7c4d6f021e4674b719/Tools/gsc/images/graphene_attestation_inside_aks_readme.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

All `Graphene` should be renamed to `Gramine` in documentation
</blockquote></details>

https://github.com/gramineproject/gsc/pull/11/files. Here, I put Gramine only. Looks like this reviewable is still referring to old files. 
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.md, line 4 at r5](https://reviewable.io/reviews/gramineproject/graphene/2473#-MfqxP7UC0p2ERlYACrn:-Mk6fykQE_dp9TVRT5Ao:b-iry7x8) ([raw file](https://github.com/gramineproject/graphene/blob/dd99b8cb82a0fa73f14b0d7c4d6f021e4674b719/Tools/gsc/images/graphene_attestation_inside_aks_readme.md#L4)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

expand CSP to Cloud Solution Providers
</blockquote></details>

Done, thanks
___
*[Tools/gsc/images/graphene_attestation_inside_aks_readme.md, line 22 at r5](https://reviewable.io/reviews/gramineproject/graphene/2473#-Mk6eR10Cnl8dXrmyE-M:-Mk6g6q17CrSOchM3e92:b77i4af) ([raw file](https://github.com/gramineproject/graphene/blob/dd99b8cb82a0fa73f14b0d7c4d6f021e4674b719/Tools/gsc/images/graphene_attestation_inside_aks_readme.md#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks ugly. Please just use the nested lists in Markdown instead of this code-like listing.
</blockquote></details>

sure, thanks.


<!-- Sent from Reviewable.io -->

2021-09-21 09:51 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2473)* status: 3 of 8 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2473#-Mk6dK1r4y96_EZcPklB:-Mk6knaw4UCEeuMSenWf:b-21per1) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow We were asked to have this PR in GSC as part of the Gramine release. Could we expedite this PR?
</blockquote></details>

The new PR is at gsc repo with the reviewable link: https://reviewable.io/reviews/gramineproject/gsc/11 and PR link: https://github.com/gramineproject/gsc/pull/11 . The updated files are present at the new link. Thanks.

---


<!-- Sent from Reviewable.io -->

2021-09-23 11:58 UTC, dimakuv commented
This PR was transferred to https://github.com/gramineproject/gsc/pull/11. Closing here.

2021-09-23 11:58 UTC, closed without merging