[LibOS] Fix setting of `O_NONBLOCK` flag at the write end of pipe
gramineproject/graphene pull request #2524
Opened 2021-07-09 01:18 UTC by vijaydhanraj

## Description of the changes 

Currently, in Graphene we don't save the `O_NONBLOCK` flag for the write end of the pipe. We set the `O_NONBLOCK` flag for the PAL_HANDLE but this isn't propagated to the SHIM_HANDLE when creating pipe. This commit fixes the corner case.

Also, updated the `pipe_nonblocking` regression test to catch this corner case.

## How to test this PR? 
Please run both `graphene-direct` and `graphene-sgx` regression tests.

2021-07-09 06:46 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2524)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene/2524#-Me9-ARh3BiKoL5CChP6:-Me9-ARh3BiKoL5CChP7:b-dd5qvw) ([raw file](https://github.com/oscarlab/graphene/blob/9556b8f9a0cedfded6a20fe56ad2ec732a8b8fcc/LibOS/shim/test/regression/pipe_nonblocking.c#L17)):*
> ```C
>     /* Verify both ends of the pipe provide same flags. */
>     int flags_wr = fcntl(p[1], F_GETFL);
>     if (flags_wr == -1)
> ```

For uniformity with the rest of this code, can we do `flags_wr < 0`?
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2524#-Me9-EOVEA15KoPZKMdn:-Me9-EOVEA15KoPZKMdo:b-6gkkie) ([raw file](https://github.com/oscarlab/graphene/blob/9556b8f9a0cedfded6a20fe56ad2ec732a8b8fcc/LibOS/shim/test/regression/pipe_nonblocking.c#L18)):*
> ```C
>     int flags_wr = fcntl(p[1], F_GETFL);
>     if (flags_wr == -1)
>         err(1, "fnctl to get status flags at write end failed\n");
> ```

First, there is no need for `\n` -- `err()` adds it implicitly. Second, I suggest a shorter version: `err(1, "fcntl(<write end of pipe>, F_GETFL)")`.
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/2524#-Me9-VAu2sfLe0BCXLxV:-Me9-VAu2sfLe0BCXLxW:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/9556b8f9a0cedfded6a20fe56ad2ec732a8b8fcc/LibOS/shim/test/regression/pipe_nonblocking.c#L21)):*
> ```C
> 
>     int flags_rd = fcntl(p[0], F_GETFL);
>     if (flags_rd == -1)
> ```

ditto
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene/2524#-Me9-Vog01YK2jnk_dwi:-Me9-Vog01YK2jnk_dwj:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/9556b8f9a0cedfded6a20fe56ad2ec732a8b8fcc/LibOS/shim/test/regression/pipe_nonblocking.c#L22)):*
> ```C
>     int flags_rd = fcntl(p[0], F_GETFL);
>     if (flags_rd == -1)
>         err(1, "fnctl to get status flags at read end failed\n");
> ```

ditto
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/2524#-Me9-ltgAbUY0zd1LGLG:-Me9-ltgAbUY0zd1LGLH:b-64ezo) ([raw file](https://github.com/oscarlab/graphene/blob/9556b8f9a0cedfded6a20fe56ad2ec732a8b8fcc/LibOS/shim/test/regression/pipe_nonblocking.c#L26)):*
> ```C
>     /* Ensure O_NONBLOCK flag is properly set on both ends of pipe. */
>     if (!(flags_wr & O_NONBLOCK) || !(flags_rd & O_NONBLOCK))
>         errx(1, "O_NONBLOCK flag must be set on both ends of pipe, flags_wr=0x%x, flags_rd=0x%x\n",
> ```

I would change text to `"expected O_NONBLOCK flag on both ends of pipe but got flags_wr=0x%x, flags_rd=0x%x\n"`
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2524#-Me9-w0DE0Jvf3eddsE9:-Me9-w0DE0Jvf3eddsEA:b-6xco9l) ([raw file](https://github.com/oscarlab/graphene/blob/9556b8f9a0cedfded6a20fe56ad2ec732a8b8fcc/LibOS/shim/test/regression/pipe_nonblocking.c#L28)):*
> ```C
>         errx(1, "O_NONBLOCK flag must be set on both ends of pipe, flags_wr=0x%x, flags_rd=0x%x\n",
>              flags_wr, flags_rd);
> ```

Can we add a similar check as above, but for `O_CLOEXEC`?


<!-- Sent from Reviewable.io -->

2021-07-12 05:55 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2524)* status: 1 of 2 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene/2524#-Me9-ARh3BiKoL5CChP6:-MeOAeWbCIllYLY7gut9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9556b8f9a0cedfded6a20fe56ad2ec732a8b8fcc/LibOS/shim/test/regression/pipe_nonblocking.c#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For uniformity with the rest of this code, can we do `flags_wr < 0`?
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2524#-Me9-EOVEA15KoPZKMdn:-MeOCrO5Ek2KM74VeQOR:bmfxpif) ([raw file](https://github.com/oscarlab/graphene/blob/9556b8f9a0cedfded6a20fe56ad2ec732a8b8fcc/LibOS/shim/test/regression/pipe_nonblocking.c#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

First, there is no need for `\n` -- `err()` adds it implicitly. Second, I suggest a shorter version: `err(1, "fcntl(<write end of pipe>, F_GETFL)")`.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/2524#-Me9-ltgAbUY0zd1LGLG:-MeODzDE2koKpK2dkZVS:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9556b8f9a0cedfded6a20fe56ad2ec732a8b8fcc/LibOS/shim/test/regression/pipe_nonblocking.c#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would change text to `"expected O_NONBLOCK flag on both ends of pipe but got flags_wr=0x%x, flags_rd=0x%x\n"`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2524#-Me9-w0DE0Jvf3eddsE9:-MeOBFevEWQENP8387Sh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9556b8f9a0cedfded6a20fe56ad2ec732a8b8fcc/LibOS/shim/test/regression/pipe_nonblocking.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we add a similar check as above, but for `O_CLOEXEC`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-12 07:03 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2524)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-07-12 07:03 UTC, dimakuv commented
Jenkins, test this please

2021-08-31 15:31 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2524)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 25 at r2](https://reviewable.io/reviews/oscarlab/graphene/2524#-MiRpUqRB3sff9GevVzN:-MiRpUqRB3sff9GevVzO:b-q97ku7) ([raw file](https://github.com/oscarlab/graphene/blob/671b55719350027816aa7658b35ef28156a75e96/LibOS/shim/test/regression/pipe_nonblocking.c#L25)):*
> ```C
> 
>     /* Ensure O_NONBLOCK flag is properly set on both ends of pipe. */
>     if (!(flags_wr & O_NONBLOCK) || !(flags_rd & O_NONBLOCK))
> ```

We could also check if `flags_wr == flags_rd`
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene/2524#-MiRpE9b0LDHx4_EsesA:-MiRpE9b0LDHx4_EsesB:b2u7lqt) ([raw file](https://github.com/oscarlab/graphene/blob/671b55719350027816aa7658b35ef28156a75e96/LibOS/shim/test/regression/pipe_nonblocking.c#L27)):*
> ```C
>     if (!(flags_wr & O_NONBLOCK) || !(flags_rd & O_NONBLOCK))
>         errx(1, "Expected O_NONBLOCK flag to be set on both ends of pipe but got flags_wr=0x%x, "
>             "flags_rd=0x%x\n", flags_wr, flags_rd);
> ```

Please remove `\n`.
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene/2524#-MiRp_ug6H_f9alVFai4:-MiRp_ug6H_f9alVFai5:bs1bthw) ([raw file](https://github.com/oscarlab/graphene/blob/671b55719350027816aa7658b35ef28156a75e96/LibOS/shim/test/regression/pipe_nonblocking.c#L38)):*
> ```C
> 
>     /* Ensure O_CLOEXEC flag is properly set on both ends of pipe. */
>     if (!(flags_wr & FD_CLOEXEC) || !(flags_rd & FD_CLOEXEC))
> ```

ditto (== check)
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 40 at r2](https://reviewable.io/reviews/oscarlab/graphene/2524#-MiRpPMP0MJoBvtmCxSo:-MiRpPMP0MJoBvtmCxSp:bifg08y) ([raw file](https://github.com/oscarlab/graphene/blob/671b55719350027816aa7658b35ef28156a75e96/LibOS/shim/test/regression/pipe_nonblocking.c#L40)):*
> ```C
>     if (!(flags_wr & FD_CLOEXEC) || !(flags_rd & FD_CLOEXEC))
>         errx(1, "Expected O_CLOEXEC flag to be set on both ends of pipe but got flags_wr=0x%x, "
>              "flags_rd=0x%x\n", flags_wr, flags_rd);
> ```

ditto (newline)


<!-- Sent from Reviewable.io -->

2021-09-10 19:37 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2524)* status: 1 of 2 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 25 at r2](https://reviewable.io/reviews/gramineproject/graphene/2524#-MiRpUqRB3sff9GevVzN:-MjG8-Iz3PisAqP_yF3i:baaiue5) ([raw file](https://github.com/gramineproject/graphene/blob/671b55719350027816aa7658b35ef28156a75e96/LibOS/shim/test/regression/pipe_nonblocking.c#L25)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We could also check if `flags_wr == flags_rd`
</blockquote></details>

This will not work as the read end of the pipe has `O_RDONLY` access mode set and the write end of pipe has `O_WRONLY` access mode set. Also, I think it is better to explicitly check against the flag that we are interested in rather than making sure that read and write flags match. 
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 27 at r2](https://reviewable.io/reviews/gramineproject/graphene/2524#-MiRpE9b0LDHx4_EsesA:-MjG9I2LBPuuPYGw9l5h:bb6un1j) ([raw file](https://github.com/gramineproject/graphene/blob/671b55719350027816aa7658b35ef28156a75e96/LibOS/shim/test/regression/pipe_nonblocking.c#L27)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please remove `\n`.
</blockquote></details>

Done
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 38 at r2](https://reviewable.io/reviews/gramineproject/graphene/2524#-MiRp_ug6H_f9alVFai4:-MjG9Z1c-LlkiVi6zXRr:b-n0n7ej) ([raw file](https://github.com/gramineproject/graphene/blob/671b55719350027816aa7658b35ef28156a75e96/LibOS/shim/test/regression/pipe_nonblocking.c#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (== check)
</blockquote></details>

Here `==` check will work but I think it is better to check for the explicit flag that we are interested in.
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 40 at r2](https://reviewable.io/reviews/gramineproject/graphene/2524#-MiRpPMP0MJoBvtmCxSo:-MjG9JDX6MFmg6_pa12M:bb6un1j) ([raw file](https://github.com/gramineproject/graphene/blob/671b55719350027816aa7658b35ef28156a75e96/LibOS/shim/test/regression/pipe_nonblocking.c#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (newline)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-09-10 19:38 UTC, vijaydhanraj commented
@boryspoplawski I have also rebased to the latest master.

2021-09-12 13:48 UTC, boryspoplawski requested changes
Please do not rebase in the middle of review.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2524#-:-MjPG5GG0oYgABg5hpKu:b-q4piiv)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 25 at r2](https://reviewable.io/reviews/gramineproject/graphene/2524#-MiRpUqRB3sff9GevVzN:-MjPFQ5z9loEondPJ2-E:bxae9gl) ([raw file](https://github.com/gramineproject/graphene/blob/671b55719350027816aa7658b35ef28156a75e96/LibOS/shim/test/regression/pipe_nonblocking.c#L25)):*
You can mask it out using `O_ACCMODE`.

> Also, I think it is better to explicitly check against the flag that we are interested in rather than making sure that read and write flags match.

I suggested to add such a check, not to replace the existing one.
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 38 at r2](https://reviewable.io/reviews/gramineproject/graphene/2524#-MiRp_ug6H_f9alVFai4:-MjPFlep8B0D6wvao_o9:b-m5r8r9) ([raw file](https://github.com/gramineproject/graphene/blob/671b55719350027816aa7658b35ef28156a75e96/LibOS/shim/test/regression/pipe_nonblocking.c#L38)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Here `==` check will work but I think it is better to check for the explicit flag that we are interested in.
</blockquote></details>

I suggested expanding the check, not replacing it.


<!-- Sent from Reviewable.io -->

2021-09-13 06:34 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2524)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 25 at r2](https://reviewable.io/reviews/gramineproject/graphene/2524#-MiRpUqRB3sff9GevVzN:-MjShS0q6TDchXB3oiDW:b-4mcgdv) ([raw file](https://github.com/gramineproject/graphene/blob/671b55719350027816aa7658b35ef28156a75e96/LibOS/shim/test/regression/pipe_nonblocking.c#L25)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You can mask it out using `O_ACCMODE`.

> Also, I think it is better to explicitly check against the flag that we are interested in rather than making sure that read and write flags match.

I suggested to add such a check, not to replace the existing one.
</blockquote></details>

sorry I don't understand why we want to add `flag_wr == flag_rd` check by masking off `O_WRONLY/O_RDWR` flags? From the code, it looks like we only support `O_NONBLOCK` and `O_CLOEXEC` flags for `pipe2`and we check both here in this test.
___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 38 at r2](https://reviewable.io/reviews/gramineproject/graphene/2524#-MiRp_ug6H_f9alVFai4:-MjSr8J2A1sO-3W44j0y:b-5h08c7) ([raw file](https://github.com/gramineproject/graphene/blob/671b55719350027816aa7658b35ef28156a75e96/LibOS/shim/test/regression/pipe_nonblocking.c#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I suggested expanding the check, not replacing it.
</blockquote></details>

same here.


<!-- Sent from Reviewable.io -->

2021-09-13 11:28 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2524)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @vijaydhanraj)

___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 25 at r2](https://reviewable.io/reviews/gramineproject/graphene/2524#-MiRpUqRB3sff9GevVzN:-MjTu0AWEeWIZzb65uoy:bv9ncof) ([raw file](https://github.com/gramineproject/graphene/blob/671b55719350027816aa7658b35ef28156a75e96/LibOS/shim/test/regression/pipe_nonblocking.c#L25)):*
> why we want to add flag_wr == flag_rd check by masking off O_WRONLY/O_RDWR flags? 

To check that Graphene did not add any flags silently.


<!-- Sent from Reviewable.io -->

2021-09-13 17:46 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2524)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 25 at r2](https://reviewable.io/reviews/gramineproject/graphene/2524#-MiRpUqRB3sff9GevVzN:-MjV1sOBDocZvMPoeORV:biweenr) ([raw file](https://github.com/gramineproject/graphene/blob/671b55719350027816aa7658b35ef28156a75e96/LibOS/shim/test/regression/pipe_nonblocking.c#L25)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> why we want to add flag_wr == flag_rd check by masking off O_WRONLY/O_RDWR flags? 

To check that Graphene did not add any flags silently.
</blockquote></details>

Feel we are overloading the intended functionality which is basically to check the `O_NONBLOCK` flag. If we suspect graphene can silently add flags, then it is a bug and it is better to have a separate test case to catch the corner case. But have added the check.


<!-- Sent from Reviewable.io -->

2021-09-13 18:06 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2524)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 48 at r4](https://reviewable.io/reviews/gramineproject/graphene/2524#-MjVKNaQ69m2CHKtO05B:-MjVKNaR9IyVc5cOlF9Y:b-kry9bp) ([raw file](https://github.com/gramineproject/graphene/blob/52954c310c38c644528935a31cc83b143d371796/LibOS/shim/test/regression/pipe_nonblocking.c#L48)):*
> ```C
>              "flags_rd=0x%x", flags_wr, flags_rd);
> 
>     flags_rd = flags_rd & ~O_ACCMODE;
> ```

`F_GETFD` does not return access mode.


<!-- Sent from Reviewable.io -->

2021-09-13 18:18 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2524)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/pipe_nonblocking.c, line 48 at r4](https://reviewable.io/reviews/gramineproject/graphene/2524#-MjVKNaQ69m2CHKtO05B:-MjVNV_j0wuWEqoWT5Za:b-sd92sc) ([raw file](https://github.com/gramineproject/graphene/blob/52954c310c38c644528935a31cc83b143d371796/LibOS/shim/test/regression/pipe_nonblocking.c#L48)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`F_GETFD` does not return access mode.
</blockquote></details>

My bad. Done.


<!-- Sent from Reviewable.io -->

2021-09-13 18:31 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2524)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-09-13 18:31 UTC, boryspoplawski commented
Jenkins, test this please

2021-09-13 18:32 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2524)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2524#-MjVQdqU2lXw4uLyVsur:-MjVQdqVB0bjBsqBeKm1:baiwb4w) (no related file):*
Okey, please move this PR to the new repository

---


<!-- Sent from Reviewable.io -->

2021-09-13 18:34 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2524)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-09-13 21:45 UTC, boryspoplawski commented
Superseded by https://github.com/gramineproject/gramine/pull/35

2021-09-13 21:45 UTC, closed without merging