[Examples] Add OpenVINO benchmarking examples
gramineproject/graphene pull request #2535
Opened 2021-07-13 09:02 UTC by sahason

Signed-off-by: Sonali Saha <sonali.saha@intel.com>

## Description of the changes 
Examples to run "Benchmark C++ Tool" (benchmark_app) from the OpenVINO distribution under Graphene-SGX to estimate deep learning inference performance.

## How to test this PR? 
Please follow steps present at Examples/OpenVINIO/README.md

2021-07-14 08:37 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ6sb87fdMWD9ZoYsr:-MeZ6sb87fdMWD9ZoYss:b-m4obcb) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L49)):*
> ```
> fs.mount.sample_app.type = "chroot"
> fs.mount.sample_app.path = "{{ HOME }}/inference_engine_cpp_samples_build"
> fs.mount.sample_app.uri = "file:{{ HOME }}/inference_engine_cpp_samples_build"
> ```

What is this directory? Why are samples installed under HOME? Is this really needed?
___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 57 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ5yFrEn1eWBW1BSAQ:-MeZ5yFrEn1eWBW1BSAR:bi315yn) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L57)):*
> ```
> # Set the virtual memory size of the SGX enclave. For SGX v1, the enclave
> # size must be specified during signing. If OpenVINO needs more virtual memory
> # than the enclave size, Graphene will not be able to allocate it.
> ```

Can we remove this comment? It doesn't really add any value.
___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ60lH34qsg3Uk1byg:-MeZ60lH34qsg3Uk1byh:bi315yn) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L64)):*
> ```
> # thread for handling inter-process communication (IPC), and potentially another
> # thread for asynchronous events. Therefore, the actual number of threads that
> # the application can create is (sgx.thread_num - 2).
> ```

Can we remove this comment? It doesn't really add any value.
___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ6zlhCzyASU7Zjr52:-MeZ6zlhCzyASU7Zjr53:b-nbb3y1) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L73)):*
> ```
> sgx.trusted_files.inferenceengine_libs = "file:{{ openvino_dir }}/deployment_tools/inference_engine/lib/intel64/"
> sgx.trusted_files.tbb_libs = "file:{{ openvino_dir }}/deployment_tools/inference_engine/external/tbb/lib/"
> sgx.trusted_files.libformatreader = "file:{{ HOME }}/inference_engine_cpp_samples_build/intel64/Release/lib/libformat_reader.so"
> ```

Why this particular line uses HOME? Doesn't look right.
___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 88 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ796T-_v8HkXxiNW_:-MeZ796T-_v8HkXxiNWa:b-8m8ykc) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L88)):*
> ```
> sgx.nonpie_binary = true
> 
> #pre-fault all enclave pages during enclave initialization by uncommenting below line
> ```

But the line is already uncommented. Stale comment? I suggest to simply remove this comment.
___
*[Examples/openvino_benchmark/Makefile, line 36 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ8-Q3BNhsK-lFp18S:-MeZ8-Q3BNhsK-lFp18T:bhp355o) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L36)):*
> ```Makefile
> 
> .PHONY: all
> all: benchmark_app benchmark_app.manifest pal_loader $(VENV_DIR) \
> ```

Please  remove `pal_loader` from here
___
*[Examples/openvino_benchmark/Makefile, line 61 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7Lj85DFX-c54QzW_:-MeZ7Lj85DFX-c54QzWa:bbik4jx) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L61)):*
> ```Makefile
> 	&& deactivate
> 
> $(MODEL_DIR)/public/$(MODEL_RESNET):
> ```

This target should depend on `$(VENV_DIR)`. So if I understand correctly, you should rewrite this line like this:
`$(MODEL_DIR)/public/$(MODEL_RESNET): $(VENV_DIR)`.
___
*[Examples/openvino_benchmark/Makefile, line 68 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7UiBAVxHj_P9hQ10:-MeZ7UiBAVxHj_P9hQ11:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L68)):*
> ```Makefile
> 	&& deactivate
> 
> $(MODEL_DIR)/intel/$(MODEL_BERT):
> ```

ditto
___
*[Examples/openvino_benchmark/Makefile, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7VMK4E9LAnatYspz:-MeZ7VMLAQSt28UXzpA6:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L75)):*
> ```Makefile
> 	&& deactivate
> 
> $(MODEL_DIR)/intel/$(MODEL_BERT_INT8):
> ```

ditto
___
*[Examples/openvino_benchmark/Makefile, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7WKp5d49DWdBttD6:-MeZ7WKp5d49DWdBttD7:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L82)):*
> ```Makefile
> 	&& deactivate
> 
> $(MODEL_DIR)/public/$(MODEL_BRATS0001):
> ```

ditto
___
*[Examples/openvino_benchmark/Makefile, line 89 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7X-B88PFWPAH5FIn:-MeZ7X-B88PFWPAH5FIo:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L89)):*
> ```Makefile
> 	&& deactivate
> 
> $(MODEL_DIR)/public/$(MODEL_BRATS0002):
> ```

ditto
___
*[Examples/openvino_benchmark/Makefile, line 96 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7Xbv421XB0Ocm40K:-MeZ7Xbv421XB0Ocm40L:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L96)):*
> ```Makefile
> 	&& deactivate
> 
> $(MODEL_DIR)/public/$(MODEL_SSD_COCO):
> ```

ditto
___
*[Examples/openvino_benchmark/Makefile, line 114 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7_lV2z8QPyjUfpOG:-MeZ7_lV2z8QPyjUfpOH:b5yt1a6) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L114)):*
> ```Makefile
> # and the token for enclave initialization.
> benchmark_app.manifest.sgx: benchmark_app.manifest \
> 		| benchmark_app
> ```

Can you move this line to the previous line? It belongs there.
___
*[Examples/openvino_benchmark/Makefile, line 115 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7fKCC8LoboP0M-G4:-MeZ7fKCC8LoboP0M-G5:bshh124) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L115)):*
> ```Makefile
> benchmark_app.manifest.sgx: benchmark_app.manifest \
> 		| benchmark_app
> 		graphene-sgx-sign \
> ```

This should have only one-tab indentation level, not two
___
*[Examples/openvino_benchmark/Makefile, line 126 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7k2kEz_Rtmaam3ks:-MeZ7k2kEz_Rtmaam3kt:b-r3h0eu) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L126)):*
> ```Makefile
> benchmark_app:
> 	cd $(OPENVINO_DIR)/deployment_tools/inference_engine/samples/cpp && ./build_samples.sh
> 	ln -s $(HOME)/inference [...]

2021-07-19 10:25 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: 0 of 5 files reviewed, 32 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ6sb87fdMWD9ZoYsr:-Mey5z1O4OnA13YlIeaR:b-kzeiud) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this directory? Why are samples installed under HOME? Is this really needed?
</blockquote></details>

Yes, this is required. Sample gets installed by this command - "cd $(OPENVINO_INSTALLED_DIR)/deployment_tools/inference_engine/samples/cpp && ./build_samples.sh". The build_samples.sh has HOME as default installation directory and there is no option for passing alternate installation location from command line.
___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 57 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ5yFrEn1eWBW1BSAQ:-MeyEOxi9nk8QY3iNxFR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we remove this comment? It doesn't really add any value.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ60lH34qsg3Uk1byg:-MeyEPO0AN7Xhpi00IWL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we remove this comment? It doesn't really add any value.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ6zlhCzyASU7Zjr52:-MeyEQfW4JUS9as_fzax:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this particular line uses HOME? Doesn't look right.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 88 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ796T-_v8HkXxiNW_:-MeyESf_9_YFQs6F78YV:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L88)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But the line is already uncommented. Stale comment? I suggest to simply remove this comment.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 36 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ8-Q3BNhsK-lFp18S:-MeyEjOd5hXZZm_3g69H:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please  remove `pal_loader` from here
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 61 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7Lj85DFX-c54QzW_:-MeyEYJl1jr9Ss1QfkjX:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This target should depend on `$(VENV_DIR)`. So if I understand correctly, you should rewrite this line like this:
`$(MODEL_DIR)/public/$(MODEL_RESNET): $(VENV_DIR)`.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 68 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7UiBAVxHj_P9hQ10:-MeyEZ4O7D1FY4zeBeNh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L68)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7VMK4E9LAnatYspz:-MeyEZJi2UlYJ4OjMDbK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L75)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7WKp5d49DWdBttD6:-MeyE_2oE6PWCxW9QfxV:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 89 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7X-B88PFWPAH5FIn:-MeyE_HxBEPB5DMBMa3t:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 96 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7Xbv421XB0Ocm40K:-MeyEa1z4CNDswsqaK2r:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 114 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7_lV2z8QPyjUfpOG:-MeyEaMvEd3muP1KfPFn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L114)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you move this line to the previous line? It belongs there.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 115 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7fKCC8LoboP0M-G4:-MeyEbn41TsFgpVWhXt9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L115)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should have only one-tab indentation level, not two
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 126 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7k2kEz_Rtmaam3ks:-MeyEdXcBXHdtclirBU3:b-kzeiud) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L126)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Where does this HOME stuff come from? If [...]

2021-07-21 09:29 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ6sb87fdMWD9ZoYsr:-Mf7JJg8DW7LAlI4qDbd:b-hwkaiy) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L49)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Yes, this is required. Sample gets installed by this command - "cd $(OPENVINO_INSTALLED_DIR)/deployment_tools/inference_engine/samples/cpp && ./build_samples.sh". The build_samples.sh has HOME as default installation directory and there is no option for passing alternate installation location from command line.
</blockquote></details>

I see. Can you please add a short comment on this `fs.mount.sample_app` entry then? Something like `# Need to mount HOME because OpenVINO's build_samples.sh always installs samples in this directory`.
___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ6zlhCzyASU7Zjr52:-Mf7JgwbEXiZR9bHbt-F:b-c5t0jg) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L73)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any change. I understand that the samples need to be built under HOME, but `libformatreader` is a generic library of OpenCL, so it should be already covered by e.g. `file:{{ openvino_dir }}/deployment_tools/inference_engine/lib/intel64/`, no?
___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7K-DC3HhdSE6nUNx2:-Mf7K-DC3HhdSE6nUNx3:b-1j6q0e) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/benchmark_app.manifest.template#L7)):*
> ```
> libos.entrypoint = "benchmark_app"
> 
> # Graphene environment, including the path to the library OS 
> ```

We decided to remove all redundant comments from our manifest files, please see https://github.com/oscarlab/graphene/pull/2566.

Could you also remove all unnecesary comments similar to that PR? And also move the manifest options around to resemble the structure in that PR.
___
*[Examples/openvino_benchmark/Makefile, line 114 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7_lV2z8QPyjUfpOG:-Mf7LGlx98K33ad3P8l7:b-2gktsh) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L114)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You removed the `|` sign which is important here
___
*[Examples/openvino_benchmark/Makefile, line 126 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7k2kEz_Rtmaam3ks:-Mf7LVUTD3w5qIbyNeWM:b-42lypt) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L126)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Yes, this is required. Sample gets installed by this command - "cd $(OPENVINO_INSTALLED_DIR)/deployment_tools/inference_engine/samples/cpp && ./build_samples.sh". The build_samples.sh has HOME as default installation directory and there is no option for passing alternate installation location from command line.
</blockquote></details>

Please add a comment about this here.
___
*[Examples/openvino_benchmark/Makefile, line 48 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KdbC1rF5VWQn9dnU:-Mf7KdbC1rF5VWQn9dnV:b6pv8az) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L48)):*
> ```Makefile
> endif
> 
> include ../../Scripts/Makefile.configs
> ```

Why do you need this? Please remove.

I guess you include this because you use `$(ARCH_LIBDIR)`. Please see my comment there.
___
*[Examples/openvino_benchmark/Makefile, line 62 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KKCU5KLH7SehrdVM:-Mf7KKCV2BujSM0LP06U:b-jhvgda) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L62)):*
> ```Makefile
> 
> $(MODEL_DIR)/public/$(MODEL_RESNET): $(VENV_DIR)
> 	. $(VENV_DIR)/bin/activate \
> ```

Just noticed this. Could you replace `.` with `source`? These two commands are equivalent, but `.` is less readable.
___
*[Examples/openvino_benchmark/Makefile, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KRZE0eE8uO7vhQ70:-Mf7KRZE0eE8uO7vhQ71:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L69)):*
> ```Makefile
> 
> $(MODEL_DIR)/intel/$(MODEL_BERT): $(VENV_DIR)
> 	. $(VENV_DIR)/bin/activate \
> ```

ditto
___
*[Examples/openvino_benchmark/Makefile, line 76 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KSJU5aaaSw9pVSdS:-Mf7KSJU5aaaSw9pVSdT:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L76)):*
> ```Makefile
> 
> $(MODEL_DIR)/intel/$(MODEL_BERT_INT8): $(VENV_DIR)
> 	. $(VENV_DIR)/bin/activate \
> ```

ditto
___
*[Examples/openvino_benchmark/Makefile, line 83 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KSz_9gOitufVB29v:-Mf7KSz_9gOitufVB29w:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L83)):*
> ```Makefile
> 
> $(MODEL_DIR)/public/$(MODEL_BRATS0001): $(VENV_DIR)
> 	. $(VENV_DIR)/bin/activate \
> ```

ditto
___
*[Examples/openvino_benchmark/Makefile, line 90 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KTkr7I5Z4L4k8E96:-Mf7KTks80IGcfInzP5o:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L90)):*
> ```Makefile
> 
> $(MODEL_DIR)/public/$(MODEL_BRATS0002): $(VENV_DIR)
> 	. $(VENV_DIR)/bin/activate \
> ```

ditto
___
*[Examples/openvino_benchmark/Makefile, line 97 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KVEB5pT-pkaC2O4D:-Mf7KVEB5pT-pkaC2O4E:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L97)):*
> ```Makefile
> 
> $(MODEL_DIR)/public/$(MODEL_SSD_COCO): $(VENV_DIR)
> 	. $(VENV_DIR)/bin/activate \
> ```

ditto
___
*[Examples/openvino_benchmark/Makefile, line 106 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7Kqya-gZ7j0JRIGBs:-Mf7Kqya-gZ7j0JRIGBt:bnjuj36) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L106)):*
> ```Makefile
> 	graphene-manifest \
> 	-Dlog_level=$(GRAPHENE_LOG_LEVEL) \
> 	-Darch_libdir=$(ARCH_LIBDIR) \
> ```

You shouldn't use `$(ARCH_LIBDIR)` (it is defined in `Makefile.configs` which is deprecated). Please use instead `{{ arch_libdir }}` -- this one is populated by the `graphene-manifest` utility.
___
*[Examples/openvino_benchmark/Makefile, line 108 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7L9jl2zebas5ln2_6:-Mf7L9jl2zebas5ln2_7:b-ioft3k) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L108)):*
> ```Ma [...]

2021-07-22 16:22 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: 2 of 5 files reviewed, 32 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ6sb87fdMWD9ZoYsr:-MfDaptaCvc114f1bkGY:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see. Can you please add a short comment on this `fs.mount.sample_app` entry then? Something like `# Need to mount HOME because OpenVINO's build_samples.sh always installs samples in this directory`.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ6zlhCzyASU7Zjr52:-MfDav06AJJhpPkr4m2X:bjunw0d) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see any change. I understand that the samples need to be built under HOME, but `libformatreader` is a generic library of OpenCL, so it should be already covered by e.g. `file:{{ openvino_dir }}/deployment_tools/inference_engine/lib/intel64/`, no?
</blockquote></details>

I searched for libformatreader in {{ openvino_dir }}/deployment_tools/inference_engine/lib/intel64. This library is not present in this location. I could only find the file in {{ HOME }}/inference_engine_cpp_samples_build/intel64/Release/lib. Hence no change is made.
___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7K-DC3HhdSE6nUNx2:-MfE-thh1At-Q1MWtm5w:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/benchmark_app.manifest.template#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We decided to remove all redundant comments from our manifest files, please see https://github.com/oscarlab/graphene/pull/2566.

Could you also remove all unnecesary comments similar to that PR? And also move the manifest options around to resemble the structure in that PR.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 114 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7_lV2z8QPyjUfpOG:-MfDboFzEOqCz5aI5dD4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L114)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You removed the `|` sign which is important here
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 126 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ7k2kEz_Rtmaam3ks:-MfDbvaE71XoEUkBY8UE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/Makefile#L126)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment about this here.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 48 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KdbC1rF5VWQn9dnU:-MfDcHdsAYSLYgJbAfr9:b-2u999l) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need this? Please remove.

I guess you include this because you use `$(ARCH_LIBDIR)`. Please see my comment there.
</blockquote></details>

I have used {{ arch_libdir }} in manifest.template file. 
I checked latest Makefiles in Examples directory and this PR https://github.com/oscarlab/graphene/pull/2566.  I see this line is included in all places. Could you please help by pointing to any Makefile example which I can follow to make necessary changes as requested.
___
*[Examples/openvino_benchmark/Makefile, line 62 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KKCU5KLH7SehrdVM:-MfDc7Co1w-cn6ypMBEq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just noticed this. Could you replace `.` with `source`? These two commands are equivalent, but `.` is less readable.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KRZE0eE8uO7vhQ70:-MfDc89sB87mcKV3GCgL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 76 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KSJU5aaaSw9pVSdS:-MfDc8RW2m2mWYx3zldZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 83 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KSz_9gOitufVB29v:-MfDc9K-7lz0odR8Fy7k:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L83)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 90 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KTkr7I5Z4L4k8E96:-MfDcA95ELgba7uCawi7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 97 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KVEB5pT-pkaC2O4D:-MfDcB1g8b1Vwvs1jeWl:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 106 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7Kqya-gZ7j0JRIGBs:-MfDfY5R8rkfG6nmyx5s:b-qdlhnf) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L106)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You shouldn't use `$(ARCH_LIBDIR)` (it is defined in `Makefile.configs` which is deprecated). Please use instead `{{ arch_libdir }}` -- this one is populated by the `graphene-manifest` utility.
</blockquote></details>

I have used {{ arch_libdir }} in manifest.template file. 
I checked latest Makefile in Examples directory and this PR  [...]

2021-07-23 06:29 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfGyw3w0TxxbYfzU8QK:-MfGyw3x-EVKH9Ft835D:b-ystrdb) (no related file):*
You added executable permissions to some of your files? Could you remove this and go back to normal RW permissions?

---
___
*[Examples/openvino_benchmark/benchmark_app.manifest.template, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2535#-MeZ6zlhCzyASU7Zjr52:-MfGzCneCD-nBJQ_Pffo:bxcixbi) ([raw file](https://github.com/oscarlab/graphene/blob/23eba3a40eaca91f897512b8fe48246ef951cb3e/Examples/openvino_benchmark/benchmark_app.manifest.template#L73)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I searched for libformatreader in {{ openvino_dir }}/deployment_tools/inference_engine/lib/intel64. This library is not present in this location. I could only find the file in {{ HOME }}/inference_engine_cpp_samples_build/intel64/Release/lib. Hence no change is made.
</blockquote></details>

OK, thanks for explanation.
___
*[Examples/openvino_benchmark/Makefile, line 48 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7KdbC1rF5VWQn9dnU:-MfGzHEh3RbmHOXhVNXE:bllixde) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L48)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I have used {{ arch_libdir }} in manifest.template file. 
I checked latest Makefiles in Examples directory and this PR https://github.com/oscarlab/graphene/pull/2566.  I see this line is included in all places. Could you please help by pointing to any Makefile example which I can follow to make necessary changes as requested.

</blockquote></details>

OK. I plan to remove all these `include Makefile.configs` and `ARCH_DIR` thingies from all Examples, but don't have a corresponding PR yet. So yeah, let's keep this for now, and later I'll remove them all.
___
*[Examples/openvino_benchmark/Makefile, line 106 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7Kqya-gZ7j0JRIGBs:-MfGzYrO0BspyCobqfbX:b-9rhksu) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L106)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I have used {{ arch_libdir }} in manifest.template file. 
I checked latest Makefile in Examples directory and this PR https://github.com/oscarlab/graphene/pull/2566.  I see  is used in all places. Could you please help by pointing to any Makefile example which I can follow to make necessary changes as requested.

</blockquote></details>

OK. I'll do this later (when fixing all examples).
___
*[Examples/openvino_benchmark/Makefile, line 108 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7L9jl2zebas5ln2_6:-MfGzi7YA3911GQMtAhZ:bvqo58u) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L108)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Same as {{ arch_libdir }}.  Could you please help by pointing to any Makefile example which I can follow to make necessary changes as requested.
</blockquote></details>

This is one example: https://github.com/oscarlab/graphene/blob/32831e4410e9a6bcae8e4c143714883b5cae0539/Examples/pytorch/pytorch.manifest.template#L52
___
*[Examples/openvino_benchmark/README.md, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7M9Rt3a03vSincRi_:-MfGzxF837-iLbFa0-ny:b-fr2j0u) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/README.md#L30)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, looks very good now!
___
*[Examples/openvino_benchmark/README.md, line 78 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7NB8k8YqHX9DsWhMq:-MfH0FFRDOSR1WdSu6Di:bxh3n8v) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/README.md#L78)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

The previous one is generalized one. 
In current command I had removed -i <image files> as it's optional. Now I have added it back to keep it consistent. 

Please fine explanation for -m option below.
-m model/<public | intel>/<model_dir>/<INT8 | FP16 | FP32>/<model_xml_file>

When the model files are downloaded based on the model name and precision they would be placed in different location.

The directory structure is as follow.
model
|_____
         public/intel
         |__________
                          model_dir
                           |___________
                                             INT8/FP16/FP32
                                             |______________
                                                                      model xml file

</blockquote></details>

So I still don't like this whole duplication of the command: once with `OPTIMAL_VALUE ` and then with `72` as an example. Maybe we should do like this: the first command is generic:
```
$ export OPTIMAL_VALUE=<number of physical cores * 2>
$ KMP_AFFINITY=granularity=fine,noverbose,compact,1,0 numactl --cpubind=0 --membind=0 \
graphene-sgx benchmark_app -i <image files> \
-m model/<public | intel>/<model_dir>/<INT8 | FP16 | FP32>/<model_xml_file> \
-d CPU -b 1 -t 20 \
-nstreams OPTIMAL_VALUE -nthreads OPTIMAL_VALUE -nireq OPTIMAL_VALUE
```

And for the second command you simply show:
```
$ export OPTIMAL_VALUE=76
```

This way we don't have this duplication of the graphene-sgx command, and it is still easy to follow for the reader.
___
*[Examples/openvino_benchmark/README.md, line 97 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7NQjZC1DTobKNjSvq:-MfH0xZ6ExhR-Zk88XKz:bq3tc5w) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/README.md#L97)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto (replace this whole command with `$ export ...`)
___
*[Examples/openvino_benchmark/README.md, line 129 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7NdK3Akfg2rnVXEZU:-MfH1VQN25y6cRSCKRDz:b-xmpmbq) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/README.md#L129)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

The first one was generalized. I have removed first one and kept only second one. I have removed it now as the command does not change based on the number of cores.
</blockquote></details>

OK, this looks much better, thanks!
___
*[Examples/openvino_benchmark/README.md, line 7 at r3](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfH-BNT7mNrNXZPzAp4:-MfH-BNUDr16W0t7V4Vs:bnb64sm) ([raw file](https://github.com/oscarlab/graphene/blob/a0026e6138d1abe687a5c197451db3454981344d/Examples/openvino_benchmark/README.md#L7)):*
> ```Markdown
> the OpenVINO distribution as a concrete application running under Graphene-SGX to estimate deep
> learning inference performance. We test only the CPU backend (i.e., no GPU or FPGA). This was
> tested on a machine with Ubuntu 18.04 and Python 3.6.
> ```

Please remove `This was tested...`, we decided to remove this info from our examples (see PR https://github.com/oscarlab/graphene/pull/2566). The reason is that this information gets stale very fast, and it doesn't bring much value to the read [...]

2021-07-23 11:37 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: 2 of 5 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfGyw3w0TxxbYfzU8QK:-MfI7a0l1Cyb6Hpkvr-9:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You added executable permissions to some of your files? Could you remove this and go back to normal RW permissions?
</blockquote></details>

Done.

---
___
*[Examples/openvino_benchmark/Makefile, line 108 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7L9jl2zebas5ln2_6:-MfI7gmU74m9TKX7QqdW:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/Makefile#L108)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is one example: https://github.com/oscarlab/graphene/blob/32831e4410e9a6bcae8e4c143714883b5cae0539/Examples/pytorch/pytorch.manifest.template#L52
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 78 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7NB8k8YqHX9DsWhMq:-MfHr2OjAFJJAHnvA0pA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/README.md#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So I still don't like this whole duplication of the command: once with `OPTIMAL_VALUE ` and then with `72` as an example. Maybe we should do like this: the first command is generic:
```
$ export OPTIMAL_VALUE=<number of physical cores * 2>
$ KMP_AFFINITY=granularity=fine,noverbose,compact,1,0 numactl --cpubind=0 --membind=0 \
graphene-sgx benchmark_app -i <image files> \
-m model/<public | intel>/<model_dir>/<INT8 | FP16 | FP32>/<model_xml_file> \
-d CPU -b 1 -t 20 \
-nstreams OPTIMAL_VALUE -nthreads OPTIMAL_VALUE -nireq OPTIMAL_VALUE
```

And for the second command you simply show:
```
$ export OPTIMAL_VALUE=76
```

This way we don't have this duplication of the graphene-sgx command, and it is still easy to follow for the reader.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 97 at r2](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mf7NQjZC1DTobKNjSvq:-MfHrMPU-5B7AncpDweH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4538f54654896e3d627b2beb3a39c4c4c904126c/Examples/openvino_benchmark/README.md#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (replace this whole command with `$ export ...`)
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 7 at r3](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfH-BNT7mNrNXZPzAp4:-MfHq-5C6uSZpYF71zWd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a0026e6138d1abe687a5c197451db3454981344d/Examples/openvino_benchmark/README.md#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `This was tested...`, we decided to remove this info from our examples (see PR https://github.com/oscarlab/graphene/pull/2566). The reason is that this information gets stale very fast, and it doesn't bring much value to the reader.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 42 at r3](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfH-XjGEyyGE_zbmaVl:-MfHqKVKDLp-ad7HMknz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a0026e6138d1abe687a5c197451db3454981344d/Examples/openvino_benchmark/README.md#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this step, this is clear.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 56 at r3](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfH-d6-8_Gzq4KGUcpV:-MfHr-5H1sPh52QUTUUR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a0026e6138d1abe687a5c197451db3454981344d/Examples/openvino_benchmark/README.md#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please put `-nireq -nstreams -nthreads` in backticks.

Also, is this a typo: `For them`? For whom? For the Xeon servers? If so, could you rephrase a bit, otherwise it reads strangely.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 109 at r3](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfH1BaA3Y0MorHPapA2:-MfHvqOVAAg_-q7o0qcd:b-1anams) ([raw file](https://github.com/oscarlab/graphene/blob/a0026e6138d1abe687a5c197451db3454981344d/Examples/openvino_benchmark/README.md#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Somewhere in this sentence, a comma is missing... Hard to read, please add a comma or a dot (split into two sentences).

Also, please add backticks around `numactl --membind`.
</blockquote></details>

Done. I have rephrased the sentence.
___
*[Examples/openvino_benchmark/README.md, line 133 at r3](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfH1dX3Ed-K7koCmhmA:-MfHw4LF65Sl8BVE43EQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a0026e6138d1abe687a5c197451db3454981344d/Examples/openvino_benchmark/README.md#L133)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`invocation` -> `startup`.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 135 at r3](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfH1jxv0-OuXwL1RvoA:-MfHwVsA27pPn_5O1p-3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a0026e6138d1abe687a5c197451db3454981344d/Examples/openvino_benchmark/README.md#L135)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`does not pass any invalid pointers` -> `does not invoke system calls with invalid pointers (typical case)`
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 141 at r3](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfH1uH88pkA80G4sC7H:-MfHxXXB0OFdytKt3v6G:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a0026e6138d1abe687a5c197451db3454981344d/Examples/openvino_benchmark/README.md#L141)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Please` -> `please` (start with small letter)
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 142 at r3](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfH1zus4xZrcREKIqTH:-MfHxb6t7_onmKVrgOFh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a0026e6138d1abe687a5c197451db3454981344d/Examples/openvino_benchmark/README.md#L142)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add backticks here
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 143 at r3](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfH21Uv22xhZnJHhQ3y:-MfHxz8s0diVG8EktfpC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a0026e6138d1abe687a5c197451db3454981344d/Examples/openvino_benchmark/README.md#L143)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a `:`
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 153 at r3](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfH2OeHChuJkDoMyoC_:-MfHyKH453oLrxmgWg6a:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob [...]

2021-07-26 06:37 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[Examples/openvino_benchmark/README.md, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWUj945p3_r63ofAsx:-MfWUj945p3_r63ofAsy:b-6yof3m) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L1)):*
> ```Markdown
> Enabling OpenVINO benchmark runs with Graphene-SGX
> ```

Let's just call it `OpenVINO benchmark`
___
*[Examples/openvino_benchmark/README.md, line 10 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWUuyXB2TUKiFcGekS:-MfWUuyXB2TUKiFcGekT:batzpse) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L10)):*
> ```Markdown
> Note: the models require ~3GB of disk space.
> 
> # Pre-system setting
> ```

What does it mean, `pre-system`? Was it supposed to be `per-system`? Maybe rephrase to something else, like `Tips for better performance`?
___
*[Examples/openvino_benchmark/README.md, line 20 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWV8M_Cx5_NndaHAF5:-MfWV8M_Cx5_NndaHAF6:b-eqnpnn) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L20)):*
> ```Markdown
> ```
> 
> # Bare-metal
> ```

Now we don't have GSC part here, we can remove this `Bare-metal` title.
___
*[Examples/openvino_benchmark/README.md, line 50 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWVNz-BYLiCBLeIOIb:-MfWVNz-BYLiCBLeIOIc:bgerkrt) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L50)):*
> ```Markdown
> **NOTE**: After setting up OpenVINO environment variables if you want to build graphene after
> cleaning you need to unset LD_LIBRARY_PATH. Please make sure to set up OpenVINO environment
> variables after building graphene again.
> ```

Please replace `graphene` with `Graphene` (starting with capital letter) everywhere in this file.
___
*[Examples/openvino_benchmark/README.md, line 55 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWUFio4iAZPINGYSXO:-MfWUFio4iAZPINGYSXP:b-sevhbu) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L55)):*
> ```Markdown
> Performance benchmark on Xeon servers (Silver/Gold/Platinum) must be launched with increased number
> of inference requests. Options ``-nireq``, ``-nstreams`` and ``-nthreads`` should be set to the
> ``number of physical cores * 2`` (take into account hyperthreading) for achieving maximal
> ```

`maximal` -> `maximum`? But I'm not sure here, just never saw people using `maximal` before.
___
*[Examples/openvino_benchmark/README.md, line 58 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWVZiRCWnC7OT_56kW:-MfWVZiRCWnC7OT_56kX:b-7lcmb) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L58)):*
> ```Markdown
> performance.
> 
> **NOTE** To get 'number of physical cores', do ``lscpu | grep 'Core(s) per socket'``
> ```

Please add `:` after NOTE, and add a dot at the end.
___
*[Examples/openvino_benchmark/README.md, line 77 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWVnD09lxpKIrur3H1:-MfWVnD09lxpKIrur3H2:b-pywdvl) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L77)):*
> ```Markdown
> ```
> 
> #### Bare-metal
> ```

We typicall call these `Native` (or `Direct`, choose whichever one you prefer)
___
*[Examples/openvino_benchmark/README.md, line 97 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWU9WN7ymr4lHGm4Sp:-MfWU9WN7ymr4lHGm4Sq:b7mlne6) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L97)):*
> ```Markdown
> the models these are stored in ``model/public`` directory.  
> **NOTE 4**: Based on the precision for bert-large and brain-tumor-segmentation models the enclave
> size must be set to 64/128 GB.  
> ```

Here and above, you have trailing whitespaces. Please remove them.
___
*[Examples/openvino_benchmark/README.md, line 109 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWWCBVAo1OvrS6n92o:-MfWWCBW0oGq2aezy5Xc:bv9vh6o) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L109)):*
> ```Markdown
> graphene-sgx benchmark_app -i <image files> \
> -m model/<public | intel>/<model_dir>/<INT8 | FP16 | FP32>/<model_xml_file> \
> -d CPU -t 20 -b 1 -api sync
> ```

I noticed that in `Throughput runs`, you write `-d CPU -b 1 -t 20`. But here, in `Latency runs`, you write `-d CPU -t 20 -b 1`. So you swap places for `-t` and `-b` parameters. Is there a reason for this? If there is no reason for this swap, could you unify to the same format (the same ordering)? This will improve readability.
___
*[Examples/openvino_benchmark/README.md, line 112 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWVtdk-xqrFG1mowC-:-MfWVtdk-xqrFG1mowC0:b-pywdvl) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L112)):*
> ```Markdown
> ```
> 
> #### Bare-metal
> ```

We typicall call these `Native` (or `Direct`, choose whichever one you prefer)
___
*[Examples/openvino_benchmark/README.md, line 115 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWWneQ0C6TThoTBmVo:-MfWWneQ0C6TThoTBmVp:b-jo8ts4) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L115)):*
> ```Markdown
> ```
> $ KMP_AFFINITY=granularity=fine,noverbose,compact,1,0 numactl --cpubind=0 --membind=0 \
> ./benchmark_app -i <image files> -m model/<public | intel>/<model_dir>/<INT8 | FP16 | FP32>/<model_xml_file> \
> ```

Could you put `-m model/...` on a separate line, just like you have it in all other cases?
___
*[Examples/openvino_benchmark/README.md, line 116 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWWbnw0Q5RMqyWFkFW:-MfWWbnw0Q5RMqyWFkFX:b-15p3rf) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L116)):*
> ```Markdown
> $ KMP_AFFINITY=granularity=fine,noverbose,compact,1,0 numactl --cpubind=0 --membind=0 \
> ./benchmark_app -i <image files> -m model/<public | intel>/<model_dir>/<INT8 | FP16 | FP32>/<model_xml_file> \
> -d CPU -t 20 -b 1 -api sync
> ```

ditto (ordering of parameters)
___
*[Examples/openvino_benchmark/README.md, line 119 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWWstfBxn-LvNa5ght:-MfWWstfBxn-LvNa5ghu:b-uh97tq) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L119)):*
> ```Markdown
> ```
> 
> **NOTE**: Option ``-i <image files>`` is optional. A user may use this option as required.
> ```

Actually, what happens if this option is not specified? The benchmark app will create some dummy random images? Just curious.


<!-- Sent from Reviewable.io -->

2021-07-26 08:41 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: 4 of 5 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Examples/openvino_benchmark/README.md, line 153 at r3](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfH2Sya9xP50h4iJcee:-MfI8tr7D1eDM7t2rheu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a0026e6138d1abe687a5c197451db3454981344d/Examples/openvino_benchmark/README.md#L153)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have a tab here instead of spaces.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWUj945p3_r63ofAsx:-MfWoQfx3j13NdDRkpYp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's just call it `OpenVINO benchmark`
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 10 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWUuyXB2TUKiFcGekS:-MfWoYoQEXrbCAx0qQYV:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does it mean, `pre-system`? Was it supposed to be `per-system`? Maybe rephrase to something else, like `Tips for better performance`?
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 20 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWV8M_Cx5_NndaHAF5:-MfWo_gD28KvL0c4JceE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now we don't have GSC part here, we can remove this `Bare-metal` title.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 50 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWVNz-BYLiCBLeIOIb:-MfWoiaF4KOsQrhWsACf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace `graphene` with `Graphene` (starting with capital letter) everywhere in this file.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 55 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWUFio4iAZPINGYSXO:-MfWooAT4AQ8vfuKQl7k:b-6h58fu) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L55)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`maximal` -> `maximum`? But I'm not sure here, just never saw people using `maximal` before.
</blockquote></details>

I have changed it to maximum.
___
*[Examples/openvino_benchmark/README.md, line 58 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWVZiRCWnC7OT_56kW:-MfWozez3LUPkusAdy9i:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `:` after NOTE, and add a dot at the end.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 77 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWVnD09lxpKIrur3H1:-MfWp8ZW0qywtdc5u0nZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L77)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We typicall call these `Native` (or `Direct`, choose whichever one you prefer)
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 97 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWU9WN7ymr4lHGm4Sp:-MfWpHqz2eQjM_fB78bn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here and above, you have trailing whitespaces. Please remove them.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 109 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWWCBVAo1OvrS6n92o:-MfWpRYTEEXQNK_b9GHF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I noticed that in `Throughput runs`, you write `-d CPU -b 1 -t 20`. But here, in `Latency runs`, you write `-d CPU -t 20 -b 1`. So you swap places for `-t` and `-b` parameters. Is there a reason for this? If there is no reason for this swap, could you unify to the same format (the same ordering)? This will improve readability.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 112 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWVtdk-xqrFG1mowC-:-MfWpTVL1Bl0kPJDWiSv:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We typicall call these `Native` (or `Direct`, choose whichever one you prefer)
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 115 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWWneQ0C6TThoTBmVo:-MfWpZ4X3QkHHKTgMBJG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L115)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you put `-m model/...` on a separate line, just like you have it in all other cases?
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 116 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWWbnw0Q5RMqyWFkFW:-MfWp_g-33sUyUBaDKK5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (ordering of parameters)
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 119 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWWstfBxn-LvNa5ght:-MfWpeMG3IK9q9HdUpxq:b-20nlbq) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L119)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, what happens if this option is not specified? The benchmark app will create some dummy random images? Just curious.
</blockquote></details>

Yes, as you have mentioned the benchmark app will create some dummy random images.


<!-- Sent from Reviewable.io -->

2021-07-26 15:12 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[Examples/openvino_benchmark/README.md, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWUj945p3_r63ofAsx:-MfYLNcs6081CNt1CHVH:bypim2a) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L1)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I meant the whole title text should be `OpenVINO benchmark` (no need for `runs with Graphene-SGX`)
___
*[Examples/openvino_benchmark/README.md, line 2 at r5](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfYMfXRBD1-XIMuayWy:-MfYMfXRBD1-XIMuayWz:b9rp5ha) ([raw file](https://github.com/oscarlab/graphene/blob/e2f039e0a798325fc9ae80159cd14840fda2076f/Examples/openvino_benchmark/README.md#L2)):*
> ```Markdown
> OpenVINO benchmark runs with Graphene-SGX
> =====================================================
> ```

Actually, where is this `====` pattern from? (Probably from the older version that had `.rst` file). We should do the classic Markdown titles with `#`:
```
# OpenVINO benchmark

This directory contains ...
```

See e.g. the formatting in https://raw.githubusercontent.com/oscarlab/graphene/master/Examples/bash/README.md
___
*[Examples/openvino_benchmark/README.md, line 10 at r5](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfYMIVY0XwZLyGJ9xJD:-MfYMIVY0XwZLyGJ9xJE:bjrbz2m) ([raw file](https://github.com/oscarlab/graphene/blob/e2f039e0a798325fc9ae80159cd14840fda2076f/Examples/openvino_benchmark/README.md#L10)):*
> ```Markdown
> Note: the models require ~3GB of disk space.
> 
> # Tips for better performance
> ```

Please make it `##` (second-level title), to have the same level as `Software Requirements`, `Running the Benchmark`, etc.
___
*[Examples/openvino_benchmark/README.md, line 46 at r5](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfYLWbdEzAgNajlvV5U:-MfYLWbdEzAgNajlvV5V:b-du4cg8) ([raw file](https://github.com/oscarlab/graphene/blob/e2f039e0a798325fc9ae80159cd14840fda2076f/Examples/openvino_benchmark/README.md#L46)):*
> ```Markdown
> 3. Build: ``make SGX=1``
> 
> **NOTE**: After setting up OpenVINO environment variables if you want to build graphene after
> ```

`graphene` -> `Graphene`
___
*[Examples/openvino_benchmark/README.md, line 95 at r5](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfYM-_O2UJcHATzc9Kz:-MfYM-_O2UJcHATzc9L-:bcm0ohg) ([raw file](https://github.com/oscarlab/graphene/blob/e2f039e0a798325fc9ae80159cd14840fda2076f/Examples/openvino_benchmark/README.md#L95)):*
> ```Markdown
> the models these are stored in ``model/public`` directory.\
> **NOTE 4**: Based on the precision for bert-large and brain-tumor-segmentation models the enclave
> size must be set to 64/128 GB.\
> ```

Please don't use `\` to create a new line. Just use an empty line in-between your NOTEs for this.
___
*[Examples/openvino_benchmark/README.md, line 120 at r5](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfYMXiH93C8hyOXU7jL:-MfYMXiH93C8hyOXU7jM:bjrbz2m) ([raw file](https://github.com/oscarlab/graphene/blob/e2f039e0a798325fc9ae80159cd14840fda2076f/Examples/openvino_benchmark/README.md#L120)):*
> ```Markdown
> **NOTE**: Option ``-i <image files>`` is optional. A user may use this option as required.
> 
> # Performance considerations
> ```

Please make it `##` (second-level title), to have the same level as `Software Requirements`, `Running the Benchmark`, etc.


<!-- Sent from Reviewable.io -->

2021-07-27 05:09 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: 4 of 5 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Examples/openvino_benchmark/README.md, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfWUj945p3_r63ofAsx:-MfaFHMr4KJY3kpNjeK4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e902371b788b2f097911ff2380fb4b623158271/Examples/openvino_benchmark/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, I meant the whole title text should be `OpenVINO benchmark` (no need for `runs with Graphene-SGX`)
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 2 at r5](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfYMfXRBD1-XIMuayWy:-MfaF_3z1x8d_W_95A5C:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e2f039e0a798325fc9ae80159cd14840fda2076f/Examples/openvino_benchmark/README.md#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, where is this `====` pattern from? (Probably from the older version that had `.rst` file). We should do the classic Markdown titles with `#`:
```
# OpenVINO benchmark

This directory contains ...
```

See e.g. the formatting in https://raw.githubusercontent.com/oscarlab/graphene/master/Examples/bash/README.md
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 10 at r5](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfYMIVY0XwZLyGJ9xJD:-MfaFdwi-nZC8rQK0qwa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e2f039e0a798325fc9ae80159cd14840fda2076f/Examples/openvino_benchmark/README.md#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please make it `##` (second-level title), to have the same level as `Software Requirements`, `Running the Benchmark`, etc.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 46 at r5](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfYLWbdEzAgNajlvV5U:-MfaFwsSAHEWi8uddbNI:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e2f039e0a798325fc9ae80159cd14840fda2076f/Examples/openvino_benchmark/README.md#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`graphene` -> `Graphene`
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 95 at r5](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfYM-_O2UJcHATzc9Kz:-MfaG5aN9yNqOvvsVTQd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e2f039e0a798325fc9ae80159cd14840fda2076f/Examples/openvino_benchmark/README.md#L95)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please don't use `\` to create a new line. Just use an empty line in-between your NOTEs for this.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 120 at r5](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfYMXiH93C8hyOXU7jL:-MfaGDRH0XqgVtazT3O6:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e2f039e0a798325fc9ae80159cd14840fda2076f/Examples/openvino_benchmark/README.md#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please make it `##` (second-level title), to have the same level as `Software Requirements`, `Running the Benchmark`, etc.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-27 08:12 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mfb0OQ20bZkbRbh6kH2:-Mfb0OQ20bZkbRbh6kH3:bs2v8p7) (no related file):*
Please re-test your OpenVINO benchmark example again, just to make sure we didn't screw up anywhere during the review process. But it looks ready from my side!

---
___
*[Examples/openvino_benchmark/README.md, line 125 at r6](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mfb0Hax91ZozUFFl7bb:-Mfb0Hay5iQeykedLqVI:bh6m92i) ([raw file](https://github.com/oscarlab/graphene/blob/9f2d62b79f2855b83688d9bd44434289b510d7a6/Examples/openvino_benchmark/README.md#L125)):*
> ```Markdown
> ## Performance considerations
> - Preheat manifest option pre-faults the enclave memory and moves the performance penalty to
> graphene-sgx startup (before the workload starts executing). To use preheat option, add
> ```

`graphene-sgx` -> `Graphene-SGX`


<!-- Sent from Reviewable.io -->

2021-07-27 08:58 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: 4 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mfb0OQ20bZkbRbh6kH2:-Mfb9u685BgDRQsPrlJY:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-test your OpenVINO benchmark example again, just to make sure we didn't screw up anywhere during the review process. But it looks ready from my side!
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-07-28 07:20 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2535#-MffwcLw5N_sf3mV2d2Z:-MffwcLx55bOOFN1Z_0r:b33mnbf) (no related file):*
Just realized that you don't have `.gitignore` file in your example. This file is needed to inform git to ignore the new (downloaded, generated, etc.) files. Please see how this example: https://github.com/sahason/graphene/blob/ov_benchmark/Examples/openvino/.gitignore. And apply a similar list of ignored files/dirs.

---
___
*[Examples/openvino_benchmark/Makefile, line 10 at r7](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mffy9V4-QmSxomyK98J:-Mffy9V4-QmSxomyK98K:b-v6y78f) ([raw file](https://github.com/oscarlab/graphene/blob/97fd81b6bf4e5803385f66718d42ff86d38e90fc/Examples/openvino_benchmark/Makefile#L10)):*
> ```Makefile
> # Use `make clean` to remove Graphene-generated files.
> # Use `make distclean` to further remove model directory and venv directory
> #
> ```

Please remove all these comments. (I reworked Examples in the meantime, see the new versions, e.g. https://github.com/oscarlab/graphene/blob/master/Examples/openvino/Makefile)
___
*[Examples/openvino_benchmark/Makefile, line 27 at r7](https://reviewable.io/reviews/oscarlab/graphene/2535#-MffygGPDDmjMmAGr_gQ:-MffygGPDDmjMmAGr_gR:bp8eyx) ([raw file](https://github.com/oscarlab/graphene/blob/97fd81b6bf4e5803385f66718d42ff86d38e90fc/Examples/openvino_benchmark/Makefile#L27)):*
> ```Makefile
> 
> # Relative path to Graphene root and key for enclave signing
> GRAPHENE_DIR ?= ../..
> ```

Please remove the comment and `GRAPHENE_DIR`, as explained in this PR: https://github.com/oscarlab/graphene/pull/2582. See the example here: https://github.com/oscarlab/graphene/blob/dimakuv/unbind-examples-from-makefiles/Examples/openvino/Makefile
___
*[Examples/openvino_benchmark/Makefile, line 49 at r7](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mffz22G5BXK-QLKIZTn:-Mffz22HCB6xItRakA3C:b-99t18k) ([raw file](https://github.com/oscarlab/graphene/blob/97fd81b6bf4e5803385f66718d42ff86d38e90fc/Examples/openvino_benchmark/Makefile#L49)):*
> ```Makefile
> endif
> 
> include ../../Scripts/Makefile.configs
> ```

Please remove this (see my example in https://github.com/oscarlab/graphene/blob/dimakuv/unbind-examples-from-makefiles/Examples/openvino/Makefile)
___
*[Examples/openvino_benchmark/Makefile, line 112 at r7](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mffz-ao6-WvBiPbDL8j:-Mffz-ao6-WvBiPbDL8k:b-r305lk) ([raw file](https://github.com/oscarlab/graphene/blob/97fd81b6bf4e5803385f66718d42ff86d38e90fc/Examples/openvino_benchmark/Makefile#L112)):*
> ```Makefile
> 
> # Generating the SGX-specific manifest (benchmark_app.manifest.sgx), the enclave signature,
> # and the token for enclave initialization.
> ```

Please remove this comment
___
*[Examples/openvino_benchmark/Makefile, line 114 at r7](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mffyt4l-B7XZVBKPsyo:-Mffyt4l-B7XZVBKPsyp:b-pbvxif) ([raw file](https://github.com/oscarlab/graphene/blob/97fd81b6bf4e5803385f66718d42ff86d38e90fc/Examples/openvino_benchmark/Makefile#L114)):*
> ```Makefile
> # and the token for enclave initialization.
> benchmark_app.manifest.sgx: benchmark_app.manifest | benchmark_app
> 	graphene-sgx-sign \
> ```

Please add the testing for `SGX_SIGNER_KEY`, see example here: See the example here: https://github.com/oscarlab/graphene/blob/dimakuv/unbind-examples-from-makefiles/Examples/openvino/Makefile. This is a change from my new PR: https://github.com/oscarlab/graphene/pull/2582
___
*[Examples/openvino_benchmark/README.md, line 7 at r7](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mffx1uF2eEX9uzuKlTb:-Mffx1uF2eEX9uzuKlTc:bwn70f4) ([raw file](https://github.com/oscarlab/graphene/blob/97fd81b6bf4e5803385f66718d42ff86d38e90fc/Examples/openvino_benchmark/README.md#L7)):*
> ```Markdown
> learning inference performance. We test only the CPU backend (i.e., no GPU or FPGA).
> 
> Note: the models require ~3GB of disk space.
> ```

All other notes you have as `**NOTE**` (capital letters and in bold). Please fix this one similarly.
___
*[Examples/openvino_benchmark/README.md, line 145 at r7](https://reviewable.io/reviews/oscarlab/graphene/2535#-MffxaNV1gW4TvCj-7cq:-MffxaNV1gW4TvCj-7cr:b2xb8hv) ([raw file](https://github.com/oscarlab/graphene/blob/97fd81b6bf4e5803385f66718d42ff86d38e90fc/Examples/openvino_benchmark/README.md#L145)):*
> ```Markdown
>     - Add these in the manifest template:
>         - ``loader.env.LD_PRELOAD = "/usr/local/lib/mimalloc-1.7/libmimalloc.so.1.7"``
>         - ``sgx.trusted_files.libmimalloc = "file:/usr/local/lib/mimalloc-1.7/libmimalloc.so.1.7"``
> ```

You `mimalloc` instructions are not sufficient. You cannot use `/usr/local/` directory because it is not mounted via `fs.mount.blablabla` syntax in your manifest file. So you should either add an instruction to add this `fs.mount.` syntax for `/usr/local/`, or you should just add it in the manifest file itself.


<!-- Sent from Reviewable.io -->

2021-07-28 12:02 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: 3 of 6 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2535#-MffwcLw5N_sf3mV2d2Z:-MfgwKQq6pUej5ElL41I:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just realized that you don't have `.gitignore` file in your example. This file is needed to inform git to ignore the new (downloaded, generated, etc.) files. Please see how this example: https://github.com/sahason/graphene/blob/ov_benchmark/Examples/openvino/.gitignore. And apply a similar list of ignored files/dirs.
</blockquote></details>

Done.

---
___
*[Examples/openvino_benchmark/Makefile, line 10 at r7](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mffy9V4-QmSxomyK98J:-MfgwM885QGSesvvWACy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/97fd81b6bf4e5803385f66718d42ff86d38e90fc/Examples/openvino_benchmark/Makefile#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove all these comments. (I reworked Examples in the meantime, see the new versions, e.g. https://github.com/oscarlab/graphene/blob/master/Examples/openvino/Makefile)
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 27 at r7](https://reviewable.io/reviews/oscarlab/graphene/2535#-MffygGPDDmjMmAGr_gQ:-MfgwPoFA57_vVgO_z1l:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/97fd81b6bf4e5803385f66718d42ff86d38e90fc/Examples/openvino_benchmark/Makefile#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the comment and `GRAPHENE_DIR`, as explained in this PR: https://github.com/oscarlab/graphene/pull/2582. See the example here: https://github.com/oscarlab/graphene/blob/dimakuv/unbind-examples-from-makefiles/Examples/openvino/Makefile
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 49 at r7](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mffz22G5BXK-QLKIZTn:-Mfgwx2p4O0xH8ioZvz2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/97fd81b6bf4e5803385f66718d42ff86d38e90fc/Examples/openvino_benchmark/Makefile#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this (see my example in https://github.com/oscarlab/graphene/blob/dimakuv/unbind-examples-from-makefiles/Examples/openvino/Makefile)
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 112 at r7](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mffz-ao6-WvBiPbDL8j:-Mfgx55D8Ohbx-poRcs2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/97fd81b6bf4e5803385f66718d42ff86d38e90fc/Examples/openvino_benchmark/Makefile#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this comment
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 114 at r7](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mffyt4l-B7XZVBKPsyo:-MfgxBcBC2glTkPw3opb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/97fd81b6bf4e5803385f66718d42ff86d38e90fc/Examples/openvino_benchmark/Makefile#L114)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add the testing for `SGX_SIGNER_KEY`, see example here: See the example here: https://github.com/oscarlab/graphene/blob/dimakuv/unbind-examples-from-makefiles/Examples/openvino/Makefile. This is a change from my new PR: https://github.com/oscarlab/graphene/pull/2582
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 7 at r7](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mffx1uF2eEX9uzuKlTb:-MfgxEzb-KqfMnt_wHKl:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/97fd81b6bf4e5803385f66718d42ff86d38e90fc/Examples/openvino_benchmark/README.md#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

All other notes you have as `**NOTE**` (capital letters and in bold). Please fix this one similarly.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 145 at r7](https://reviewable.io/reviews/oscarlab/graphene/2535#-MffxaNV1gW4TvCj-7cq:-MfgxFmX9WGiYr2fCMF3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/97fd81b6bf4e5803385f66718d42ff86d38e90fc/Examples/openvino_benchmark/README.md#L145)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You `mimalloc` instructions are not sufficient. You cannot use `/usr/local/` directory because it is not mounted via `fs.mount.blablabla` syntax in your manifest file. So you should either add an instruction to add this `fs.mount.` syntax for `/usr/local/`, or you should just add it in the manifest file itself.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 15:31 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mfhj3RC52JYklcVnKx6:-Mfhj3RC52JYklcVnKx7:bvzt3rf) (no related file):*
BTW, we should probably remove the previous OpenVINO example and replace it with this one. This is not for this PR, but something to discuss later.

@sahason Do you think there is any benefit of having the old OpenVINO example side-by-side with your new one? Or your new one completely supersedes the old one?

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2535#-MfhjMEw--XoauayOqfE:-MfhjMEw--XoauayOqfF:b-a7gi15) (no related file):*
Looks good to me, let's wait for other reviews. In the meantime, I should test that this README actually works as expected.

---


<!-- Sent from Reviewable.io -->

2021-07-29 07:45 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mfhj3RC52JYklcVnKx6:-MflB6fC23hoY7KioS1Z:bt6lu39) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

BTW, we should probably remove the previous OpenVINO example and replace it with this one. This is not for this PR, but something to discuss later.

@sahason Do you think there is any benefit of having the old OpenVINO example side-by-side with your new one? Or your new one completely supersedes the old one?
</blockquote></details>

No the new one does not supersedes the old one. These two examples have different application as entry point. Old one is based on "object detection sample ssd" whereas new one is using a benchmarking application.

---


<!-- Sent from Reviewable.io -->

2021-07-29 18:12 UTC, vijaydhanraj commented
IIRC, to enable `benchmark_app` with the existing openvino example all that is needed would be a simple change to the `makefile` to build `benchmark_app` instead of `object detection sample ssd`. Attaching my old `makefile` as a reference.

So, if we want to merge these two, it should be possible. Just a suggestion.
[openvino_benchmark_app_makefile_patch.txt](https://github.com/oscarlab/graphene/files/6902713/openvino_benchmark_app_makefile_patch.txt)

2021-07-30 05:49 UTC, sahason commented
Also, I have made below changes in new one.
1. Installing OpenVINO from distribution as per requirement than building it from a specific version.
2. Automatically download models like bert-large, resnet-50-tf, brain-tumor-segmentation-* etc. which can be used for benchmarking.
3. Have separate and optimized commands for throughput and latency runs.

2021-07-30 06:32 UTC, dimakuv approved these changes
Well, sounds to me like this new example is much more useful than the older one. The old one runs a sample application (`object_detection_sample_ssd`) whereas this new one runs actual practical models and shows perf results.

I vote for removing the existing OpenVINO example (+ bring any useful parts from it to this new example).

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535#-:-Mfq5vI7Dg9w9-jxHqDO:b-scbx8b)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @sahason)



<!-- Sent from Reviewable.io -->

2021-08-30 08:44 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: 2 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mi3tkKg3n5zyDqxvfMN:-MiLAKI4DGW2G3kgAPMo:b-dopk6) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

// Moving into a thread.

> Well, sounds to me like this new example is much more useful than the older one. The old one runs a sample application (object_detection_sample_ssd) whereas this new one runs actual practical models and shows perf results.
> I vote for removing the existing OpenVINO example (+ bring any useful parts from it to this new example).

@sahason Could you do this? I'd rename this one to just "openvino" then.
</blockquote></details>

I will do that. Please confirm deletion of existing files from openvino directory.

---
___
*[Examples/openvino_benchmark/Makefile, line 1 at r8](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mi3uTmn3Q-dUOOEeM9d:-MiK4HjW9-rPcSbnRslr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/16d09f590e9704a869d030729ea6aa36b0db4abf/Examples/openvino_benchmark/Makefile#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> SHELL := /bin/bash
> ```

Why is this needed? For `source $(VENV_DIR)/bin/activate` I guess? If so, then please add an explanatory comment, this is quite unexpected here.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/Makefile, line 50 at r8](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mi3uely70WRvecPp0DI:-MiL5x6v533KXy7N60US:b8l3ett) ([raw file](https://github.com/oscarlab/graphene/blob/16d09f590e9704a869d030729ea6aa36b0db4abf/Examples/openvino_benchmark/Makefile#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please deduplicate this and the rules below using Make's patterns.
</blockquote></details>

I have added these two lines to the target of all model downloads to activate the virtual environment for subsequent models in case downloading of any of the models fails.  Also, I have not joined all model downloading under a single target to download a specific model separately. Hope this clarifies. If this is not the correct understanding of your comment by me request you to elaborate/give example.
___
*[Examples/openvino_benchmark/Makefile, line 114 at r8](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mi3vSEz55EFIc_1UgFC:-MiL4gTC7hA4-ok7tB88:b-o8pbqf) ([raw file](https://github.com/oscarlab/graphene/blob/16d09f590e9704a869d030729ea6aa36b0db4abf/Examples/openvino_benchmark/Makefile#L114)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Waaait, we can't copy some files to the host user's home folder here. The user has no way to expect this (they are just building some Graphene example...).
Are you sure that this OpenVINO's script can't be parametrized? Is this really the intended way to build OpenVINO examples? Sounds pretty bad.
</blockquote></details>

There is no option available to parametrize  build_samples.sh script. Updated the Makefile to build samples manually instead of script. The samples are saved now inside this Examples/openvino_benchmark/ instead of user's home.
___
*[Examples/openvino_benchmark/README.md, line 16 at r8](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mi3vg4c2BuzpPzkQQJF:-MiKMulmEidA_1BLQCE2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/16d09f590e9704a869d030729ea6aa36b0db4abf/Examples/openvino_benchmark/README.md#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please reformat + use Bash syntax highlighting in Markdown.
Should be something like:
```Bash
for ((i=0; i<$(nproc); i++)); do
    echo 'performance' > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor
done
```

Ditto for other shell listings here, the formatting/wrapping used there makes them hard to read.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-31 18:43 UTC, mkow reviewed
> Reviewed 1 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2535)* status: 3 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2535#-Mi3tkKg3n5zyDqxvfMN:-MiSW9ls1LhHSA19KvB9:bjowk3s) (no related file):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I will do that. Please confirm deletion of existing files from openvino directory.
</blockquote></details>

Yup, that's what I meant.

---


<!-- Sent from Reviewable.io -->

2021-09-22 14:14 UTC, sahason commented
This PR was transferred to gramineproject/examples#6. Closing here.

2021-09-22 14:15 UTC, closed without merging