[Pal/Linux] Cap max available address for LibOS's memory management
gramineproject/graphene pull request #2595
Opened 2021-07-29 15:05 UTC by dimakuv

## Description of the changes 

During fork, the parent process checkpoints LibOS-managed memory regions and the child process restores them at the exact same addresses. However, the child process's main executable (`libpal.so`) may be mapped randomly because we don't use fork for this emulation (which would preserve the libpal.so memory mapping) but execve (which allows Linux host to perform ASLR on `libpal.so`). This leads to transient failures of the child because its `libpal.so`'s memory region may overlap with restored-from-checkpoint memory regions.

This commit restricts the memory range accessible to LibOS for memory management. Since Linux allocates from the top of the x86-64 address range (in approx. `0x7f...` range), we hard-code a max available address for LibOS memory management to definitely not overlap with `0x7f...` range.

For more context, see https://github.com/oscarlab/graphene/issues/2589.

Fixes #2589.

## How to test this PR? 

Try stress-ng manually (#2589).

2021-07-29 17:49 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-MfnNcBs8aHsaJEv5Tgb:bx9cr4j) (no related file):*
@dimakuv Please check #2597 for an alternative solution that does not hardcode any addresses.

---


<!-- Sent from Reviewable.io -->

2021-07-30 06:51 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-MfqASYfChmpwmjGnu8t:b-qnz7bz) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@dimakuv Please check #2597 for an alternative solution that does not hardcode any addresses.
</blockquote></details>

@boryspoplawski Unfortunately, it doesn't work under Docker with default seccomp policies. For this reason, I would prefer my fix. Or is there any particular issue with this hard-coding approach?

---


<!-- Sent from Reviewable.io -->

2021-07-30 12:44 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-MfrPvQw570q9lbGgrN_:b-ohxxbt) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Unfortunately, it doesn't work under Docker with default seccomp policies. For this reason, I would prefer my fix. Or is there any particular issue with this hard-coding approach?
</blockquote></details>

The issue is that uniform predicting of address space layout is hard (impossible?). Just run Graphene with unlimited stack limit (on host) and see how it changes. What if somebody uses grsec or hardened-kernel (or anything like that)?
Ideally we would report to LibOS all of the address space, not just part above PAL with a bald (and wrong) assumption that nothing is there (well, we account for vdso,vvar and some other memories, but is that all there is? how one can tell?).

---


<!-- Sent from Reviewable.io -->

2021-07-30 12:47 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-MfrRaWsAHW0s_q4JvXR:bdv03w0) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The issue is that uniform predicting of address space layout is hard (impossible?). Just run Graphene with unlimited stack limit (on host) and see how it changes. What if somebody uses grsec or hardened-kernel (or anything like that)?
Ideally we would report to LibOS all of the address space, not just part above PAL with a bald (and wrong) assumption that nothing is there (well, we account for vdso,vvar and some other memories, but is that all there is? how one can tell?).
</blockquote></details>

This PR adds another hack on top of something that we should be removing, not burying deeper so it will be harder to remove when the time comes.

---


<!-- Sent from Reviewable.io -->

2021-07-30 14:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-MfrjzX8BofqxpYqvxWb:bkj9r0m) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This PR adds another hack on top of something that we should be removing, not burying deeper so it will be harder to remove when the time comes.
</blockquote></details>

Hm... I agree with this logic. Maybe there is another way of doing this, other than this hard-coding hack and the bad-for-Docker `personality()` syscall?

I was thinking about replacing `vfork + execve` with just `fork`, but mark all mmaps with `madvise(MADV_DONTFORK)` and then kinda rollback the child's state to the beginning of `pal_main()`. But this is probably very painful to do.

---


<!-- Sent from Reviewable.io -->

2021-07-30 14:24 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-MfrmV1C2hod1Gr_3v3w:b-vog5j2) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm... I agree with this logic. Maybe there is another way of doing this, other than this hard-coding hack and the bad-for-Docker `personality()` syscall?

I was thinking about replacing `vfork + execve` with just `fork`, but mark all mmaps with `madvise(MADV_DONTFORK)` and then kinda rollback the child's state to the beginning of `pal_main()`. But this is probably very painful to do.
</blockquote></details>

I don't think we have machinery to restore PAL state to the original (as for madvise - we could just `munmap(0, (size_t)PAL_START_ADDR)`, i.e. unmap everytihng).
There is also another approach proposed by @mkow: make PAL binary non-pie and pick some high base address. I dislike this approach also, as it's hard to predict what will land where, e.g, stack could be moved above PAL binary...

---


<!-- Sent from Reviewable.io -->

2021-07-30 14:27 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-MfrnhG8ANbY0uA-FTTD:b-odpfs0) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't think we have machinery to restore PAL state to the original (as for madvise - we could just `munmap(0, (size_t)PAL_START_ADDR)`, i.e. unmap everytihng).
There is also another approach proposed by @mkow: make PAL binary non-pie and pick some high base address. I dislike this approach also, as it's hard to predict what will land where, e.g, stack could be moved above PAL binary...
</blockquote></details>

Hm. Can we then try a special seccomp policy in the Docker that runs in our Jenkins CI? I hope you can just update the Docker-related configs in `.ci/` in your #2597. Maybe the `personality()` way is the best we can do after all... 

---


<!-- Sent from Reviewable.io -->

2021-07-30 14:29 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-MfroGO4DKHqVuvfCYBd:b-612fz4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm. Can we then try a special seccomp policy in the Docker that runs in our Jenkins CI? I hope you can just update the Docker-related configs in `.ci/` in your #2597. Maybe the `personality()` way is the best we can do after all... 
</blockquote></details>

That we can do, but then we would also tell users of gsc to run that seccomp profile, or not use seccomp at all.
Maybe it's time to rework this mess (initial memory mappings state) altogether?

---


<!-- Sent from Reviewable.io -->

2021-07-30 14:35 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-Mfrpo7j0v3ESSIzfMGb:b-5x6t5m) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

That we can do, but then we would also tell users of gsc to run that seccomp profile, or not use seccomp at all.
Maybe it's time to rework this mess (initial memory mappings state) altogether?
</blockquote></details>

What do you mean? Rework how?

---


<!-- Sent from Reviewable.io -->

2021-07-30 14:47 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-MfrsNQeB3oufmdQHVuy:b-krc0jd) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean? Rework how?
</blockquote></details>

Report everything that's preallocated to LibOS and let the rest of the address space be usable. The only issue I see currently is that the initial stack can be extended.

---


<!-- Sent from Reviewable.io -->

2021-07-30 15:00 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-MfrvKom0dI5ndweK90M:bc3rzl) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Report everything that's preallocated to LibOS and let the rest of the address space be usable. The only issue I see currently is that the initial stack can be extended.
</blockquote></details>

Does it solve our current problem? Linux can still put the initial PAL executable anywhere in memory of the child process, and it may overlap with whatever VMAs were on the parent process.

---


<!-- Sent from Reviewable.io -->

2021-07-30 15:05 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-MfrwHCjDV2A3KlFc-kd:b-5dvo2e) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Does it solve our current problem? Linux can still put the initial PAL executable anywhere in memory of the child process, and it may overlap with whatever VMAs were on the parent process.
</blockquote></details>

Ops, that true, I've already forgotten what was the original problem...
So there seems to be only two solutions:
1a) disable ASLR per process - requires custom docker seccomp
1b) "disable ASLR" by making PAL non-pie
2) split address space to LibOS usable and host/PAL usable
I dislike all of them :(

---


<!-- Sent from Reviewable.io -->

2021-07-30 15:19 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-MfrzkHu6ksTxEBxpp8_:b-ezpvwz) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ops, that true, I've already forgotten what was the original problem...
So there seems to be only two solutions:
1a) disable ASLR per process - requires custom docker seccomp
1b) "disable ASLR" by making PAL non-pie
2) split address space to LibOS usable and host/PAL usable
I dislike all of them :(
</blockquote></details>

Summoning @mkow and @pwmarcz for this :) We need to choose one of these...

---


<!-- Sent from Reviewable.io -->

2021-07-30 15:32 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-Mfs1QLq1a3HSCoUwTOx:b-vte4y3) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Summoning @mkow and @pwmarcz for this :) We need to choose one of these...
</blockquote></details>

I'd go with 1a or 1b, seem to a bit less hacky and brittle to me. And more deterministic.
Ad. 1a - I think we control the docker cmdline in GSC? I.e. the users already need to use our special cmdline from the docs which includes e.g. forwarding SGX devices.

---


<!-- Sent from Reviewable.io -->

2021-08-02 06:35 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-Mg4ZP-s0pgzAZ_QfnYQ:b927acr) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd go with 1a or 1b, seem to a bit less hacky and brittle to me. And more deterministic.
Ad. 1a - I think we control the docker cmdline in GSC? I.e. the users already need to use our special cmdline from the docs which includes e.g. forwarding SGX devices.
</blockquote></details>

Well, we don't *control* but we tell users the way Docker containers are started. So yes, we can add one more option to the Docker-container-run command. I guess it's fine...

---


<!-- Sent from Reviewable.io -->

2021-08-02 11:02 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-Mg5WSBL3xEY6BExIhgV:b994kvz) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, we don't *control* but we tell users the way Docker containers are started. So yes, we can add one more option to the Docker-container-run command. I guess it's fine...
</blockquote></details>

One argument for disabling ASLR in Linux PAL (i.e. both 1a and 1b): It would allow us to finally support inline syscalls outside of SGX.

---


<!-- Sent from Reviewable.io -->

2021-08-02 12:01 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-Mg5jCiH5ffwUsIIXzeT:bo6gtlf) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

One argument for disabling ASLR in Linux PAL (i.e. both 1a and 1b): It would allow us to finally support inline syscalls outside of SGX.
</blockquote></details>

@mkow I don't follow. What inline syscalls? Don't we do it already? How ASLR prevents it?

---


<!-- Sent from Reviewable.io -->

2021-08-02 12:26 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-Mg5nyj47JZ2Zcnk0-ej:b-yp6lf0) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow I don't follow. What inline syscalls? Don't we do it already? How ASLR prevents it?
</blockquote></details>

He meant inline syscalls in user app (e.g. statically compiled binary). We do not support it in non-SGX cases.
We talked about it in priv some time ago and didn't find other way than using a seccomp filer, which would allow syscalls made from PAL and generate SIGSYS on other syscalls. The only way to do this that I know of, is to check whether `rip` is in some range (in PAL). The problem is that PAL addresses change (due to ASLR), but seccomp filers pass to child processes (after fork) and you cannot remove it.

---


<!-- Sent from Reviewable.io -->

2021-08-02 12:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2595)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2595#-MfnNcBqE8z1a9J_Rgun:-Mg5pPdC8VV9x-iC2k8Z:b9wf5rw) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

He meant inline syscalls in user app (e.g. statically compiled binary). We do not support it in non-SGX cases.
We talked about it in priv some time ago and didn't find other way than using a seccomp filer, which would allow syscalls made from PAL and generate SIGSYS on other syscalls. The only way to do this that I know of, is to check whether `rip` is in some range (in PAL). The problem is that PAL addresses change (due to ASLR), but seccomp filers pass to child processes (after fork) and you cannot remove it.
</blockquote></details>

Got it. Thanks for explaining the context. Yes, would be cool to re-add the seccomp filter back to `graphene-direct`.

---


<!-- Sent from Reviewable.io -->

2021-09-24 02:24 UTC, boryspoplawski commented
Superseded by https://github.com/gramineproject/gramine/pull/89

2021-09-24 02:24 UTC, closed without merging