[Linux-SGX] Compile sgx tools with meson
gramineproject/graphene pull request #2645
Opened 2021-08-12 00:03 UTC by woju

## Description of the changes 

This is another step towards mesonification of Linux-SGX. The PAL itself still crashes, but the changes keep piling up, so maybe I can merge this undertaking in smaller chunks.

## How to test this PR? 

Jenkins

2021-08-19 20:45 UTC, woju commented
Jenkins, retest Jenkins-Debug-20.04 please (writev07)

2021-08-20 11:35 UTC, mkow requested changes
> Reviewed 3 of 61 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 3 of 61 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @pwmarcz, and @woju)

___
*[meson.build, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHCmSCwGqu7iTootw:-MhYHCmSCwGqu7iTootx:b-2j9j6d) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L30)):*
> ```Meson
> )
> 
> subdir('Scripts')
> ```

This seems to be a totally random place for this declaration, why not to move it to the other `subdir()` calls?
___
*[meson.build, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHcRl9_4cciLa50cT:-MhYHcRl9_4cciLa50cU:b-80z19o) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L59)):*
> ```Meson
>     '-Wwrite-strings',
> 
>     '-Wno-sign-compare', #TODO
> ```

TODO?
___
*[meson.build, line 101 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHtet9XFQj5pcZZE2:-MhYHtet9XFQj5pcZZE3:b447co6) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L101)):*
> ```Meson
> 
> if sgx
>     threads_dep = dependency('threads')
> ```

what's this variable? and this whole dependency?
___
*[meson.build, line 107 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHxiwA2dNnZufbxmj:-MhYHxiwA2dNnZufbxmk:bo3rad8) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L107)):*
> ```Meson
>     mbedtls_dep = mbedtls_proj.get_variable('mbedtls_dep')
>     mbedtls_install_dir = mbedtls_proj.get_variable('mbedtls_install_dir') # for install_rpath
> #   mbedtls_pal_dep = mbedtls_proj.get_variable('mbedtls_pal_dep')
> ```

why is this commented out?
___
*[meson.build, line 113 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYI9HrDKdK-2l-mgMp:-MhYI9HrDKdK-2l-mgMq:bg19bmz) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L113)):*
> ```Meson
>     cjson_dep = dependency('cjson', required: false)
>     if not cjson_dep.found()
>         # on Debian < 11 .pc is not installed and dependency() fails, so we fallback to
> ```

what's `.pc`?
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYJW5z8i6bQ2OTUe2L:-MhYJW5z8i6bQ2OTUe2M:b-uovsb4) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/Examples/ra-tls-mbedtls/server.manifest.template#L49)):*
> ```
> {%- endif %}
> ```

Nice, I didn't know this syntax with `-`!
___
*[Pal/src/host/Linux-SGX/protected-files/meson.build, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYJo3W12OSVN5Qvcxn:-MhYJo3W12OSVN5Qvcxo:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/Pal/src/host/Linux-SGX/protected-files/meson.build#L13)):*
> ```Meson
> 
>     compile_args: [
>         '-Wno-null-dereference', # TODO fails on 18.04 in lru_cache.c
> ```

ditto
___
*[subprojects/packagefiles/mbedtls/compile.sh, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYKE148_KH1aNjA43N:-MhYKE148_KH1aNjA43O:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/subprojects/packagefiles/mbedtls/compile.sh#L3)):*
> ```Shell
> #!/bin/sh
> 
> # TODO Debug/Release
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-08-20 12:24 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 3 of 75 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[meson.build, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHCmSCwGqu7iTootw:-MhYNNMj795nnOkkRw5g:b-yhmmg2) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This seems to be a totally random place for this declaration, why not to move it to the other `subdir()` calls?
</blockquote></details>

Because next one in series has python3_platlib definition here, together with other paths, and that requires find_program which is run in Scripts.
___
*[meson.build, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHcRl9_4cciLa50cT:-MhYOE1u1bGafvKWcJus:b1y02di) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

TODO?
</blockquote></details>

If you comment this, there are compilation `-Werror`s.
___
*[meson.build, line 101 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHtet9XFQj5pcZZE2:-MhYOgcp9PPw-iEupza9:b1sdooa) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L101)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

what's this variable? and this whole dependency?
</blockquote></details>

This is `-lpthreads`, used in `libsecret_prov_verify_{epid,dcap}.so`. https://mesonbuild.com/Threads.html
___
*[meson.build, line 107 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHxiwA2dNnZufbxmj:-MhYOc5z45AruOEh9iNu:bmbkt7d) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L107)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

why is this commented out?
</blockquote></details>

Will be used in next PR in series.
___
*[meson.build, line 113 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYI9HrDKdK-2l-mgMp:-MhYP4zb3SkLpQ3OpAyI:b-vcezwp) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L113)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

what's `.pc`?
</blockquote></details>

An extension to a file read by `pkg-config`, which is a distro-neutral tool for discovering compilation flags for dependencies. Usually this is used in makefiles like this:

```make
program: program.c
    $(CC) -o $@ $< $(shell pkg-config --cflags --libs library)
```

And `-I`, `-L`, `-l`, `-Wl,-rpath` etc. are on the stdout from pkg-config, you don't have to bother, this is done for you by packager who should supply the respective `.pc` file. (I seriously consider doing just that for our patched mbedtls, but rather not now).

So meson has this `dependency()` discovery thingy which uses three different distro-neutral standards for searching for already installed libraries. But on old distros this file is missing and discovery fails. So we resort to `cc.find_library()` which just checks if dummy file compiles with `-l<whatever>`.

`man pkg-config` for details.
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYJW5z8i6bQ2OTUe2L:-MhYRuw4AyDDC51CVAS3:b-b2qqoi) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/Examples/ra-tls-mbedtls/server.manifest.template#L49)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> {%- endif %}
> ```

Nice, I didn't know this syntax with `-`!
</blockquote></details>

Yep, it works also with `{{` and `{#`.
___
*[Pal/src/host/Linux-SGX/protected-files/meson.build, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYJo3W12OSVN5Qvcxn:-MhYS3rj9pY2yY2eSaFC:b-z3dhv1) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/Pal/src/host/Linux-SGX/protected-files/meson.build#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Plz comment and see for yourself.

And for the record, that's why I pasted gcc errors in commit messages in previous PR.
___
*[subprojects/packagefiles/mbedtls/compile.sh, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYKE148_KH1aNjA43N:-MhYV2544vTDafj7qFCq:bbt45mb) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/subprojects/packagefiles/mbedtls/compile.sh#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

This was leftover from rewriting what's being done in `common/src/Makefile` (MBED_BUILD_TYPE). But ISTM that there is no such variable, so we can drop this altogether.


<!-- Sent from Reviewable.io -->

2021-08-20 12:49 UTC, pwmarcz requested changes
> Reviewed 61 of 61 files at r1, 14 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 74 of 75 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXku6M2_eUhsPTm2bd:-MhXku6M2_eUhsPTm2be:bs2cdvm) (no related file):*
Meson on Ubuntu 18.04 fails to build, and apparently leaves the working directory in a broken state:

```
$ meson --version
0.45.1
$ meson build-sgx -Dsgx=enabled -Dprefix=$PWD/.local
...
Executing subproject mbedtls-mbedtls-2.26.0.
meson.build:104:4: ERROR: Missing Meson file in /home/pawel/graphene/subprojects/mbedtls-mbedtls-2.26.0/meson.build
$ meson build-sgx -Dsgx=enabled -Dprefix=$PWD/.local
...
meson.build:104:4: ERROR: Subproject directory 'subprojects/mbedtls-mbedtls-2.26.0' does not exist and cannot be downloaded:
'subprojects/mbedtls-mbedtls-2.26.0' is not empty and has no meson.build files
```

Installing meson 0.55 via pip worked (but I had to manually clean the `subprojects/`) dir.

So: if meson 0.45 no longer works, maybe `building.rst` should mention a specific version?

I also found this:

```
WARNING: Project targeting '>=0.45' but tried to use feature introduced in '0.49.0': / with string arguments.
```

So it looks like the version in the project also needs bumping.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYVhCKDIMPIRUe0Oo5:-MhYVhCL5N1VSEGmDkmE:bdkcsv3) (no related file):*
More warnings from meson:

```
WARNING: custom_target 'mbedtls' has more than one output! Using the first one.
WARNING: custom_target 'mbedtls' has more than one output! Using the first one.
WARNING: custom_target 'mbedtls_pal' has more than one output! Using the first one.
WARNING: custom_target 'mbedtls_pal' has more than one output! Using the first one.
```

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYVu5IDdrhGt9mqTtC:-MhYVu5IDdrhGt9mqTtD:bm4zics) (no related file):*
With `SGX=1 DEBUG=1`, `ninja` fails the linking stage due to `undefined reference to `_log'`. This is again the one configuration that we don't have on Jenkins (but let's not break it!)

 It looks like the tools should define it (probably as a wrapper over `vprintf` - see `Pal/regression/utils.c` for a similar situation).

---
___
*[meson.build, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHcRl9_4cciLa50cT:-MhYXqiq1PXi_kGlSRK9:b-i7ma8h) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L59)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If you comment this, there are compilation `-Werror`s.
</blockquote></details>

Suggested fix:

```diff
diff --git a/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c b/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c
index 3d5fbc80..cc2f7fce 100644
--- a/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c
+++ b/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c
@@ -47,7 +47,7 @@ static void usage(void) {
     exit(-1); \
 } while (0)
 
-ssize_t g_input_size = 0;
+size_t g_input_size = 0;
 char* g_input_name = NULL;
 void* g_input_data = MAP_FAILED;
 char* g_output_dir = NULL;
@@ -447,11 +447,12 @@ int main(int argc, char* argv[]) {
         goto out;
     }
 
-    g_input_size = get_file_size(input_fd);
-    if (g_input_size < 0) {
+    ssize_t input_size = get_file_size(input_fd);
+    if (input_size < 0) {
         ERROR("Failed to stat input file '%s': %s\n", input_path, strerror(errno));
         goto out;
     }
+    g_input_size = input_size;
 
     g_input_data = mmap(NULL, g_input_size, PROT_READ, MAP_PRIVATE, input_fd, 0);
     if (g_input_data == MAP_FAILED) {
diff --git a/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c b/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c
index 659c98d3..b3254362 100644
--- a/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c
+++ b/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c
@@ -335,7 +335,7 @@ __attribute__((constructor)) static void secret_provision_constructor(void) {
             if (fd < 0)
                 return;
 
-            ssize_t total_written = 0;
+            size_t total_written = 0;
             while (total_written < secret_len) {
                 ssize_t written = write(fd, secret + total_written, secret_len - total_written);
                 if (written > 0) {
```
___
*[.ci/ubuntu18.04.dockerfile, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXeje55GXozYl08ykg:-MhXeje55GXozYl08ykh:b-szcsi7) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/ubuntu18.04.dockerfile#L73)):*
> ```Dockerfile
>     sphinx_rtd_theme \
>     'toml>=0.10' \
>     'meson<0.56'
> ```

Is 0.56 incompatible? If so, maybe you can leave a comment why (and when/how the incompatibility can be resolved).

Also, wouldn't it be better to pin the exact version? We're probably not compatible with *any* version before 0.56.
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhInK6NXsgplPO3Xi:-MhXhInK6NXsgplPO3Xj:b-ljkucn) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L42)):*
> ```
>     }
> 
>     libdir = sh(returnStdout: true, script: '''
> ```

Looking at this line, I've no idea what the path is supposed to be. 

Does it differ between builds? Can we just hardcode it here? If not, then maybe add a comment what we expect it to be for current configurations?
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhHdg4q0KoJyuF4jn:-MhXhHdg4q0KoJyuF4jo:b-oss54p) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L48)):*
> ```
> 
>     env.GRAPHENE_PKGLIBDIR = libdir + '/graphene'
>     env.LD_LIBRARY_PATH = libdir
> ```

What's the `LD_LIBRARY_PATH` override for? It seems weird to set it globally, it will affect all programs executed in the Jenkins build.

Also, I see that it influences the manifest for some examples, even outside of Jenkins. That looks like a footgun: I wouldn't expect an environment variable for *runtime* linking to change how software is built.
___
*[Pal/src/host/Linux-SGX/protected-files/meson.build, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYJo3W12OSVN5Qvcxn:-MhY_1AS2zlHf8E1_hno:bxmnigb) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/Pal/src/host/Linux-SGX/protected-files/meson.build#L13)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Plz comment and see for yourself.

And for the record, that's why I pasted gcc errors in commit messages in previous PR.
</blockquote></details>

Proposed fix (kind of quick-and-dirty, maybe someone will have a better idea):

```diff
--- a/Pal/src/host/Linux-SGX/protected-files/lru_cache.c
+++ b/Pal/src/host/Linux-SGX/protected-files/lru_cache.c
@@ -138,7 +138,7 @@ void* lruc_get_first(lruc_context_t* lruc) {
     lruc->current = LISTP_FIRST_ENTRY(&lruc->list, /*unused*/ 0, list);
     lruc_map_node_t* mn = get_map_node(lruc, lruc->current->key);
     assert(mn != NULL);
-    return mn->data;
+    return mn ? mn->data : NULL;
 }
 
 void* lruc_get_next(lruc_context_t* lruc) {
@@ -151,7 +151,7 @@ void* lruc_get_next(lruc_context_t* lruc) {
 
     lruc_map_node_t* mn = get_map_node(lruc, lruc->current->key);
     assert(mn != NULL);
-    return mn->data;
+    return mn ? mn->data : NULL;
 }
 
 void* lruc_get_last(lru [...]

2021-08-20 15:36 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 74 of 75 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXku6M2_eUhsPTm2bd:-MhYdCEYBzWcxZdKJ6wp:bh7heik) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Meson on Ubuntu 18.04 fails to build, and apparently leaves the working directory in a broken state:

```
$ meson --version
0.45.1
$ meson build-sgx -Dsgx=enabled -Dprefix=$PWD/.local
...
Executing subproject mbedtls-mbedtls-2.26.0.
meson.build:104:4: ERROR: Missing Meson file in /home/pawel/graphene/subprojects/mbedtls-mbedtls-2.26.0/meson.build
$ meson build-sgx -Dsgx=enabled -Dprefix=$PWD/.local
...
meson.build:104:4: ERROR: Subproject directory 'subprojects/mbedtls-mbedtls-2.26.0' does not exist and cannot be downloaded:
'subprojects/mbedtls-mbedtls-2.26.0' is not empty and has no meson.build files
```

Installing meson 0.55 via pip worked (but I had to manually clean the `subprojects/`) dir.

So: if meson 0.45 no longer works, maybe `building.rst` should mention a specific version?

I also found this:

```
WARNING: Project targeting '>=0.45' but tried to use feature introduced in '0.49.0': / with string arguments.
```

So it looks like the version in the project also needs bumping.
</blockquote></details>

This would work fine if you used `meson dist` on meson 0.55, which produces tarball with subprojects already fetched. Then you can unpack this tarball and run `meson setup`. (This will be intended method of source distribution for packaging, once everything important will be mesonified.) To execute `meson setup` without subprojects fetched, you need meson >= 0.55, because `packagefiles=`in wraps is supported since then, and without that we'd have to either maintain forks or make available tarballs(!) with overlays.

Or yolo, scrap all that and let's say you need meson >= 0.55, and users on 18.04 can download meson from unsigned pip.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYVhCKDIMPIRUe0Oo5:-MhYf1ri22b0So1kW3wu:b-gk8j1s) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

More warnings from meson:

```
WARNING: custom_target 'mbedtls' has more than one output! Using the first one.
WARNING: custom_target 'mbedtls' has more than one output! Using the first one.
WARNING: custom_target 'mbedtls_pal' has more than one output! Using the first one.
WARNING: custom_target 'mbedtls_pal' has more than one output! Using the first one.
```
</blockquote></details>

Oops, this is worrying. On which meson version this was captured? This might actually mean that we'll have to bump minimal meson version.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYVu5IDdrhGt9mqTtC:-MhZBIGO-LK-OFuz6KvX:btq92p) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

With `SGX=1 DEBUG=1`, `ninja` fails the linking stage due to `undefined reference to `_log'`. This is again the one configuration that we don't have on Jenkins (but let's not break it!)

 It looks like the tools should define it (probably as a wrapper over `vprintf` - see `Pal/regression/utils.c` for a similar situation).
</blockquote></details>

Isn't this acutally broken by #2631?

---
___
*[meson.build, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHcRl9_4cciLa50cT:-MhZ974UDxrZbfTxz_ey:bnxs5cm) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L59)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Suggested fix:

```diff
diff --git a/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c b/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c
index 3d5fbc80..cc2f7fce 100644
--- a/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c
+++ b/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c
@@ -47,7 +47,7 @@ static void usage(void) {
     exit(-1); \
 } while (0)
 
-ssize_t g_input_size = 0;
+size_t g_input_size = 0;
 char* g_input_name = NULL;
 void* g_input_data = MAP_FAILED;
 char* g_output_dir = NULL;
@@ -447,11 +447,12 @@ int main(int argc, char* argv[]) {
         goto out;
     }
 
-    g_input_size = get_file_size(input_fd);
-    if (g_input_size < 0) {
+    ssize_t input_size = get_file_size(input_fd);
+    if (input_size < 0) {
         ERROR("Failed to stat input file '%s': %s\n", input_path, strerror(errno));
         goto out;
     }
+    g_input_size = input_size;
 
     g_input_data = mmap(NULL, g_input_size, PROT_READ, MAP_PRIVATE, input_fd, 0);
     if (g_input_data == MAP_FAILED) {
diff --git a/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c b/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c
index 659c98d3..b3254362 100644
--- a/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c
+++ b/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c
@@ -335,7 +335,7 @@ __attribute__((constructor)) static void secret_provision_constructor(void) {
             if (fd < 0)
                 return;
 
-            ssize_t total_written = 0;
+            size_t total_written = 0;
             while (total_written < secret_len) {
                 ssize_t written = write(fd, secret + total_written, secret_len - total_written);
                 if (written > 0) {
```
</blockquote></details>

Done. I committed with your `--author`ship.
___
*[.ci/ubuntu18.04.dockerfile, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXeje55GXozYl08ykg:-MhYfZgV1T_izzepKA4A:b-hsn3xz) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/ubuntu18.04.dockerfile#L73)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Is 0.56 incompatible? If so, maybe you can leave a comment why (and when/how the incompatibility can be resolved).

Also, wouldn't it be better to pin the exact version? We're probably not compatible with *any* version before 0.56.
</blockquote></details>

No, we're compatible with any version since `0.55.0`. So I wanted to install the oldest supported plus bugfixes (0.55.y), so the last one before 0.56. Which is exactly what this states.
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhInK6NXsgplPO3Xi:-MhYg0Jo2AqtN_qE1nYx:b-joplbg) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L42)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Looking at this line, I've no idea what the path is supposed to be. 

Does it differ between builds? Can we just hardcode it here? If not, then maybe add a comment what we expect it to be for current configurations?
</blockquote></details>

This is `'/'.join()`ed `--prefix` to `--libdir` (meson options, as configured in `build/`). Yes, they differ, because there's `$WORKSPACE` inside `--prefix`. `--libdir` differs between distro families, so for now it's the same in all ubuntus, but will be different on rhel/fedora.

Would you like a comment here?
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhHdg4q0KoJyuF4jn:-MhYgid63PZnYxh8HpBW:b-mnat3l) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L48)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

What's the `LD_LIBRARY_PATH [...]

2021-08-20 15:42 UTC, woju commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXku6M2_eUhsPTm2bd:-MhZCt339FXhUCbmIpNQ:b-nmgqls) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This would work fine if you used `meson dist` on meson 0.55, which produces tarball with subprojects already fetched. Then you can unpack this tarball and run `meson setup`. (This will be intended method of source distribution for packaging, once everything important will be mesonified.) To execute `meson setup` without subprojects fetched, you need meson >= 0.55, because `packagefiles=`in wraps is supported since then, and without that we'd have to either maintain forks or make available tarballs(!) with overlays.

Or yolo, scrap all that and let's say you need meson >= 0.55, and users on 18.04 can download meson from unsigned pip.
</blockquote></details>

I mean, `patch_directory =`. Aaand I fixed `/` problem in my tree, will push with next batch.

---


<!-- Sent from Reviewable.io -->

2021-08-20 15:50 UTC, boryspoplawski requested changes
> Reviewed 60 of 61 files at r1, 15 of 15 files at r2, 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 70 of 76 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[meson.build, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHcRl9_4cciLa50cT:-MhYsTIDAPmMflr9lwBd:bwzc6b7) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L59)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Suggested fix:

```diff
diff --git a/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c b/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c
index 3d5fbc80..cc2f7fce 100644
--- a/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c
+++ b/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c
@@ -47,7 +47,7 @@ static void usage(void) {
     exit(-1); \
 } while (0)
 
-ssize_t g_input_size = 0;
+size_t g_input_size = 0;
 char* g_input_name = NULL;
 void* g_input_data = MAP_FAILED;
 char* g_output_dir = NULL;
@@ -447,11 +447,12 @@ int main(int argc, char* argv[]) {
         goto out;
     }
 
-    g_input_size = get_file_size(input_fd);
-    if (g_input_size < 0) {
+    ssize_t input_size = get_file_size(input_fd);
+    if (input_size < 0) {
         ERROR("Failed to stat input file '%s': %s\n", input_path, strerror(errno));
         goto out;
     }
+    g_input_size = input_size;
 
     g_input_data = mmap(NULL, g_input_size, PROT_READ, MAP_PRIVATE, input_fd, 0);
     if (g_input_data == MAP_FAILED) {
diff --git a/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c b/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c
index 659c98d3..b3254362 100644
--- a/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c
+++ b/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c
@@ -335,7 +335,7 @@ __attribute__((constructor)) static void secret_provision_constructor(void) {
             if (fd < 0)
                 return;
 
-            ssize_t total_written = 0;
+            size_t total_written = 0;
             while (total_written < secret_len) {
                 ssize_t written = write(fd, secret + total_written, secret_len - total_written);
                 if (written > 0) {
```
</blockquote></details>

+1 to @pwmarcz fix
___
*[meson.build, line 107 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHxiwA2dNnZufbxmj:-MhYsq53CJcchOAgZIWV:b-qtlg1f) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L107)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Will be used in next PR in series.
</blockquote></details>

Then why you add it here not in next PR?
___
*[.ci/ubuntu18.04.dockerfile, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXeje55GXozYl08ykg:-MhYuIVy4nceXBBJIVE9:bjmr1ra) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/ubuntu18.04.dockerfile#L73)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Is 0.56 incompatible? If so, maybe you can leave a comment why (and when/how the incompatibility can be resolved).

Also, wouldn't it be better to pin the exact version? We're probably not compatible with *any* version before 0.56.
</blockquote></details>

Actually, this install any **lower** version. This definitely deserves a comment (atm I have no idea why this is done).
Also do we really want to install ninja from apt and meson from pip? Should users do the same? How can they know that?
___
*[.ci/ubuntu20.04.dockerfile, line 73 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYvERq1TmCVaCh-XxS:-MhYvERq1TmCVaCh-XxT:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/ubuntu20.04.dockerfile#L73)):*
> ```Dockerfile
> RUN python3 -m pip install -U \
>     asv \
>     'meson<0.56'
> ```

ditto
___
*[.ci/lib/stage-build-nosgx.jenkinsfile, line 28 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYvUP6-tDv5hOUoS1f:-MhYvUP6-tDv5hOUoS1g:b-xqs7ln) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-build-nosgx.jenkinsfile#L28)):*
> ```
> 
>     env.GRAPHENE_PKGLIBDIR = libdir + '/graphene'
>     env.LD_LIBRARY_PATH = libdir
> ```

This looks super fishy. Why you need to do this?
___
*[.ci/lib/stage-build-nosgx.jenkinsfile, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYvnAnCfbw1KhtfnhB:-MhYvnAo5CHjpTqhwhA1:brjorc8) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-build-nosgx.jenkinsfile#L32)):*
> ```
> 
>     sh 'rm -rf build'
>     sh 'git clean -Xf subprojects'
> ```

Why? Who have built it before? Why can't we reuse that build?
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhHdg4q0KoJyuF4jn:-MhYwEDF6yEkfEjORrRL:b32v57) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L48)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

What's the `LD_LIBRARY_PATH` override for? It seems weird to set it globally, it will affect all programs executed in the Jenkins build.

Also, I see that it influences the manifest for some examples, even outside of Jenkins. That looks like a footgun: I wouldn't expect an environment variable for *runtime* linking to change how software is built.
</blockquote></details>

+1
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 43 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYwIYo4hIFP5rT_v3g:-MhYwIYo4hIFP5rT_v3h:b1etsza) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-build-sgx.jenkinsfile#L43)):*
> ```
> 
>     libdir = sh(returnStdout: true, script: '''
>         meson introspect build/ --buildoptions \
> ```

Hmm, doesn't this mean that `build/` directory is hardcoded? What if I use a different one?
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 52 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYwHZi8PKvJy1nVFaC:-MhYwHZi8PKvJy1nVFaD:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-build-sgx.jenkinsfile#L52)):*
> ```
> 
>     sh 'rm -rf build'
>     sh 'git clean -Xf subprojects'
> ```

ditto
___
*[.ci/lib/stage-clean-check.jenkinsfile, line 43 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYwadH2UF-lwgKEw3t:-MhYwadH2UF-lwgKEw3u:b-s9x4yr) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-clean-check.jenkinsfile#L43)):*
> ```
>         rm -rf python/graphenelibos/__pycache__
> 
>         # on bionic, git clean -Xf fails
> ```

`Ubuntu Bionic`?
___
*[common/src/string/ctype.c, line 10 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYymby4AsP4rKQLeJP:-MhYymby4AsP4rKQLeJQ:b-vohobb) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/common/src/string/ctype.c#L10)):*
> ```C
> }
> 
> int isupper(int c) {
> ```

Hmm, why is this included in the diff?

Update: ok, you've force-pushed the `into` merge branch, so the commits changed. Please do not force push...
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYzXMn0yDc2E0y2suw:-MhYzXMn0yDc2E0y2sux:b-1srmuw) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/Examples/ra-tls-mbedtls/client.manifest [...]

2021-08-20 15:58 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r3, 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 40 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhHdg4q0KoJyuF4jn:-MhZGuElEON0_Ue5ymLY:bfehvhv) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L48)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

No, we cannot override `LD_LIBRARY_PATH` globally (for the whole build/link stage). Something will break someday.


<!-- Sent from Reviewable.io -->

2021-08-20 17:20 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 68 of 76 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYVhCKDIMPIRUe0Oo5:-MhZHnLj6TrD-sag3A38:b-8ddasl) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Oops, this is worrying. On which meson version this was captured? This might actually mean that we'll have to bump minimal meson version.
</blockquote></details>

I can't find the version in changelog when this was fixed. However I found another problem, `link_with: custom_target()` is supported since 0.51.0, so this is it. Without this option, building mbedtls would be much more complicated.

---
___
*[meson.build, line 107 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHxiwA2dNnZufbxmj:-MhZV4Zi1HePZ3h_zWky:b-gvg7vf) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L107)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then why you add it here not in next PR?
</blockquote></details>

That would be a conflict when rebasing, but sure, why not.
___
*[.ci/ubuntu18.04.dockerfile, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXeje55GXozYl08ykg:-MhZITkT1gsXSsPKGEGj:b-fbkq7l) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/ubuntu18.04.dockerfile#L73)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, this install any **lower** version. This definitely deserves a comment (atm I have no idea why this is done).
Also do we really want to install ninja from apt and meson from pip? Should users do the same? How can they know that?
</blockquote></details>

pip implicitly installs latest available version satisfying the constraint. I do it this way, because meson is actively developed and distros have older versions. So I want to install as old version as I can get away with.

We want people to install both meson and ninja from apt (`apt install meson`, and ninja pulled by dependency), but until we can do that (Ubuntu >= 20.10, so no LTS; Debian 11 or Debian 10 + backports; not available in RHEL, not even in EPEL), we should install meson from pip. Ninja is written in C++, so it's easier to tell people to install from repo, and also it's not the only backend supported by meson, theoretically you can also use visual studio and xcode projects.
___
*[.ci/ubuntu20.04.dockerfile, line 73 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYvERq1TmCVaCh-XxS:-MhZKbI8C6ZIq3okqYxn:b2ni7t9) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/ubuntu20.04.dockerfile#L73)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

mhm
___
*[.ci/lib/stage-build-nosgx.jenkinsfile, line 28 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYvUP6-tDv5hOUoS1f:-MhZVL014wyA48JROc7L:ben38ma) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-build-nosgx.jenkinsfile#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This looks super fishy. Why you need to do this?
</blockquote></details>

For the same reason as in `stage-build-sgx.jenkinsfile`.
___
*[.ci/lib/stage-build-nosgx.jenkinsfile, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYvnAnCfbw1KhtfnhB:-MhZKiPN5_uMswNx_wE2:bbcbsqq) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-build-nosgx.jenkinsfile#L32)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why? Who have built it before? Why can't we reuse that build?
</blockquote></details>

`subprojects/` were downloaded and overlaid by `meson setup`. This is done to avoid cheating, for example linking against objects in `build/` or relying on sources being present or the directory named "build". Actually both of those should have been under the comment below.

In this project there's much precedent for such unholy things, from detecting architecture by executing gcc, to gratuitous copying whatever was conventient to tests and/or Examples. If we need after build, it should be installed.
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhHdg4q0KoJyuF4jn:-MhZQ5am1TqZk6QGWT5T:b-k1ueq5) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L48)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, we cannot override `LD_LIBRARY_PATH` globally (for the whole build/link stage). Something will break someday.
</blockquote></details>

This is done after building and linking. Only tests and Examples are affected. Also, this is perfectly safe as long as you point to the directory that on normal install will be in a place normally frequented by `ld.so`.
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 43 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYwIYo4hIFP5rT_v3g:-MhZVWTf6GDpS2dMIk8X:bgfrrl7) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-build-sgx.jenkinsfile#L43)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, doesn't this mean that `build/` directory is hardcoded? What if I use a different one?
</blockquote></details>

It's hardcoded in jenkins, and it doesn't leave this file. In your own environment you can rename that directory to your heart's content. And this is only needed to query for `--prefix` and `--libdir`, in real life (in deb) this is `'/usr'` and `'lib/x86_64-linux-gnu'` respectively (but not here).
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 52 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYwHZi8PKvJy1nVFaC:-MhZQbhJ2dsQ13pPE0qw:b2ni7t9) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-build-sgx.jenkinsfile#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

mhm
___
*[.ci/lib/stage-clean-check.jenkinsfile, line 43 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYwadH2UF-lwgKEw3t:-MhZQg7--JYJdNVr9tRv:b-qkk8g3) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-clean-check.jenkinsfile#L43)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`Ubuntu Bionic`?
</blockquote></details>

No, lowercase `bionic`. Yes, this refers to "Ubuntu 18.04LTS".
___
*[common/src/string/ctype.c, line 10 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYymby4AsP4rKQLeJP:-MhZQw8_1o-dOUT-2i9b:be0ncro) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/common/src/string/ctype.c#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, why is this included in the diff?

Update: ok, you've force-pushed the `into` merge branch, so the commits changed. Please do not force push...
</blockquote></details>

This was done by pushing to #2631. Looks like reviewable has problems with stacked PRs.
___
*[Examples/ra-tls-mbedtls/client.manife [...]

2021-08-20 18:57 UTC, pwmarcz requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 68 of 76 files reviewed, 38 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYVu5IDdrhGt9mqTtC:-MhZeQZADuB9nP3vxCbu:bffdekk) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Isn't this acutally broken by #2631?
</blockquote></details>

Kind of: #2631 introduces problems with definitions (`pid_t` etc.) I fixed them before trying to compile this branch (with the change I mentioned in #2631) and I still get the linking issue. It looks unrelated.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYVhCKDIMPIRUe0Oo5:-MhZrGWm-TrIiVt5TjU9:btz7p7b) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I can't find the version in changelog when this was fixed. However I found another problem, `link_with: custom_target()` is supported since 0.51.0, so this is it. Without this option, building mbedtls would be much more complicated.
</blockquote></details>

Meson 0.55, installed from pip on Ubuntu 18.04.

---
___
*[.ci/ubuntu18.04.dockerfile, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXeje55GXozYl08ykg:-MhZfbUz85Q-rI1qVkHf:b-sevfm) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/ubuntu18.04.dockerfile#L73)):*
>No, we're compatible with any version since 0.55.0. So I wanted to install the oldest supported plus bugfixes (0.55.y), so the last one before 0.56. Which is exactly what this states.

No, this says to install any version lower than 0.56, and (as you say) the assumption that pip will do the right thing is implicit. It works only because 0.55 is available on PyPI, *and* we haven't installed earlier version before, *and* we're not installing a conflicting package at the same time, *and* nobody refactored this not knowing that the implicit behavior is actually important.

I agree with the decision to use `0.55.y`, but please use `meson>=0.55,<0.56` to make that intention clear (and so that pip fails loudly if something goes wrong).
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhInK6NXsgplPO3Xi:-MhZiMXi2Om1p4R81tdC:b-5n2fde) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L42)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is `'/'.join()`ed `--prefix` to `--libdir` (meson options, as configured in `build/`). Yes, they differ, because there's `$WORKSPACE` inside `--prefix`. `--libdir` differs between distro families, so for now it's the same in all ubuntus, but will be different on rhel/fedora.

Would you like a comment here?
</blockquote></details>

So what is it in our Jenkins setup? `/lib/x86_64-linux-gnu/`? `/usr/lib/x86_64-linux-gnu`?

If I understand this correctly, it would be nice to say something like:

```
# Target library path, as configured by Meson. (for our current builds, that should be `/lib/x86_64-linux-gnu/`)
```
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhHdg4q0KoJyuF4jn:-MhZk-v27QGVJxvPEPut:beh5ixq) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L48)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is done after building and linking. Only tests and Examples are affected. Also, this is perfectly safe as long as you point to the directory that on normal install will be in a place normally frequented by `ld.so`.
</blockquote></details>

I'm still confused. Is `libdir` in our Jenkins setup some non-standard path?

As a Graphene user, am I expected to override `LD_LIBRARY_PATH`? Am I expected to override it *before building the example*? Should this be documented?

(I still think `LD_LIBRARY_PATH` influencing *how the example is built* is a bad idea. This variable is for controlling `ld.so`, not Graphene build script).
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYzXMn0yDc2E0y2suw:-MhZsaVDEQ56N-3LHjt_:bw9uovl) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/Examples/ra-tls-mbedtls/client.manifest.template#L7)):*
>No, you need this anyway (probably in every single enclave that runs dynamically linked binaries) if LD_LIBRARY_PATH is to be working as documented.

Wait, why? If for some reason I override `LD_LIBRARY_PATH` in my host system, I definitely wouldn't expect this to be passed down to software running in Graphene (which by definition is a controlled environment), much less influence what is _mounted_ there. If I change`LD_LIBRARY_PATH`, I expect it to control the behavior of ld.so, not some random other pieces of software.
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 49 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYzhS09ryJo1Mk-GRz:-MhZsmXq9F02AKU8C_eB:b-oosbc9) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/Examples/ra-tls-mbedtls/client.manifest.template#L49)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

`LD_LIBRARY_PATH` is a list, this will break as soon as it contains more than one path.
___
*[Pal/src/host/Linux-SGX/tools/ias-request/ias_request.c, line 149 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXjdJI9t9o3ty6XHXC:-MhZpntS8O3Dl-9wKz5a:barcqaq) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/Pal/src/host/Linux-SGX/tools/ias-request/ias_request.c#L149)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

IDK. Do you want an error message? xD
</blockquote></details>

Ouch, I didn't know casting a string literal to `char*` was legal.

I haven't checked the message but `gcc -Wwrite-strings` seems to have that effect, so that's probably it?


<!-- Sent from Reviewable.io -->

2021-08-20 22:01 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 68 of 76 files reviewed, 38 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[.ci/ubuntu18.04.dockerfile, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXeje55GXozYl08ykg:-Mh_LgFqDmfO765kYgIw:bctpdcc) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/ubuntu18.04.dockerfile#L73)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>No, we're compatible with any version since 0.55.0. So I wanted to install the oldest supported plus bugfixes (0.55.y), so the last one before 0.56. Which is exactly what this states.

No, this says to install any version lower than 0.56, and (as you say) the assumption that pip will do the right thing is implicit. It works only because 0.55 is available on PyPI, *and* we haven't installed earlier version before, *and* we're not installing a conflicting package at the same time, *and* nobody refactored this not knowing that the implicit behavior is actually important.

I agree with the decision to use `0.55.y`, but please use `meson>=0.55,<0.56` to make that intention clear (and so that pip fails loudly if something goes wrong).
</blockquote></details>

Makes sense. Done.
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhInK6NXsgplPO3Xi:-Mh_LnPE-FXjHGoBcuL1:b-7g1oq4) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L42)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

So what is it in our Jenkins setup? `/lib/x86_64-linux-gnu/`? `/usr/lib/x86_64-linux-gnu`?

If I understand this correctly, it would be nice to say something like:

```
# Target library path, as configured by Meson. (for our current builds, that should be `/lib/x86_64-linux-gnu/`)
```
</blockquote></details>

`$WORKSPACE/usr/lib/x86_64-linux-gnu` most likely, so `/home/jenkins/$JOBNAME/usr/lib/x86_64-linux-gnu`. "x86_64-linux-gnu" is default on debian-like, so will change on RHEL/CentOS/AlmaLinux.
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhHdg4q0KoJyuF4jn:-Mh_OrVb8KDc-fR3wM5M:bk3dxgl) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L48)):*
> I'm still confused. Is libdir in our Jenkins setup some non-standard path?

Meson option `--libdir` is standard (see it's not even specified), but it's relative, specificaly relative to `--prefix` and prefix is non-standard, so the end result (groovy variable `libdir`) also points to something arbitrary.

> As a Graphene user, am I expected to override LD_LIBRARY_PATH? Am I expected to override it before building the example? Should this be documented?

Depends on how you configure/build/install graphene. If from deb or you use `--prefix=/usr` or `--prefix=/usr/local` (last one is the default), you don't need to, so it's not documented. But while building the enclave (cc-ing the binary and rendering manifest) you can, it's your decision (esp. if you have some libraries installed in non-standard places like `/opt`).

If you configure with weird `--prefix` (or friends like `--bindir`, `--libdir` etc.), you're on your own like with every self-compiled software and you need to override some subset of `$PATH`,  `$LD_LIBRARY_PATH`, `$LIBRARY_PATH`, `$PYTHONPATH` and in the near future maybe also `$MANPATH` if we want to compile them with meson (I doubt this one). Or possibly edit `/etc/ld.so.conf` and other conf files, and remember to also adjust the manifest.

In short, it behaves exactly like with other projects. It's documented in respective manpages of each piece of software that uses it's own `$WHATEVERPATH`.

> (I still think LD_LIBRARY_PATH influencing how the example is built is a bad idea. This variable is for controlling ld.so, not Graphene build script).

It's the decision of whoever builds the enclave. We shouldn't forbid using this variable if developers so desire. But because we gate the access to filesystem and environment variables, if the entrypoint was built with `LIBRARY_PATH` set, we need to adjust manifest, right? Specifically 1) `LD_LIBRARY_PATH` needs to be forwarded, 2) libraries under this path need to be measured. So that's what happens.
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYzXMn0yDc2E0y2suw:-Mh_TID646qwE-v_BM53:b-4nd6hg) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/Examples/ra-tls-mbedtls/client.manifest.template#L7)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>No, you need this anyway (probably in every single enclave that runs dynamically linked binaries) if LD_LIBRARY_PATH is to be working as documented.

Wait, why? If for some reason I override `LD_LIBRARY_PATH` in my host system, I definitely wouldn't expect this to be passed down to software running in Graphene (which by definition is a controlled environment), much less influence what is _mounted_ there. If I change`LD_LIBRARY_PATH`, I expect it to control the behavior of ld.so, not some random other pieces of software.
</blockquote></details>

1) Yes, no surprises, it was explicitly stated in manifest. 2) If you've had overridden it, it was there when you were compiling entrypoint, so if you linked against some library from there, now it's too late, you either pass it through manifest, or dynamic loading of entrypoint fails.
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 49 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYzhS09ryJo1Mk-GRz:-Mh_UClc1NwxdkqSwkZR:b9mx6le) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/Examples/ra-tls-mbedtls/client.manifest.template#L49)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`LD_LIBRARY_PATH` is a list, this will break as soon as it contains more than one path.
</blockquote></details>

Oh. Right.


<!-- Sent from Reviewable.io -->

2021-08-20 22:53 UTC, boryspoplawski requested changes
> Reviewed 3 of 8 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[meson.build, line 107 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHxiwA2dNnZufbxmj:-Mh_aXjRAgSzhSu3nlpC:bq5wmbv) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L107)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

That would be a conflict when rebasing, but sure, why not.
</blockquote></details>

And removing the `#` from the line won't be a conflict? That's the very same line that differs, so it's either always or never a conflict.
___
*[.ci/ubuntu20.04.dockerfile, line 73 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYvERq1TmCVaCh-XxS:-Mh_dGst3MrY3boXhc7q:b-fmd656) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/ubuntu20.04.dockerfile#L73)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

mhm
</blockquote></details>

Hint: if you click on the `Done.` button appropriate message will be added automatically.
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhHdg4q0KoJyuF4jn:-Mh_g8A1EAhLai5hDL4c:bxd6tn1) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L48)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> I'm still confused. Is libdir in our Jenkins setup some non-standard path?

Meson option `--libdir` is standard (see it's not even specified), but it's relative, specificaly relative to `--prefix` and prefix is non-standard, so the end result (groovy variable `libdir`) also points to something arbitrary.

> As a Graphene user, am I expected to override LD_LIBRARY_PATH? Am I expected to override it before building the example? Should this be documented?

Depends on how you configure/build/install graphene. If from deb or you use `--prefix=/usr` or `--prefix=/usr/local` (last one is the default), you don't need to, so it's not documented. But while building the enclave (cc-ing the binary and rendering manifest) you can, it's your decision (esp. if you have some libraries installed in non-standard places like `/opt`).

If you configure with weird `--prefix` (or friends like `--bindir`, `--libdir` etc.), you're on your own like with every self-compiled software and you need to override some subset of `$PATH`,  `$LD_LIBRARY_PATH`, `$LIBRARY_PATH`, `$PYTHONPATH` and in the near future maybe also `$MANPATH` if we want to compile them with meson (I doubt this one). Or possibly edit `/etc/ld.so.conf` and other conf files, and remember to also adjust the manifest.

In short, it behaves exactly like with other projects. It's documented in respective manpages of each piece of software that uses it's own `$WHATEVERPATH`.

> (I still think LD_LIBRARY_PATH influencing how the example is built is a bad idea. This variable is for controlling ld.so, not Graphene build script).

It's the decision of whoever builds the enclave. We shouldn't forbid using this variable if developers so desire. But because we gate the access to filesystem and environment variables, if the entrypoint was built with `LIBRARY_PATH` set, we need to adjust manifest, right? Specifically 1) `LD_LIBRARY_PATH` needs to be forwarded, 2) libraries under this path need to be measured. So that's what happens.
</blockquote></details>

I think you are confusing in-Graphene LD_LIBRARY_PATH with host one. They are both different and never forwarded. Actually the fact that we use it in-Graphene is a hack that needs to be fixed someday.
In any case the current version is incorrect: from what I understand that path contains all Graphene-related libs, including our build of glibc. Things will blow up, if any of the commands below (sh, rm, git, ...) will load that glibc (we might get lucky if loading happens in such order that host glibc is used first).
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 43 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYwIYo4hIFP5rT_v3g:-Mh_evzgBYJUtyYEQbjy:b3vmb76) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-build-sgx.jenkinsfile#L43)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It's hardcoded in jenkins, and it doesn't leave this file. In your own environment you can rename that directory to your heart's content. And this is only needed to query for `--prefix` and `--libdir`, in real life (in deb) this is `'/usr'` and `'lib/x86_64-linux-gnu'` respectively (but not here).
</blockquote></details>

Ah, these are jenkinfiles, sorry, brain lag.
___
*[.ci/lib/stage-clean-check.jenkinsfile, line 43 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYwadH2UF-lwgKEw3t:-Mh_iPkO54lwYVj_G_uA:b86uded) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-clean-check.jenkinsfile#L43)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, lowercase `bionic`. Yes, this refers to "Ubuntu 18.04LTS".
</blockquote></details>

Then please add `ubuntu`, not everyone remembers ubuntu versions by their code name.
___
*[common/src/string/ctype.c, line 10 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYymby4AsP4rKQLeJP:-Mh_i_S60LO1zDese8kd:bxnr2jn) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/common/src/string/ctype.c#L10)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This was done by pushing to #2631. Looks like reviewable has problems with stacked PRs.
</blockquote></details>

No, you've added some commits (from original #2631) to this PR, but now #2631 does not contain them (because you've force pushed it).
Basically: you've force-pushed the base branch, so this PR contains the old version, hence the diff. The reviewable works as expected.
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYzXMn0yDc2E0y2suw:-Mh_hFFe4RHF2-30iD33:brnr0gs) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/Examples/ra-tls-mbedtls/client.manifest.template#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

1) Yes, no surprises, it was explicitly stated in manifest. 2) If you've had overridden it, it was there when you were compiling entrypoint, so if you linked against some library from there, now it's too late, you either pass it through manifest, or dynamic loading of entrypoint fails.
</blockquote></details>

I did not understand you last sentence. In any case this is wrong.
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 49 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhZ2RAl3PcSPTS6GX_v:-Mh_hj_K7x791J2CIVEU:bkt2px0) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/Examples/ra-tls-mbedtls/server.manifest.template#L49)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, this strips all whitespace. Actually this should be glued to the next stanza.
</blockquote></details>

`{%- ...` strips whitespaces before that statement, not after (the newline). The new version looks ok.
___
*[Pal/src/host/Linux-SGX/Makefile, line 166 at r2](https: [...]

2021-08-23 09:43 UTC, pwmarcz requested changes
> Reviewed 1 of 2 files at r3, 3 of 5 files at r4, 2 of 8 files at r5, 1 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[-- commits, line 19 at r6](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhmNzoq0GixlvczWtCM:-MhmNzorEfJWrUst3ulI:bw75hx5) ([raw file](https://github.com/oscarlab/graphene/blob/3d34e10f53c49b25ef67474cf63e65367677b57d/-- commits#L19)):*
Actually, doesn't this need my signoff as well? Or do we use `Co-authored-by` for that?

@mkow I remember you doing something like that recently, can you advise?

(this is a short patch I pasted in one of the reviewable comments)
___
*[.ci/ubuntu18.04.dockerfile, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXeje55GXozYl08ykg:-MhmK9rO94_oIvi-hVvT:b-ucfknh) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/ubuntu18.04.dockerfile#L73)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Makes sense. Done.
</blockquote></details>

Thanks!
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhInK6NXsgplPO3Xi:-MhmKMA6CCO-Pv_r6opD:b16ej0n) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L42)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`$WORKSPACE/usr/lib/x86_64-linux-gnu` most likely, so `/home/jenkins/$JOBNAME/usr/lib/x86_64-linux-gnu`. "x86_64-linux-gnu" is default on debian-like, so will change on RHEL/CentOS/AlmaLinux.
</blockquote></details>

I see. Thanks for the comment.
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhHdg4q0KoJyuF4jn:-MhmKWLi9WWQKdkuXvNR:b-erkua3) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L48)):*
>In any case the current version is incorrect: from what I understand that path contains all Graphene-related libs, including our build of glibc. Things will blow up, if any of the commands below (sh, rm, git, ...) will load that glibc (we might get lucky if loading happens in such order that host glibc is used first).

I don't think that's true. The patched libraries are not under `libdir`, but `libdir/graphene`.
___
*[.ci/lib/stage-clean-check.jenkinsfile, line 43 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYwadH2UF-lwgKEw3t:-MhmKimQ9rlAovUCkvaj:b-6bzjwu) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-clean-check.jenkinsfile#L43)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then please add `ubuntu`, not everyone remembers ubuntu versions by their code name.
</blockquote></details>

+1, especially since the alphabet wrapped around back to `b` so I never remember which one is the newer one :)
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYzXMn0yDc2E0y2suw:-MhmKyYX0KSmczk4_68T:b55dq0a) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/Examples/ra-tls-mbedtls/client.manifest.template#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I did not understand you last sentence. In any case this is wrong.
</blockquote></details>

I'm still not convinced that this is the way to go and there are no better alternatives. We're planning a call, can we talk about it then?
___
*[Pal/src/host/Linux-SGX/protected-files/meson.build, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYJo3W12OSVN5Qvcxn:-MhmMu_S0q4Qwa2bc2IO:bj1l038) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/Pal/src/host/Linux-SGX/protected-files/meson.build#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How? In release these asserts are no-op.
</blockquote></details>

Yeah... I tried to replicate it locally and couldn't:

```c
pawel ~/test $ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

pawel ~/test $ cat test.c 

#include <stdlib.h>
#include <assert.h>

int x;
int* f(int y) { return y ? &x : NULL; }
int g(int y) {
   int* xp = f(y);
   assert(xp);
   return *xp;
}
pawel ~/test $ gcc -c test.c -O3 -Wnull-dereference
pawel ~/test $ gcc -c test.c -O3 -Wnull-dereference -DNDEBUG
test.c: In function ‘g’:
test.c:10:11: warning: potential null pointer dereference [-Wnull-dereference]
   10 |    return *xp;
      |           ^~~
```

So I'm wondering... Are we compiling this with `-DNDEBUG` and `-O3`? @woju can you check that?


<!-- Sent from Reviewable.io -->

2021-08-24 18:29 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[-- commits, line 19 at r6](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhmNzoq0GixlvczWtCM):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Actually, doesn't this need my signoff as well? Or do we use `Co-authored-by` for that?

@mkow I remember you doing something like that recently, can you advise?

(this is a short patch I pasted in one of the reviewable comments)
</blockquote></details>

`Co-authored-by` is wrong in this case, because you're the author of 100% of diff, I'm only the committer.

In any case, you'd have to submit the `Signed-off-by:` line yourself, I cannot sign anything in your name. We could skip this if we agree that the amount and creativity of the patch isn't too high.
___
*[meson.build, line 107 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYHxiwA2dNnZufbxmj:-MhmV29_CHyjaYCuyk8b:bl0b8ss) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/meson.build#L107)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And removing the `#` from the line won't be a conflict? That's the very same line that differs, so it's either always or never a conflict.
</blockquote></details>

How do you know what's in the next patch in the queue?

In any case, @mkow this is fixed, plz resolve.
___
*[.ci/ubuntu20.04.dockerfile, line 73 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYvERq1TmCVaCh-XxS:-Mhbo9q17dG_Zz5c6HcU:b30frco) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/ubuntu20.04.dockerfile#L73)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hint: if you click on the `Done.` button appropriate message will be added automatically.
</blockquote></details>

yes, I know
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhHdg4q0KoJyuF4jn:-MhtPfZpDahQXO6qjbPA:b-ejv579) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L48)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>In any case the current version is incorrect: from what I understand that path contains all Graphene-related libs, including our build of glibc. Things will blow up, if any of the commands below (sh, rm, git, ...) will load that glibc (we might get lucky if loading happens in such order that host glibc is used first).

I don't think that's true. The patched libraries are not under `libdir`, but `libdir/graphene`.
</blockquote></details>

The problem is, it's the same library and the same binary. But anyway, this revision doesn't directly rely on `env.LD_LIBRARY_PATH`, instead it passes it through `-D`.
___
*[.ci/lib/stage-clean-check.jenkinsfile, line 43 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYwadH2UF-lwgKEw3t:-MhmsIip5WRW976ypYsr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-clean-check.jenkinsfile#L43)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

+1, especially since the alphabet wrapped around back to `b` so I never remember which one is the newer one :)
</blockquote></details>

Done.
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYzXMn0yDc2E0y2suw:-MhtPYRuDez4XN11JV9E:bayqjat) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/Examples/ra-tls-mbedtls/client.manifest.template#L7)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'm still not convinced that this is the way to go and there are no better alternatives. We're planning a call, can we talk about it then?
</blockquote></details>

So here's another version. Do you like it better?
___
*[Pal/src/host/Linux-SGX/protected-files/meson.build, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYJo3W12OSVN5Qvcxn:-MhtOFUiDrXuBMeA838L:b-gqnz5s) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/Pal/src/host/Linux-SGX/protected-files/meson.build#L13)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yeah... I tried to replicate it locally and couldn't:

```c
pawel ~/test $ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

pawel ~/test $ cat test.c 

#include <stdlib.h>
#include <assert.h>

int x;
int* f(int y) { return y ? &x : NULL; }
int g(int y) {
   int* xp = f(y);
   assert(xp);
   return *xp;
}
pawel ~/test $ gcc -c test.c -O3 -Wnull-dereference
pawel ~/test $ gcc -c test.c -O3 -Wnull-dereference -DNDEBUG
test.c: In function ‘g’:
test.c:10:11: warning: potential null pointer dereference [-Wnull-dereference]
   10 |    return *xp;
      |           ^~~
```

So I'm wondering... Are we compiling this with `-DNDEBUG` and `-O3`? @woju can you check that?
</blockquote></details>

`-O3`, no `-DNDEBUG`.

<details><summary>Click here for the full line</summary>
`cc -IPal/src/host/Linux-SGX/tools/common/libsgx_util.so.p -IPal/src/host/Linux-SGX/tools/common -I../Pal/src/host/Linux-SGX/tools/common -IPal/include -I../Pal/include -I../Pal/include/pal -I../Pal/include/arch/x86_64 -Icommon/include -I../common/include -I../common/include/arch/x86_64 -IPal/src/host/Linux-SGX -I../Pal/src/host/Linux-SGX -I../Pal/include/arch/x86_64/Linux -I../Pal/include/host/Linux-common -IPal/src/host/Linux-SGX/protected-files -I../Pal/src/host/Linux-SGX/protected-files -Isubprojects/cJSON-1.7.12 -I../subprojects/cJSON-1.7.12 -I../subprojects/mbedtls-mbedtls-2.26.0/include -I/usr/include/x86_64-linux-gnu -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c11 -O3 -Wa,--noexecstack -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wtrampolines -Wnull-dereference -fPIC -DHAVE_INTERNAL_CJSON -MD -MQ Pal/src/host/Linux-SGX/tools/common/libsgx_util.so.p/.._.._protected-files_lru_cache.c.o -MF Pal/src/host/Linux-SGX/tools/common/libsgx_util.so.p/.._.._protected-files_lru_cache.c.o.d -o Pal/src/host/Linux-SGX/tools/common/libsgx_util.so.p/.._.._protected-files_lru_cache.c.o -c ../Pal/src/host/Linux-SGX/protected-files/lru_cache.c`
</details>

BUT we define our own `assert()` in `common/include/assert.h`, and this assert is on `#ifdef DEBUG` and not `#ifndef NDEBUG` (and we don't add `-DDEBUG` either). There's a TODO comment about this. I'm not sure how this should work in the end.


<!-- Sent from Reviewable.io -->

2021-08-25 10:19 UTC, pwmarcz requested changes
> Reviewed 1 of 2 files at r3, 1 of 5 files at r4, 1 of 8 files at r5, 3 of 9 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[-- commits, line 19 at r6](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhmNzoq0GixlvczWtCM):*
>We could skip this if we agree that the amount and creativity of the patch isn't too high.

That's the best option, I think. Feel free to commit this fix under your own name.
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhHdg4q0KoJyuF4jn:-MhwluSN5i3wnzvrJmwl:b-6b6cle) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L48)):*
As discussed, can we have a comment here? Something like:

>Make sure Graphene's command-line tools can use their libraries, which we install in `libdir` (e.g. `graphene-sgx-pf-crypt` needs `libsgx_util.so`).
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYzXMn0yDc2E0y2suw:-Mhwbb0n67xLFFvctITl:bm8vi4a) ([raw file](https://github.com/oscarlab/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/Examples/ra-tls-mbedtls/client.manifest.template#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

So here's another version. Do you like it better?
</blockquote></details>

But the example still uses `LD_LIBRARY_PATH` to control mounts, only it's being read in Makefile now:

```
-Dadd_library_paths=$(LD_LIBRARY_PATH) 
```

So this doesn't change anything for the user. One way would be to instead use another env variable, such as `-Dadd_library_paths=$(GRAPHENE_ADD_LIBRARY_PATHS)`. 

However, I see the Python tools already know where Graphene is installed, and  provide this path to template (`{{ graphene.pkglibdir }}` which is `<libdir>/graphene`). Can we get the path we want here (`<libdir>`) from Python tools as well? Then the user wouldn't have to set any environment variable to make it work.

Another option: also install these libraries somewhere under `<libdir>/graphene`, explicitly mount them. I see we already do that for mbedtls; we mount `<libdir>/graphene/mbedtls` (is that going to be removed btw?). If you don't want to make a copy, make a symlink (`ln -s <libdir>/graphene/sgx_util.so <libdir>/sgx_util.so`).
___
*[Pal/src/host/Linux-SGX/protected-files/meson.build, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYJo3W12OSVN5Qvcxn:-MhwiPl5-owUdxA5WSz5:bu4k7x8) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/Pal/src/host/Linux-SGX/protected-files/meson.build#L13)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`-O3`, no `-DNDEBUG`.

<details><summary>Click here for the full line</summary>
`cc -IPal/src/host/Linux-SGX/tools/common/libsgx_util.so.p -IPal/src/host/Linux-SGX/tools/common -I../Pal/src/host/Linux-SGX/tools/common -IPal/include -I../Pal/include -I../Pal/include/pal -I../Pal/include/arch/x86_64 -Icommon/include -I../common/include -I../common/include/arch/x86_64 -IPal/src/host/Linux-SGX -I../Pal/src/host/Linux-SGX -I../Pal/include/arch/x86_64/Linux -I../Pal/include/host/Linux-common -IPal/src/host/Linux-SGX/protected-files -I../Pal/src/host/Linux-SGX/protected-files -Isubprojects/cJSON-1.7.12 -I../subprojects/cJSON-1.7.12 -I../subprojects/mbedtls-mbedtls-2.26.0/include -I/usr/include/x86_64-linux-gnu -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c11 -O3 -Wa,--noexecstack -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wtrampolines -Wnull-dereference -fPIC -DHAVE_INTERNAL_CJSON -MD -MQ Pal/src/host/Linux-SGX/tools/common/libsgx_util.so.p/.._.._protected-files_lru_cache.c.o -MF Pal/src/host/Linux-SGX/tools/common/libsgx_util.so.p/.._.._protected-files_lru_cache.c.o.d -o Pal/src/host/Linux-SGX/tools/common/libsgx_util.so.p/.._.._protected-files_lru_cache.c.o -c ../Pal/src/host/Linux-SGX/protected-files/lru_cache.c`
</details>

BUT we define our own `assert()` in `common/include/assert.h`, and this assert is on `#ifdef DEBUG` and not `#ifndef NDEBUG` (and we don't add `-DDEBUG` either). There's a TODO comment about this. I'm not sure how this should work in the end.
</blockquote></details>

That's not true: `lru_cache.c` includes `<assert.h>` in this case (note the `#ifdef IN_PAL`). Which makes sense, because we're not even linking Graphene's common library.

I think that for consistency, our release builds should globally define `-DNDEBUG`. It won't do anything bad to Graphene's no-stdlib code, and for the few libraries/command-line tools that use the standard library (like here), it will ensure they behave the same.


<!-- Sent from Reviewable.io -->

2021-08-27 23:52 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 75 of 79 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[-- commits, line 10 at r8](https://reviewable.io/reviews/oscarlab/graphene/2645#-Mi78zts9iOqfD0NQ9HP):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

They already have +1 from borys
</blockquote></details>

This PR is _huge_, I'd really feel more comfortable with having a few smaller ones, especially that these bugfixes are completely independent from each other ;)


<!-- Sent from Reviewable.io -->

2021-08-30 08:37 UTC, pwmarcz reviewed
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXku6M2_eUhsPTm2bd:-MiL8gVN38tWsYytPk1U:b5qiwmf) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yeah. Meson 0.45 is a lost cause, because we also need to `link_with: custom_target()`, because that's how we build patched mbedtls. So this means we will be able to use `/` for joining paths after all, but I probably won't fix this in this PR. 
</blockquote></details>

Looks good, resolving.

---


<!-- Sent from Reviewable.io -->

2021-08-30 09:33 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[-- commits, line 10 at r8](https://reviewable.io/reviews/oscarlab/graphene/2645#-Mi78zts9iOqfD0NQ9HP):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This PR is _huge_, I'd really feel more comfortable with having a few smaller ones, especially that these bugfixes are completely independent from each other ;)
</blockquote></details>

I submitted my two fixes in #2668.


<!-- Sent from Reviewable.io -->

2021-08-30 09:58 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[-- commits, line 10 at r8](https://reviewable.io/reviews/oscarlab/graphene/2645#-Mi78zts9iOqfD0NQ9HP):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I submitted my two fixes in #2668.
</blockquote></details>

And merged.


<!-- Sent from Reviewable.io -->

2021-08-30 12:13 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 78 of 79 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[-- commits, line 10 at r8](https://reviewable.io/reviews/oscarlab/graphene/2645#-Mi78zts9iOqfD0NQ9HP):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

And merged.
</blockquote></details>

I rebased this PR on top of that.


<!-- Sent from Reviewable.io -->

2021-08-30 14:30 UTC, boryspoplawski requested changes
> Reviewed 1 of 8 files at r7, 10 of 23 files at r8, 4 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[.ci/ubuntu18.04.dockerfile, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXeje55GXozYl08ykg:-MhZG_LZCWiTY5wxcQjb:b51sppq) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/ubuntu18.04.dockerfile#L73)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Actually, wouldn't `meson==0.55` do exactly what we want?
___
*[Documentation/building.rst, line 46 at r10](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiMO-ObEunguS2k3xmE:-MiMO-ObEunguS2k3xmF:blkb0b7) ([raw file](https://github.com/oscarlab/graphene/blob/aa93875ad9962c9bcfc36753128dc3ec3c256696/Documentation/building.rst#L46)):*
> ```reStructuredText
>         autoconf bison gawk ninja-build python3 python3-click python3-jinja2 \
>         wget
>     python3 -m pip install meson
> ```

Shouldn't we add version requirements?
___
*[Documentation/quickstart.rst, line 21 at r10](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiMO2cnD_NybIiT0xVB:-MiMO2coBXKgPMXbNNsR:bgjzwnv) ([raw file](https://github.com/oscarlab/graphene/blob/aa93875ad9962c9bcfc36753128dc3ec3c256696/Documentation/quickstart.rst#L21)):*
> ```reStructuredText
>           autoconf bison gawk ninja-build python3 python3-click python3-jinja2 \
>           wget
>       python3 -m pip install 'meson>=0.55'
> ```

Don't we require exactly `0.55.x`?
___
*[Documentation/quickstart.rst, line 69 at r10](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiMOmom27f5OxP-YmUs:-MiMOmom27f5OxP-YmUt:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/aa93875ad9962c9bcfc36753128dc3ec3c256696/Documentation/quickstart.rst#L69)):*
> ```reStructuredText
>           ninja-build protobuf-c-compiler python3 python3-click python3-jinja2 \
>           python3-pip python3-protobuf wget
>       python3 -m pip install 'meson>=0.55' 'toml>=0.10'
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-08-30 14:44 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[.ci/ubuntu18.04.dockerfile, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXeje55GXozYl08ykg:-MiMToFE377AKwcxFohE:bppabhi) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/ubuntu18.04.dockerfile#L73)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, wouldn't `meson==0.55` do exactly what we want?
</blockquote></details>

No,`==0.55` doesn't match anything but 0.55.0, but we're fine with 0.55.3 for example. We could think about `==0.55.*`; `.*` is a special syntax which also matches things without a dot like `0.55a1`. Here are the rules: https://www.python.org/dev/peps/pep-0440/#version-matching.
___
*[Documentation/building.rst, line 46 at r10](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiMO-ObEunguS2k3xmE:-MiMVySTCtl8CfWM0kEk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/aa93875ad9962c9bcfc36753128dc3ec3c256696/Documentation/building.rst#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't we add version requirements?
</blockquote></details>

Done.
___
*[Documentation/quickstart.rst, line 21 at r10](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiMO2cnD_NybIiT0xVB:-MiMTFyV9-aq6T-LuZ3w:b-ka3rw5) ([raw file](https://github.com/oscarlab/graphene/blob/aa93875ad9962c9bcfc36753128dc3ec3c256696/Documentation/quickstart.rst#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't we require exactly `0.55.x`?
</blockquote></details>

No, we support anything newer than 0.55.0, so we test 0.55.x in Jenkins, but whoever uses graphene is free to use any later version.


<!-- Sent from Reviewable.io -->

2021-08-30 15:08 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[.ci/ubuntu18.04.dockerfile, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXeje55GXozYl08ykg:-MiM_kdN84eyTy_U4BjK:b-no5zk4) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/ubuntu18.04.dockerfile#L73)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No,`==0.55` doesn't match anything but 0.55.0, but we're fine with 0.55.3 for example. We could think about `==0.55.*`; `.*` is a special syntax which also matches things without a dot like `0.55a1`. Here are the rules: https://www.python.org/dev/peps/pep-0440/#version-matching.
</blockquote></details>

Oh, all right then.
___
*[.ci/ubuntu18.04.dockerfile, line 73 at r11](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiMa0LZ2lpExHst5rvg:-MiMa0LZ2lpExHst5rvh:by81qpv) ([raw file](https://github.com/oscarlab/graphene/blob/7744057d31e9c2439869fd61460267d759a54bad/.ci/ubuntu18.04.dockerfile#L73)):*
> ```Dockerfile
>     sphinx_rtd_theme \
>     'toml>=0.10' \
>     'meson>=0.55,<0.56'
> ```

Please add a comment describing why we pin the version so specifically (since we support any newer).
___
*[Documentation/quickstart.rst, line 21 at r10](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiMO2cnD_NybIiT0xVB:-MiM_wVR-_tws0orGBUd:b-4hvi0m) ([raw file](https://github.com/oscarlab/graphene/blob/aa93875ad9962c9bcfc36753128dc3ec3c256696/Documentation/quickstart.rst#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, we support anything newer than 0.55.0, so we test 0.55.x in Jenkins, but whoever uses graphene is free to use any later version.
</blockquote></details>

Got it.


<!-- Sent from Reviewable.io -->

2021-08-30 15:44 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 76 of 79 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[.ci/ubuntu18.04.dockerfile, line 73 at r11](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiMa0LZ2lpExHst5rvg:-MiMisqSCDbcyx3iNuXN:b-eo8thk) ([raw file](https://github.com/oscarlab/graphene/blob/7744057d31e9c2439869fd61460267d759a54bad/.ci/ubuntu18.04.dockerfile#L73)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add a comment describing why we pin the version so specifically (since we support any newer).
</blockquote></details>

Done, also 20.04.


<!-- Sent from Reviewable.io -->

2021-08-30 17:14 UTC, boryspoplawski reviewed
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2021-08-30 17:17 UTC, boryspoplawski commented
Jenkins, retest Jenkins-20.04 please (LTP fcntl14, setrlimit02, setrlimit03, setrlimit05 timed out, unrelated)

2021-08-31 10:42 UTC, anjalirai-intel commented
Hi @woju

I wanted to know what is the status of Meson changes for Graphene? As part of Meson changes make command will be replaced by Meson but in documentation I still see that make commands are still in use, so I wanted to know if there will be other PR's for Meson and is it part of Release 1.0 validation. 

As part of this PR, there has been some changes done for meson, for e.g. is_sgx_available does not have make file, is it supposed to be built along with initial make at Graphene source level directory or it has to be built separately. If someone has to build is_sgx_available, how they can build it manually?





<!-- Sent from Reviewable.io -->

2021-08-31 10:51 UTC, jinengandhi-intel reviewed
Woju, what Anjali is trying to get to is that with the meson changes we were expecting all make commands to be eliminated, but in the README, you say that for now we will continue to use both build chains. So is this the final PR for meson? or we are expecting more? On the is_sgx_available tool, what Anjali noticed is that the tool is not getting built automatically, is that expected? If yes, then can you share the command to build the tool?

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645#-:-MiQonwUE8ngNTDI1eSl:b-o5982s)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2021-08-31 11:37 UTC, woju reviewed
> I wanted to know what is the status of Meson changes for Graphene? As part of Meson changes make command will be replaced by Meson but in documentation I still see that make commands are still in use, so I wanted to know if there will be other PR's for Meson and is it part of Release 1.0 validation.

I'm not sure, depending on how much time we'll have, we might or might not use make. The main aim of the build system rewrite is to make packaging, so at least Pal/sgx will be rewritten into meson (#2466), but I can't promise anything about glibc, which in principle is not required to be included into meson to make packaging viable. We intend to do this eventually, but given the short timeline we might or might not manage to do this before freeze.

(I think you're talking about 1.2). 

> As part of this PR, there has been some changes done for meson, for e.g. is_sgx_available does not have make file, is it supposed to be built along with initial make at Graphene source level directory or it has to be built separately.

By default it is built by default together with the rest of graphene, if you enabled `-Dsgx`. It is renamed `is-sgx-available` (with dashes, not underlines, to save clicking on shift).

> If someone has to build is_sgx_available, how they can build it manually?

If you want to build it without anything else (apart from dependencies), you can specify the target to ninja:

```sh
# (previous commands omitted)
meson setup build/ -Dsgx=enabled # [the rest of options ...]
ninja -C build/ is-sgx-available
```

Then it's built in respective subdirectory under the `build/`. You may execute it directly from there.

> Woju, what Anjali is trying to get to is that with the meson changes we were expecting all make commands to be eliminated, but in the README, you say that for now we will continue to use both build chains.

Yes, that's correct.

> So is this the final PR for meson? or we are expecting more

There will be further PRs, I just can't promise how much we'll be able to merge before freeze. In any case, the documentation will be up-to-date at the time of freeze, then I'll be able to definitely answer the question, if you'll need to also run make.

Also, heads up: there will be another way of building graphene, by invoking dpkg build tools, which will invoke meson and possibly make indirectly. That will be another PR or possibly another repo, I'm not sure, and probably it will not be available at the start of the freeze, because it's not a "feature" that will be frozen, just another way of invoking build chain.

> On the is_sgx_available tool, what Anjali noticed is that the tool is not getting built automatically, is that expected? If yes, then can you share the command to build the tool?

No, it's built and installed if you configure with `-Dsgx=enabled`. See for yourself in CI log of any SGX pipeline (grep for `is-sgx-available`, there are two lines, compile and link).

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645#-:-MiQqh6z2vHHuJ9drF-S:bp02my)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2021-08-31 11:49 UTC, jinengandhi-intel reviewed
Thanks Woju for the response. So on the meson build side, from what I understand is that post this PR, we will be merging PR 2466 and that would complete move of PAL to meson and this is for sure planned for 1.2 release? Completely removing the make build chain that is used by glibc may not happen before the freeze. Is that right?

On the is_sgx_available tool, Anjali will re-verify on her system and get back to you.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645#-:-MiR0xydB10TDLDZ6iRr:b-dty8fg)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2021-08-31 12:19 UTC, woju reviewed
> Thanks Woju for the response. So on the meson build side, from what I understand is that post this PR, we will be merging PR 2466 and that would complete move of PAL to meson and this is for sure planned for 1.2 release?

Yes, that's correct.

> Completely removing the make build chain that is used by glibc may not happen before the freeze. Is that right?

We don't exactly indend to remove all the make, because glibc is internally built with make and that won't change, you'll still need make to be installed as build dependency. We'll just wrap that in meson, so you won't need to run make separately, it will be managed by meson+ninja. Yes, this might not happen before freeze.

And to be sure, we won't remove make from `Examples/` before freeze, because that's not needed for packaging either.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645#-:-MiR7Rxn7swcwSTICG93:b-qog9im)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2021-08-31 12:36 UTC, anjalirai-intel commented
@woju @jinengandhi-intel 

Yes, I could see is-sgx-available executable in /usr/local/bin. Initially it used to be in the Pal/src/host/Linux-SGX/tools/is-sgx-available so i was verifying in the previous location itself.

2021-08-31 14:08 UTC, dimakuv requested changes
> Reviewed 41 of 61 files at r1, 2 of 2 files at r3, 3 of 5 files at r4, 2 of 8 files at r5, 1 of 8 files at r7, 9 of 23 files at r8, 3 of 4 files at r9, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[meson.build, line 20 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRGUTg5QOu8QLNwX-O:-MiRGUTh2rn9OFC5NGtG:b-d1o7yq) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/meson.build#L20)):*
> ```Meson
>     #
>     # https://wiki.ubuntu.com/Releases
>     # https://wiki.debian.org/DebianReleases#Production_Releases
> ```

What's the point of this table now that we require a very new version of meson?
___
*[meson.build, line 105 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRHL4M9nv_qY08Fmev:-MiRHL4M9nv_qY08Fmew:b6zsmbr) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/meson.build#L105)):*
> ```Meson
>     threads_dep = dependency('threads')
> 
>     # this one is bizarre, will be compiled in different ways: one for LibOS, one for PAL
> ```

I think we discussed this offline at some point, but what does it mean `one for LibOS`? mbedTLS is not used in the LibOS component at all. We only have:
- special-configuration mbedTLS statically linked into the trusted Linux-SGX PAL
- "almost-normal"-configuration mbedTLS dynamically linked with the "normal" shared libraries like RA-TLS and Secret Prov.
___
*[Pal/src/host/Linux-SGX/tools/ias-request/meson.build, line 9 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRTh5w1jc8hYxrWZC8:-MiRTh5w1jc8hYxrWZC9:b-ugzzm3) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/tools/ias-request/meson.build#L9)):*
> ```Meson
>     ],
> 
>     install: false,
> ```

Why false here?
___
*[Pal/src/host/Linux-SGX/tools/quote-dump/meson.build, line 9 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRU2n9BULyXYXnyruw:-MiRU2n9BULyXYXnyrux:bnryugp) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/tools/quote-dump/meson.build#L9)):*
> ```Meson
>     ],
> 
>     install: false,
> ```

Why false?
___
*[Pal/src/host/Linux-SGX/tools/verify-ias-report/meson.build, line 9 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRULcF9CWpCzN3DpC2:-MiRULcF9CWpCzN3DpC3:bnryugp) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/tools/verify-ias-report/meson.build#L9)):*
> ```Meson
>     ],
> 
>     install: false,
> ```

Why false?
___
*[subprojects/cJSON-1.7.12.wrap, line 7 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRWowe1528YOhYBsRN:-MiRWowf2_P-BuXEAh14:b-smh1ja) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/subprojects/cJSON-1.7.12.wrap#L7)):*
> ```
> source_filename = cJSON-1.7.12.tar.gz
> source_hash = 760687665ab41a5cff9c40b1053c19572bcdaadef1194e5cba1b5e6f824686e7
> patch_directory = cJSON
> ```

But we don't patch cJSON, what's this?
___
*[subprojects/packagefiles/mbedtls/meson.build, line 19 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRVfpk2dgUYaif7Vty:-MiRVfpk2dgUYaif7Vtz:bgs4wzs) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/subprojects/packagefiles/mbedtls/meson.build#L19)):*
> ```Meson
>     ],
> 
>     input: ['Makefile', 'graphene.patch'],
> ```

What is this `Makefile` here?
___
*[subprojects/packagefiles/mbedtls/meson.build, line 45 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRVnDp8_6BOP5R63-c:-MiRVnDp8_6BOP5R63-d:bgs4wzs) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/subprojects/packagefiles/mbedtls/meson.build#L45)):*
> ```Meson
>     ],
> 
>     input: ['Makefile', 'graphene.patch'],
> ```

What is this `Makefile` here?
___
*[subprojects/packagefiles/mbedtls/meson.build, line 57 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRVuFo-DdscA6-_Scq:-MiRVuFo-DdscA6-_Scr:b2s2ria) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/subprojects/packagefiles/mbedtls/meson.build#L57)):*
> ```Meson
> 
> mbedtls_inc = include_directories('include')
> #mbedtls_incpath = meson.current_source_dir() / 'include'
> ```

What is this?
___
*[subprojects/packagefiles/mbedtls/meson.build, line 66 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRWC2zEfePw_VxlJL0:-MiRWC2zEfePw_VxlJL1:b-m0txxw) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/subprojects/packagefiles/mbedtls/meson.build#L66)):*
> ```Meson
>     link_with: mbedtls_pal_libs,
>     include_directories: mbedtls_inc,
>     compile_args: '-DMBEDTLS_CONFIG_FILE="mbedtls/config-pal.h"',
> ```

You already have this flag in `compile-pal.sh`, why is it needed here?


<!-- Sent from Reviewable.io -->

2021-08-31 14:51 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[meson.build, line 20 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRGUTg5QOu8QLNwX-O:-MiRfDQv-4cwhXimsxyn:b-xn0pwv) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/meson.build#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point of this table now that we require a very new version of meson?
</blockquote></details>

This is an early version of https://noc.grapheneproject.io/~woju/distros/, I don't use this one and we can remove it altogether.
___
*[meson.build, line 105 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRHL4M9nv_qY08Fmev:-MiRg6-_CxGNsHd_SMDl:bhlkg17) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/meson.build#L105)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think we discussed this offline at some point, but what does it mean `one for LibOS`? mbedTLS is not used in the LibOS component at all. We only have:
- special-configuration mbedTLS statically linked into the trusted Linux-SGX PAL
- "almost-normal"-configuration mbedTLS dynamically linked with the "normal" shared libraries like RA-TLS and Secret Prov.
</blockquote></details>

Yep, this is misleading. I'll fix this.
___
*[Pal/src/host/Linux-SGX/tools/ias-request/meson.build, line 9 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRTh5w1jc8hYxrWZC8:-MiRgAm97UaGPWxHJFGd:b-ysyuz) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/tools/ias-request/meson.build#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why false here?
</blockquote></details>

Do we want to install this? We don't use it AFAIK.
___
*[Pal/src/host/Linux-SGX/tools/quote-dump/meson.build, line 9 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRU2n9BULyXYXnyruw:-MiRgHQi6S-94iBDAjKJ:b-ysyuz) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/tools/quote-dump/meson.build#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why false?
</blockquote></details>

Do we want to install this? We don't use it AFAIK.
___
*[Pal/src/host/Linux-SGX/tools/verify-ias-report/meson.build, line 9 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRULcF9CWpCzN3DpC2:-MiRgInV9dpmy1uxu81V:b-ysyuz) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/tools/verify-ias-report/meson.build#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why false?
</blockquote></details>

Do we want to install this? We don't use it AFAIK.
___
*[subprojects/cJSON-1.7.12.wrap, line 7 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRWowe1528YOhYBsRN:-MiRdcBW6wKqnsFPXyH-:b9kffrv) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/subprojects/cJSON-1.7.12.wrap#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But we don't patch cJSON, what's this?
</blockquote></details>

This is poorly named option. It should have been named "overlay" or something like that, not patch. We add `meson.build`, see `subprojects/packagefiles/cJSON`.
___
*[subprojects/packagefiles/mbedtls/meson.build, line 19 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRVfpk2dgUYaif7Vty:-MiRdvAg274SK2Mqb8IP:b-1yspq5) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/subprojects/packagefiles/mbedtls/meson.build#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this `Makefile` here?
</blockquote></details>

This is Makefile from mbedtls. We add as dependency, so if it changes, we recompile.
___
*[subprojects/packagefiles/mbedtls/meson.build, line 45 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRVnDp8_6BOP5R63-c:-MiRe4nwB9zTpxEwjXpR:bnj7hl0) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/subprojects/packagefiles/mbedtls/meson.build#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this `Makefile` here?
</blockquote></details>

same as above
___
*[subprojects/packagefiles/mbedtls/meson.build, line 57 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRVuFo-DdscA6-_Scq:-MiRe7B5C5uM9WBLrgXy:bhr3x8o) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/subprojects/packagefiles/mbedtls/meson.build#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

This is include from mbedtls, which we should install, but currently don't, so in Examples we download alternative version of the sources and patch ourselves.
___
*[subprojects/packagefiles/mbedtls/meson.build, line 66 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRWC2zEfePw_VxlJL0:-MiReKqx3matgjlq9D27:b-sxe6an) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/subprojects/packagefiles/mbedtls/meson.build#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You already have this flag in `compile-pal.sh`, why is it needed here?
</blockquote></details>

This one has no bearing on the compilation of mbedtls itself, instead it is added to every single compilation step when we intend to link against mbedtls (more specifically, where we add dependency on `mbedtls_pal_dep`). This is needed, because mbedtls headers are littered with `#ifdef`s against `MBEDTLS_*_C` (like MBEDTLS_CMAC_C, which we flip), so we need to ensure that every compilation unit has included proper mbedtls config.


<!-- Sent from Reviewable.io -->

2021-09-01 11:26 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[meson.build, line 20 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRGUTg5QOu8QLNwX-O:-MiW4rSe4fAj98gIiyW-:b26y2oh) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/meson.build#L20)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is an early version of https://noc.grapheneproject.io/~woju/distros/, I don't use this one and we can remove it altogether.
</blockquote></details>

Can we remove them in this PR?
___
*[Pal/src/host/Linux-SGX/tools/ias-request/meson.build, line 9 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRTh5w1jc8hYxrWZC8:-MiW5-7TAw2SDWTS3HpF:buos5zd) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/tools/ias-request/meson.build#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Do we want to install this? We don't use it AFAIK.
</blockquote></details>

Yeah, we don't really use it... Ok, I guess no user of Graphene will ever use this utility.

I sometimes use these IAS/Quote utils for debugging purposes, but I guess I can just grab these utils from the `build/` directory (or manually change the `meson.build` files). Resolved.
___
*[subprojects/packagefiles/mbedtls/meson.build, line 57 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRVuFo-DdscA6-_Scq:-MiW5hJd5sZLroQFfHT-:b-715bvb) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/subprojects/packagefiles/mbedtls/meson.build#L57)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is include from mbedtls, which we should install, but currently don't, so in Examples we download alternative version of the sources and patch ourselves.
</blockquote></details>

Why not just remove this commented-out line then? Or if you want to use it in the future, please add a comment.
___
*[subprojects/packagefiles/mbedtls/meson.build, line 66 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRWC2zEfePw_VxlJL0:-MiW5uYh18TupYNPN6Cb:bfghvnl) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/subprojects/packagefiles/mbedtls/meson.build#L66)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This one has no bearing on the compilation of mbedtls itself, instead it is added to every single compilation step when we intend to link against mbedtls (more specifically, where we add dependency on `mbedtls_pal_dep`). This is needed, because mbedtls headers are littered with `#ifdef`s against `MBEDTLS_*_C` (like MBEDTLS_CMAC_C, which we flip), so we need to ensure that every compilation unit has included proper mbedtls config.
</blockquote></details>

OK. Tricky but makes sense.


<!-- Sent from Reviewable.io -->

2021-09-01 11:54 UTC, mkow requested changes
> Reviewed 39 of 61 files at r1, 2 of 2 files at r3, 3 of 5 files at r4, 2 of 8 files at r5, 1 of 8 files at r7, 23 of 23 files at r8, 3 of 4 files at r9, 1 of 1 files at r10, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[-- commits, line 3 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVFc102BD4RXC2A1lP):*
`meson` -> `Meson`
`sgx` -> `SGX`
___
*[-- commits, line 10 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVFuC36WuSNRUh2pCx):*
ditto
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhHdg4q0KoJyuF4jn:-MiVIieQ9QAuQZK_agmv:b-x0nuvq) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L48)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

I also don't like using `LD_LIBRARY_PATH`, it's quite hacky and things may blow up in weird ways in the future because of this.

Could we use `-Wl,-rpath`, but only if `--prefix` is non-standard? (e.g. if it was provided in the cmdline?) The binaries built are by-design tied to specific compilation flags, so it should be completely fine to build them for a specific installation prefix.
___
*[.ci/lib/stage-clean-check.jenkinsfile, line 43 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVJcLc4w2-u6T30WIm:-MiVJcLc4w2-u6T30WIn:bb3468r) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/.ci/lib/stage-clean-check.jenkinsfile#L43)):*
> ```
> on Ubuntu 18.04, git clean -Xf fails
> ```

why and how?
___
*[Documentation/building.rst, line 48 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVK9JW9G2k1pS-R7YE:-MiVK9JW9G2k1pS-R7YF:b-wny3a0) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Documentation/building.rst#L48)):*
> ```
> so
> ```

This connects the sentences in a weird way logically. The intended meaning is _because we require >= 0.55, you need at least Debian 11/[...] to install from apt instead of pip_.
___
*[Documentation/quickstart.rst, line 14 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVM8XS-O5P8y2sV1pz:-MiVM1HrCzjrhiFviO0L:bp2fjo) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Documentation/quickstart.rst#L14)):*
> ```reStructuredText
> 
> .. NOTE if you're about to sort the apt-get invocation below, see note in
>    building.rst
> ```

Seems this broke the numbering, it displays "1. Build Graphene:" now.
___
*[Documentation/quickstart.rst, line 61 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVMN0g4Eid7N--Hw4s:-MiVMN0g4Eid7N--Hw4t:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Documentation/quickstart.rst#L61)):*
> ```reStructuredText
> 
> .. NOTE if you're about to sort the apt-get invocation below, see note in
>    building.rst
> ```

ditto
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 46 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVMmig21KFiRa7n2D5:-MiVMmig21KFiRa7n2D6:b-tn4v6q) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/client.manifest.template#L46)):*
> ```
> 
> {% if env.GRAPHENE_LIBRARY_PATH -%}
> {% for path in env.GRAPHENE_LIBRARY_PATH.split(':') if path -%}
> ```

Do we need to actually support multiple paths in this variable? This boilerplate is quite big and complicated, I don't want to require users to copy-paste it to all their manifests.
___
*[Examples/ra-tls-mbedtls/Makefile, line 63 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVNTPx4uqyEgwQqJCy:-MiVNTPx4uqyEgwQqJCz:boozykm) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/Makefile#L63)):*
> ```Makefile
> ######################### CLIENT/SERVER EXECUTABLES ###########################
> 
> CFLAGS += -I./mbedtls/include
> ```

I don't think this change is correct, we should use the installed headers (they may contain autogenerated code/declarations which depend on the build config, e.g. the list of available ciphers).
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 7 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVNukp1DGnqJKlWyA_:-MiVNukp1DGnqJKlWyAa:b-nxjzld) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/server.manifest.template#L7)):*
> ```
> loader.log_level = "{{ log_level }}"
> 
> loader.env.LD_LIBRARY_PATH = "{% if env.GRAPHENE_LIBRARY_PATH %}{{ env.GRAPHENE_LIBRARY_PATH }}:{% endif -%}
> ```

Waaait... Does `GRAPHENE_LIBRARY_PATH` contain host paths or in-Graphene paths?
___
*[Pal/src/host/Linux-SGX/Makefile, line 173 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVfgzk0QNufjD7VAZN:-MiVfgzk0QNufjD7VAZO:bslwwra) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/Makefile#L173)):*
> ```Makefile
> 
> .PHONY: clean
> clean: clean_
> ```

You need to either put a semicolon at the end or add a no-op command (e.g. `@:`), otherwise this is _not_ a recipe but only a dependency specification.
___
*[Pal/src/host/Linux-SGX/Makefile, line 176 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVgV3P4PPg8XkJIYir:-MiVgV3P4PPg8XkJIYis:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/Makefile#L176)):*
> ```Makefile
> 
> .PHONY: distclean
> distclean: clean_
> ```

ditto
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 20 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVhQ9UE9JJDvkp3um3:-MiVhQ9UE9JJDvkp3um4:bt9auk7) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/tools/common/attestation.c#L20)):*
> ```C
> 
> #ifdef HAVE_INTERNAL_CJSON
> /* here we -I the cJSON's repo root, which directly contain the header */
> ```

`contain` -> `contains`
___
*[Pal/src/host/Linux-SGX/tools/ias-request/meson.build, line 9 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRTh5w1jc8hYxrWZC8:-MiVikQAEv9yCTKSaWwc:b-izsie6) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/tools/ias-request/meson.build#L9)):*
> Do we want to install this?

I think so, it's mainly a tool for our users to debug setup issues.
___
*[Pal/src/host/Linux-SGX/tools/quote-dump/meson.build, line 9 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRU2n9BULyXYXnyruw:-MiVjK0u48QGe9OG9jVx:bnet2ri) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/tools/quote-dump/meson.build#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Do we want to install this? We don't use it AFAIK.
</blockquote></details>

ditto, please install
___
*[Pal/src/host/Linux-SGX/tools/verify-ias-report/meson.build, line 9 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiW6H6d6u5wgSvjSUyK:-MiW6H6d6u5wgSvjSUyL:bqf8qbs) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/tools/verify-ias-report/meson.build#L9)):*
> ```Meson
>     ],
> 
>     install: false,
> ```

This should also be installed.
___
*[subprojects/packagefiles/m [...]

2021-09-01 13:24 UTC, pwmarcz reviewed
> Reviewed 2 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhHdg4q0KoJyuF4jn:-MiWWrjD9EaHlM7A-e7C:b-sauaos) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I also don't like using `LD_LIBRARY_PATH`, it's quite hacky and things may blow up in weird ways in the future because of this.

Could we use `-Wl,-rpath`, but only if `--prefix` is non-standard? (e.g. if it was provided in the cmdline?) The binaries built are by-design tied to specific compilation flags, so it should be completely fine to build them for a specific installation prefix.
</blockquote></details>

Sounds reasonable to me, and will make running the command-line tools easier to the user.


<!-- Sent from Reviewable.io -->

2021-09-01 13:55 UTC, woju commented
@anjalirai-intel Thanks for verifying!

With meson, builds are out-of-tree, which means that no build artifacts will be found in source tree, ever. Instead, everything  will be in build directory (whatever you specify to `meson setup`, in CI it's simply `build/`). So if you named it `build/`, you can find it under `build/Pal/src/host/Linux-SGX/tools/is_sgx_available`. There's a caveat though: when installing, meson changes the binaries slightly, at least it removes temporary rpaths, which are included in binaries while they sit in builddir, and only `install_rpath`s are preserved. So please use and verify only binaries *after install*.





<!-- Sent from Reviewable.io -->

2021-09-02 16:54 UTC, woju commented
___
*[.ci/lib/stage-build-sgx.jenkinsfile, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhXhHdg4q0KoJyuF4jn:-Mib0vr91KZKj2N7i6ti:b-jpcrv3) ([raw file](https://github.com/oscarlab/graphene/blob/dba514b5e66fa6d0870636d58ff146318e5b9feb/.ci/lib/stage-build-sgx.jenkinsfile#L48)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Sounds reasonable to me, and will make running the command-line tools easier to the user.
</blockquote></details>

1) We don't have a way to see if `--prefix` was specified in cmdline, and if there was, this would be wrong, because we change `--prefix=/usr` in release builds (deb). And I don't want this rpath in release builds.
2) It doesn't make running command-line tools any easier, they already run fine.

It will blow only if something overrides this LD_LIBRARY_PATH, but I don't think this would happen.


<!-- Sent from Reviewable.io -->

2021-09-03 03:46 UTC, jinengandhi-intel reviewed
Thanks for the clarification.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645#-:-MidksbT10j7lhE0IP_s:b-uv4ta)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2021-09-03 14:08 UTC, pwmarcz requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 60 of 79 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MifymuR9eQqbBVlJECL:-MifymuR9eQqbBVlJECM:b2v0xyj) (no related file):*
The new build (SGX + debug + clang) actually breaks for another reason:

```
clang++ -IPal/src/host/Linux-SGX/tools/is-sgx-available/is-sgx-available.p -IPal/src/host/Linux-SGX/tools/is-sgx-available -I../Pal/src/host/Linux-SGX/tools/is-sgx-available -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Werror -std=c++14 -g -masm=intel -Wno-multichar -MD -MQ Pal/src/host/Linux-SGX/tools/is-sgx-available/is-sgx-available.p/is_sgx_available.cpp.o -MF Pal/src/host/Linux-SGX/tools/is-sgx-available/is-sgx-available.p/is_sgx_available.cpp.o.d -o Pal/src/host/Linux-SGX/tools/is-sgx-available/is-sgx-available.p/is_sgx_available.cpp.o -c ../Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp
../Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp:45:10: error: unexpected token in argument list
        "xor qword ptr [rsp], (1<<21)\n"
         ^
<inline asm>:3:11: note: instantiated into assembly here
xor qword ptr [rsp], (1<<21)
          ^
1 error generated.
```

Does clang not support something like `(1<<21)`? I guess we could rewrite it as hex.

But why did it work before? Did we have `gcc` hardcoded instead of `$(CC)` somewhere?

---


<!-- Sent from Reviewable.io -->

2021-09-03 14:09 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 60 of 79 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[-- commits, line 3 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVFc102BD4RXC2A1lP):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`meson` -> `Meson`
`sgx` -> `SGX`
</blockquote></details>

Done.
___
*[-- commits, line 10 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVFuC36WuSNRUh2pCx):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[meson.build, line 20 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRGUTg5QOu8QLNwX-O:-MiaUkicCoorlSggcQpd:b-80tlqk) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/meson.build#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we remove them in this PR?
</blockquote></details>

Sure.
___
*[meson.build, line 105 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiRHL4M9nv_qY08Fmev:-MiaVdxr14wLTEGbTdko:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/meson.build#L105)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yep, this is misleading. I'll fix this.
</blockquote></details>

Done.
___
*[.ci/lib/stage-clean-check.jenkinsfile, line 43 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVJcLc4w2-u6T30WIm:-MibQfkb7YqnWNvG0SrW:b-r81538) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/.ci/lib/stage-clean-check.jenkinsfile#L43)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> on Ubuntu 18.04, git clean -Xf fails
> ```

why and how?
</blockquote></details>

IIRC it fails to remove the packagecache directory itself.
___
*[Documentation/building.rst, line 48 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVK9JW9G2k1pS-R7YE:-MibR9bc8vYAqeMPbWv2:b-j9dahe) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Documentation/building.rst#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> so
> ```

This connects the sentences in a weird way logically. The intended meaning is _because we require >= 0.55, you need at least Debian 11/[...] to install from apt instead of pip_.
</blockquote></details>

Yes, but then the excerpt "you need at least Debian 11" (without context) is false. I don't want to put that in writing.
___
*[Documentation/quickstart.rst, line 14 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVM8XS-O5P8y2sV1pz:-MibShR7BIo9BRQGF7C-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Documentation/quickstart.rst#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Seems this broke the numbering, it displays "1. Build Graphene:" now.
</blockquote></details>

Done.
___
*[Documentation/quickstart.rst, line 61 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVMN0g4Eid7N--Hw4s:-MibTEqZ5-AxT6ctP-F3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Documentation/quickstart.rst#L61)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 46 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVMmig21KFiRa7n2D5:-MibTPLk8_rJSU5bKlMN:b-k2dq0g) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/client.manifest.template#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do we need to actually support multiple paths in this variable? This boilerplate is quite big and complicated, I don't want to require users to copy-paste it to all their manifests.
</blockquote></details>

We can think about shipping a library of such boilerplate:

```jinja
{% import 'lib.manifest.jinja' as lib -%}

{# ... #}

{{ lib.add_sgx_trusted_files_and_fs_mounts_from_colon_separated_variable(env.GRAPHENE_LIBRARY_PATH) }}
```

(I could use a suggestion for shorter macro name).
___
*[Examples/ra-tls-mbedtls/Makefile, line 63 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVNTPx4uqyEgwQqJCy:-MibUco76jwR4WRLGwbX:b-jzt8um) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/Makefile#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't think this change is correct, we should use the installed headers (they may contain autogenerated code/declarations which depend on the build config, e.g. the list of available ciphers).
</blockquote></details>

It's no worse that what was previously, and mbedtls just copies all the headers intact. The only change happens with `./scripts/config.pl`, which `sed`s the config file. So this works. The ultimately correct way would be to install the headers themselves together with whole graphene, but I didn't though this through, so I'm not doing it now.
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 7 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVNukp1DGnqJKlWyA_:-MibVtEfBVZmTA1uEYr-:b-urz0r2) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/server.manifest.template#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Waaait... Does `GRAPHENE_LIBRARY_PATH` contain host paths or in-Graphene paths?
</blockquote></details>

I think they're mounted 1:1, as they should be, so both. I don't think we support remapping, nor we should.
___
*[Pal/src/host/Linux-SGX/Makefile, line 173 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVfgzk0QNufjD7VAZN:-MicY21BAT9P5FZTsdB3:b-bi1rfj) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/Makefile#L173)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You need to either put a semicolon at the end or add a no-op command (e.g. `@:`), otherwise this is _not_ a recipe but only a dependency specification.
</blockquote></details>

Fixed according to @boryspoplawski's suggestion.
___
*[Pal/src/host/Linux-SGX/Makefile, line 176 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVgV3P4PPg8XkJIYir:-MicY1iO8aV_CWlF5Tkd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/Makefile#L176)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/common/attestation.c, line 20 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVhQ9UE9JJDvkp3um3:-MibWZY9Dl0C99Lhb_LR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Pal/src/host/Linux-SGX/tools/common/attestation.c#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`contain` -> `contains`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/ias-request/meson.build, line 9 at r12](https://reviewable.io/reviews/osca [...]

2021-09-03 14:11 UTC, pwmarcz requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 60 of 79 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MifymuR9eQqbBVlJECL:-Mifzfvp1-AI6WMhKGm3:blryykm) (no related file):*
>Does clang not support something like (1<<21)? I guess we could rewrite it as hex.

Oh, probably clang expects GAS syntax instead of Intel, and you need to rewrite it to GAS (or set a command-line option to use Intel syntax).

---


<!-- Sent from Reviewable.io -->

2021-09-03 14:13 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 60 of 79 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MifymuR9eQqbBVlJECL:-Mig-OCn4v9s_G7T08Wq:bikkb9r) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>Does clang not support something like (1<<21)? I guess we could rewrite it as hex.

Oh, probably clang expects GAS syntax instead of Intel, and you need to rewrite it to GAS (or set a command-line option to use Intel syntax).
</blockquote></details>

Please set the cmdline option ;) We should be migrating to the acceptable x86 asm syntax ;)

---


<!-- Sent from Reviewable.io -->

2021-09-03 15:23 UTC, mkow requested changes
> Reviewed 19 of 19 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @pwmarcz, and @woju)

___
*[-- commits, line 10 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVFuC36WuSNRUh2pCx):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done (you updated only the fixup commit, but its message will be dropped on rebase)
___
*[.ci/lib/stage-clean-check.jenkinsfile, line 43 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVJcLc4w2-u6T30WIm:-Mig8VtX3_tcHGaxp_pl:bwboajj) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/.ci/lib/stage-clean-check.jenkinsfile#L43)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

IIRC it fails to remove the packagecache directory itself.
</blockquote></details>

Then please say this is the comment ;)
___
*[Documentation/building.rst, line 48 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVK9JW9G2k1pS-R7YE:-Mig8r92-zeZvEj58Krd:b-6tnsuk) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Documentation/building.rst#L48)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, but then the excerpt "you need at least Debian 11" (without context) is false. I don't want to put that in writing.
</blockquote></details>

But this is in the middle of the sentence, so you can't read it without the context?
___
*[Documentation/quickstart.rst, line 61 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVMN0g4Eid7N--Hw4s:-Mig9qq7EGbBFxTMEyo1:bfhqml6) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Documentation/quickstart.rst#L61)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 46 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVMmig21KFiRa7n2D5:-MigA7Gs4KjUBNIQ0vl1:bjo278f) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/client.manifest.template#L46)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

We can think about shipping a library of such boilerplate:

```jinja
{% import 'lib.manifest.jinja' as lib -%}

{# ... #}

{{ lib.add_sgx_trusted_files_and_fs_mounts_from_colon_separated_variable(env.GRAPHENE_LIBRARY_PATH) }}
```

(I could use a suggestion for shorter macro name).
</blockquote></details>

Wouldn't it be easier to just not allow multiple paths in `GRAPHENE_LIBRARY_PATH`? Is there any case where you'd want to insert multiple paths there?

@boryspoplawski, @pwmarcz, @dimakuv: What do you think about this?
___
*[Examples/ra-tls-mbedtls/Makefile, line 63 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVNTPx4uqyEgwQqJCy:-MigBQXd8qfnQEOkCFcK:b-xdve3f) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/Makefile#L63)):*
> It's no worse that what was previously

Why? Previously we correctly used the installed headers (`-I./mbedtls/install/include`), and now we use the ones directly from the source?

> The only change happens with `./scripts/config.pl`, which `sed`s the config file. So this works.

That looks like a risky assumption (that we manually verified that the current version seem to not touch the headers outside of `config.pl`).
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 7 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVNukp1DGnqJKlWyA_:-MigCOpW7GiEOO5eMx-w:b-zcm58j) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/server.manifest.template#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I think they're mounted 1:1, as they should be, so both. I don't think we support remapping, nor we should.
</blockquote></details>

We support and it's a completely valid and reasonable case.
In good setups you would create some "workdir" where you prepare the environment for the enclave, download/put there all the dependencies and then mount them inside the enclave (so, you'd e.g. have mappings like `my_project/workdir/usr` -> `/usr`). Mounting 1-1 from the host is a hack which we do just to simplify the examples and it only really makes sense in Docker, where you control the outer world very precisely. In all other cases a mere `apt update` on the host will break the shipped enclaves.
___
*[Examples/ra-tls-secret-prov/Makefile, line 41 at r13](https://reviewable.io/reviews/oscarlab/graphene/2645#-MigDTNZ18Ve1x4NZu7_:-MigDTNZ18Ve1x4NZu7a:b-m57pzd) ([raw file](https://github.com/oscarlab/graphene/blob/71cd5eeef7b052405cc82dddf3912076a8190ad8/Examples/ra-tls-secret-prov/Makefile#L41)):*
> ```Makefile
> 
> CFLAGS += -Wall -std=c11 -I$(GRAPHENEDIR)/Pal/src/host/Linux-SGX/tools/ra-tls \
> 		  $(shell pkg-config --cflags mbedtls_graphene)
> ```

please don't mix tabs and spaces when aligning code


<!-- Sent from Reviewable.io -->

2021-09-06 09:06 UTC, dimakuv requested changes
> Reviewed 19 of 19 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @woju)

___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 46 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVMmig21KFiRa7n2D5:-MiuHaoy7LyUlqeKmYoA:b-kyi8j8) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/client.manifest.template#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wouldn't it be easier to just not allow multiple paths in `GRAPHENE_LIBRARY_PATH`? Is there any case where you'd want to insert multiple paths there?

@boryspoplawski, @pwmarcz, @dimakuv: What do you think about this?
</blockquote></details>

I agree with @mkow -- why would we ever have two directories specified in `GRAPHENE_LIBRARY_PATH`? Let's disallow multiple paths in this envvar and simplify our manifests. But I see that @boryspoplawski asked for this, so let's see what he says.
___
*[Examples/ra-tls-mbedtls/Makefile, line 63 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVNTPx4uqyEgwQqJCy:-MiuIsOV0QnhOe-CKY24:behkgez) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/Makefile#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> It's no worse that what was previously

Why? Previously we correctly used the installed headers (`-I./mbedtls/install/include`), and now we use the ones directly from the source?

> The only change happens with `./scripts/config.pl`, which `sed`s the config file. So this works.

That looks like a risky assumption (that we manually verified that the current version seem to not touch the headers outside of `config.pl`).
</blockquote></details>

So the sole point of downloading mbedTLS here is to get the copy of mbedTLS header files (inside `./mbedtls/include`)?

Can't we install the headers together with `mbedtls_graphene` and remove the whole "download mbedTLS" logic from this Makefile?
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 7 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVNukp1DGnqJKlWyA_:-MiuJehR-bUQq9Odk7vt:b2kv7v) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/server.manifest.template#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We support and it's a completely valid and reasonable case.
In good setups you would create some "workdir" where you prepare the environment for the enclave, download/put there all the dependencies and then mount them inside the enclave (so, you'd e.g. have mappings like `my_project/workdir/usr` -> `/usr`). Mounting 1-1 from the host is a hack which we do just to simplify the examples and it only really makes sense in Docker, where you control the outer world very precisely. In all other cases a mere `apt update` on the host will break the shipped enclaves.
</blockquote></details>

@mkow is right about the remapping -- it is totally valid and in fact should be the preferred way of writing manifests.

But why are we discussing it here? In this particular manifest template, `GRAPHENE_LIBRARY_PATH` is mapped 1:1, so everything is ok. If someone wants to remap host-level `GRAPHENE_LIBRARY_PATH` inside Graphene, then she will also change the below logic of `fs.mount` and use some hard-coded in-Graphene path in this line.
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 8 at r13](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiuKEHU51db0T2sEW1S:-MiuKEHU51db0T2sEW1T:b1w5css) ([raw file](https://github.com/oscarlab/graphene/blob/71cd5eeef7b052405cc82dddf3912076a8190ad8/Examples/ra-tls-mbedtls/server.manifest.template#L8)):*
> ```
> 
> loader.env.LD_LIBRARY_PATH = "{% if env.GRAPHENE_LIBRARY_PATH %}{{ env.GRAPHENE_LIBRARY_PATH }}:{% endif -%}
>     /lib:/lib/x86_64-linux-gnu:/libs"
> ```

Why do we still have `/libs` here?


<!-- Sent from Reviewable.io -->

2021-09-06 09:56 UTC, pwmarcz reviewed
> Reviewed 1 of 3 files at r12, 19 of 19 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @woju)

___
*[Documentation/building.rst, line 48 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVK9JW9G2k1pS-R7YE:-MiuWO_TAaAl9YeiwFKk:bwh0a4z) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Documentation/building.rst#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But this is in the middle of the sentence, so you can't read it without the context?
</blockquote></details>

This looked weird to me too. How about something like "you can also install Meson from apt instead of pip, but only if your distro is new enough to have Meson >= 0.55 (Debian 11, Ubuntu 20.10)."


<!-- Sent from Reviewable.io -->

2021-09-06 14:01 UTC, boryspoplawski requested changes
> Reviewed 15 of 19 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @woju)

___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 46 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVMmig21KFiRa7n2D5:-Miga2eR7v5Te3xY5VqR:b-uzer7r) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/client.manifest.template#L46)):*
Yeah, I think that we only want one path here. (sorry, forgot to publish the comment 2 days ago...)

> But I see that @boryspoplawski asked for this, so let's see what he says.

@dimakuv Where did I ask for it?


<!-- Sent from Reviewable.io -->

2021-09-06 16:35 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 73 of 80 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MifymuR9eQqbBVlJECL:-MivlKcp8Mo6xdoonkw2:b-jm5bbp) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please set the cmdline option ;) We should be migrating to the acceptable x86 asm syntax ;)
</blockquote></details>

But it's there isn't it? `-masm=intel`, or it's something other for clang++?

---
___
*[-- commits, line 10 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVFuC36WuSNRUh2pCx):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done (you updated only the fixup commit, but its message will be dropped on rebase)
</blockquote></details>

Done.
___
*[.ci/lib/stage-clean-check.jenkinsfile, line 43 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVJcLc4w2-u6T30WIm:-MivmQ6M7CAXb8kzW2f_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/.ci/lib/stage-clean-check.jenkinsfile#L43)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then please say this is the comment ;)
</blockquote></details>

Done.
___
*[Documentation/building.rst, line 48 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVK9JW9G2k1pS-R7YE:-Mivmuqh0RBmGRMmNeNL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Documentation/building.rst#L48)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This looked weird to me too. How about something like "you can also install Meson from apt instead of pip, but only if your distro is new enough to have Meson >= 0.55 (Debian 11, Ubuntu 20.10)."
</blockquote></details>

Done.
___
*[Documentation/quickstart.rst, line 61 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVMN0g4Eid7N--Hw4s:-MiuBQZX4YJLvGcFFVLa:b-gdzlnb) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Documentation/quickstart.rst#L61)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

This was a failure at rebasing.
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 46 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVMmig21KFiRa7n2D5:-MiuBe239XVmrtU9sTiF:b-94ulwa) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/client.manifest.template#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, I think that we only want one path here. (sorry, forgot to publish the comment 2 days ago...)

> But I see that @boryspoplawski asked for this, so let's see what he says.

@dimakuv Where did I ask for it?
</blockquote></details>

It won't be easier by any significant measure.

As long as LD_LIBRARY_PATH accepts multiple paths, this is likely required. For example `meson devenv` mentioned before populates LD_LIBRARY_PATH with all directories in builddir, which contain anything resembling a library (likely more than 2). In that case we'll have those libraries spread over multiple directories.

Also it's customary to have unlimited number of directories in the variable -- that's how every single \*_PATH variable works, apart from PYTHONHOME (not to be confused with PYTHONPATH) which is spooky (it accepts up to two paths, and the treatment is different for the first and second one). We would be creating another strange thing, which would seem alien to anyone configuring `$*_PATH`s.
___
*[Examples/ra-tls-mbedtls/Makefile, line 63 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVNTPx4uqyEgwQqJCy:-MiuDUm--vcsmCiDEAPH:bngimfz) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/Makefile#L63)):*
> Why?

Because there's nothing magic in installation, it's just recursive copy. In any case this is done after configuration.

> Can't we install the headers together with mbedtls_graphene and remove the whole "download mbedTLS" logic from this Makefile?

Yes, we technically can. No, it won't cause this PR to be merged before feature freeze.
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 8 at r13](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiuKEHU51db0T2sEW1S:-MiuQhof3--VoaQdPzbd:bow5oep) ([raw file](https://github.com/oscarlab/graphene/blob/71cd5eeef7b052405cc82dddf3912076a8190ad8/Examples/ra-tls-mbedtls/server.manifest.template#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we still have `/libs` here?
</blockquote></details>

IDK, it was there, I didn't touch it. Probably copied from other manifests.
___
*[Examples/ra-tls-secret-prov/Makefile, line 41 at r13](https://reviewable.io/reviews/oscarlab/graphene/2645#-MigDTNZ18Ve1x4NZu7_:-MivxOgs0EScDxBPwoI6:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/71cd5eeef7b052405cc82dddf3912076a8190ad8/Examples/ra-tls-secret-prov/Makefile#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please don't mix tabs and spaces when aligning code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-06 17:04 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: 73 of 80 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYVu5IDdrhGt9mqTtC:-Miw2JgK6VUWv1Ve5JMc:blkpkzh) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Kind of: #2631 introduces problems with definitions (`pid_t` etc.) I fixed them before trying to compile this branch (with the change I mentioned in #2631) and I still get the linking issue. It looks unrelated.
</blockquote></details>

I reproduced it, and I think <code>undefined reference to \`_log'</code> is because of our `common/include/assert.h`, which on else does `log_always()`. `log_always` is defined as `_log()` in `log.h`. Now if we're `IN_PAL` or `IN_SHIM`, then `_log` is defined to `pal_log` or `shim_log` resp. in `callbacks.h`, but we're not in either. What should we do now?

---


<!-- Sent from Reviewable.io -->

2021-09-07 08:11 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r14, 10 of 10 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYVu5IDdrhGt9mqTtC:-MizBD_76Hqp3ykbcbHO:b-gvmsmn) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I reproduced it, and I think <code>undefined reference to \`_log'</code> is because of our `common/include/assert.h`, which on else does `log_always()`. `log_always` is defined as `_log()` in `log.h`. Now if we're `IN_PAL` or `IN_SHIM`, then `_log` is defined to `pal_log` or `shim_log` resp. in `callbacks.h`, but we're not in either. What should we do now?
</blockquote></details>

If the linking breaks on utilities, then we should define `_log` and `abort` callbacks. Just like we do it here: https://github.com/oscarlab/graphene/blob/af2f7809b36945382a535f95c2af7a2b32a2059a/Pal/regression/utils.c#L30

I guess these callbacks should be located in `sgx_utils.so`, so we should put them into https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/tools/common/util.c

---
___
*[.ci/lib/stage-clean-check.jenkinsfile, line 43 at r15](https://reviewable.io/reviews/oscarlab/graphene/2645#-MizC0S-3o9yvWYZ32Ss:-MizC0S-3o9yvWYZ32St:b-2u4idu) ([raw file](https://github.com/oscarlab/graphene/blob/449288aaab7e86ff87f7a6701ae17b6b0d777ede/.ci/lib/stage-clean-check.jenkinsfile#L43)):*
> ```
>         rm -rf python/graphenelibos/__pycache__
> 
>         # on Ubuntu 18.04, git clean -Xf fails to remove packagecache directory itselg
> ```

`itself`
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 46 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVMmig21KFiRa7n2D5:-MizCfl_9eiPDjmmIle3:b-7pw7av) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/client.manifest.template#L46)):*
> @dimakuv Where did I ask for it?

Sorry, this was @pwmarcz. See the resolved comment below in this file.

> As long as LD_LIBRARY_PATH accepts multiple paths, this is likely required. For example meson devenv mentioned before populates LD_LIBRARY_PATH with all directories in builddir, which contain anything resembling a library (likely more than 2). In that case we'll have those libraries spread over multiple directories.

Ok, fair enough. I can imagine that we'll have some Graphene helper libraries that will reside in a couple directories (e.g., `$WORKSPACE/usr/lib/x86_64-linux-gnu` and `$WORKSPACE/usr/lib/common`).
___
*[Examples/ra-tls-mbedtls/Makefile, line 63 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVNTPx4uqyEgwQqJCy:-MizDcAR-_5faMjx17u8:b5bxjq0) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/Makefile#L63)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> Why?

Because there's nothing magic in installation, it's just recursive copy. In any case this is done after configuration.

> Can't we install the headers together with mbedtls_graphene and remove the whole "download mbedTLS" logic from this Makefile?

Yes, we technically can. No, it won't cause this PR to be merged before feature freeze.
</blockquote></details>

OK, resolving, not important anyway.
___
*[Examples/ra-tls-mbedtls/Makefile, line 32 at r15](https://reviewable.io/reviews/oscarlab/graphene/2645#-MizIj0z4CeqtQyiBcxw:-MizIj0z4CeqtQyiBcxx:b95qjfr) ([raw file](https://github.com/oscarlab/graphene/blob/449288aaab7e86ff87f7a6701ae17b6b0d777ede/Examples/ra-tls-mbedtls/Makefile#L32)):*
> ```Makefile
> dcap: client_dcap.manifest.sgx client_dcap.sig client_dcap.token
> 
> ############################# MBEDTLS DEPENDENCY ##############################
> ```

Actually, could you add a comment that this mbedTLS download is purely to get the `./mbedtls/include` headers? And that the mbedTLS libraries are taken from the Graphene package.
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 8 at r13](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiuKEHU51db0T2sEW1S:-MizDonX6SszfOSOyRpm:be7bof) ([raw file](https://github.com/oscarlab/graphene/blob/71cd5eeef7b052405cc82dddf3912076a8190ad8/Examples/ra-tls-mbedtls/server.manifest.template#L8)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

IDK, it was there, I didn't touch it. Probably copied from other manifests.
</blockquote></details>

But you removed `/libs` in `client.manifest.template`, it is inconsistent.


<!-- Sent from Reviewable.io -->

2021-09-07 10:07 UTC, pwmarcz requested changes
> Reviewed 7 of 7 files at r14, 10 of 10 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MhYVu5IDdrhGt9mqTtC:-Mizh9QM7FiAxZzDk9nw:bi7w8s5) (no related file):*
>I reproduced it, and I think undefined reference to `_log' is because of our common/include/assert.h, which on else does log_always().

There are also the fortified versions of some functions (like `__memcpy_chk`, IIRC); the compiler might use them in some circumstances (and that actually happens in _release_ builds, i.e. with optimizations enabled).

Which is to say, please define them unconditionally (without `#ifdef DEBUG`), so that things don't break in the future.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MifymuR9eQqbBVlJECL:-MizhYBq9uL_cFBFTLbY:b-8sigfy) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

But it's there isn't it? `-masm=intel`, or it's something other for clang++?
</blockquote></details>

[Should be the same](https://stackoverflow.com/questions/10990018/how-to-generate-assembly-code-with-clang-in-intel-syntax). Clang usually follows GCC features (but sometimes doesn't bother to document them...)

---


<!-- Sent from Reviewable.io -->

2021-09-07 12:10 UTC, mkow requested changes
> Reviewed 7 of 7 files at r14, 10 of 10 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MifymuR9eQqbBVlJECL:-Mj-6pgNBLJvbspO8eY9:b-dir5rx) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

[Should be the same](https://stackoverflow.com/questions/10990018/how-to-generate-assembly-code-with-clang-in-intel-syntax). Clang usually follows GCC features (but sometimes doesn't bother to document them...)
</blockquote></details>

FYI: I checked that the most recent clang also doesn't work. I played a bit with this and it seems that `-masm=intel` is just broken in Clang :(
Could we hardcode GCC for this one file for now and add a TODO? We can figure out how to fix this later.

---
___
*[Documentation/building.rst, line 48 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVK9JW9G2k1pS-R7YE:-MizxNOiB8X594oAwxbm:bgtl7x9) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Documentation/building.rst#L48)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@pwmarcz: I like your version!
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 46 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVMmig21KFiRa7n2D5:-Mj--uvH2KcQmF1GP8tq:b-jzpsv7) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/client.manifest.template#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> @dimakuv Where did I ask for it?

Sorry, this was @pwmarcz. See the resolved comment below in this file.

> As long as LD_LIBRARY_PATH accepts multiple paths, this is likely required. For example meson devenv mentioned before populates LD_LIBRARY_PATH with all directories in builddir, which contain anything resembling a library (likely more than 2). In that case we'll have those libraries spread over multiple directories.

Ok, fair enough. I can imagine that we'll have some Graphene helper libraries that will reside in a couple directories (e.g., `$WORKSPACE/usr/lib/x86_64-linux-gnu` and `$WORKSPACE/usr/lib/common`).
</blockquote></details>

I'd just install all Graphene .so-s in one place, we don't have 50 of them to justify spreading them through a bunch of directories. And this snippet is quite a big boilerplate which will be hard to manage (people will be copying it literally to their manifests, then we'll change something here, but they will still have the old version, etc).
___
*[Examples/ra-tls-mbedtls/Makefile, line 63 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVNTPx4uqyEgwQqJCy:-Mizz7wW3t6MbQ7s0nvK:bafg426) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/Makefile#L63)):*
> Because there's nothing magic in installation, it's just recursive copy. In any case this is done after configuration.

The headers may get generated/altered in any of configuring/building/installing step, we can't assume what mbedtls does internally (and this may change between versions).

Please at least add a comment that this is a temporary hack and we are using wrong headers now, but should be gone when mbedtls upstreams the CMAC-enabled-by-default change.
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 7 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVNukp1DGnqJKlWyA_:-Mj--Ml24LPBTPyVwyuJ:b-3j01gr) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/server.manifest.template#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow is right about the remapping -- it is totally valid and in fact should be the preferred way of writing manifests.

But why are we discussing it here? In this particular manifest template, `GRAPHENE_LIBRARY_PATH` is mapped 1:1, so everything is ok. If someone wants to remap host-level `GRAPHENE_LIBRARY_PATH` inside Graphene, then she will also change the below logic of `fs.mount` and use some hard-coded in-Graphene path in this line.
</blockquote></details>

The problem is that `GRAPHENE_LIBRARY_PATH` by design assumes 1-1 mapping. In "If someone wants to remap" - how would you do this remapping? You can't assume the contents of `GRAPHENE_LIBRARY_PATH`, and it lists only some host paths. This could be feasible only if `GRAPHENE_LIBRARY_PATH` was just a single path (which I think is what we should do).


<!-- Sent from Reviewable.io -->

2021-09-07 13:37 UTC, pwmarcz requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MifymuR9eQqbBVlJECL:-Mj-RehA6U8gd4SNnPng:brxp9sq) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: I checked that the most recent clang also doesn't work. I played a bit with this and it seems that `-masm=intel` is just broken in Clang :(
Could we hardcode GCC for this one file for now and add a TODO? We can figure out how to fix this later.
</blockquote></details>

Sounds good.

---
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 46 at r12](https://reviewable.io/reviews/oscarlab/graphene/2645#-MiVMmig21KFiRa7n2D5:-Mj-Rt3BBQtxfd0RDCWp:bklbmjv) ([raw file](https://github.com/oscarlab/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/client.manifest.template#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd just install all Graphene .so-s in one place, we don't have 50 of them to justify spreading them through a bunch of directories. And this snippet is quite a big boilerplate which will be hard to manage (people will be copying it literally to their manifests, then we'll change something here, but they will still have the old version, etc).
</blockquote></details>

To be honest I'm still not sure why we need this. From what I understand, currently this is to make `sgx_util.so` and/or mbedtls libraries available inside Graphene, and we require the user to pass a special path (`GRAPHENE_LIBRARY_PATH`) to tell Graphene where they are installed.

However, we also make Graphene's patched glibc available, and in that case Graphene knows perfectly well where they're installed, and we can use just `{{ graphene.runtimedir() }}`.

We also make Graphene's mbedtls available, and Graphene _also_ knows where it is: we use `{{ graphene.pkglibdir }}/mbedtls` (line 29 in this file).

Why, then, in this case do we require an extra user-controlled variable, instead of using something like `{{ graphene.libdir }}`? It is my understanding that in all of these cases, we deal with libraries installed by Graphene.


<!-- Sent from Reviewable.io -->

2021-09-07 13:38 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2645)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2645#-MifymuR9eQqbBVlJECL:-Mj-TfdBCFLS4ig6RsX4:b-k3pl88) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

FYI: https://bugs.llvm.org/show_bug.cgi?id=20241#c4

---


<!-- Sent from Reviewable.io -->

2021-09-13 15:00 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2645)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2645#-MhYVu5IDdrhGt9mqTtC:-MjUWfCV4YuocNcjtIoK:b-896fix) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>I reproduced it, and I think undefined reference to `_log' is because of our common/include/assert.h, which on else does log_always().

There are also the fortified versions of some functions (like `__memcpy_chk`, IIRC); the compiler might use them in some circumstances (and that actually happens in _release_ builds, i.e. with optimizations enabled).

Which is to say, please define them unconditionally (without `#ifdef DEBUG`), so that things don't break in the future.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2645#-MifymuR9eQqbBVlJECL:-MjUWhuYEMlzFdbH7IwY:b-9rwd92) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: https://bugs.llvm.org/show_bug.cgi?id=20241#c4
</blockquote></details>

We can't hardcode GCC in meson, anyone configuring build can select a compiler. We can just skip this file if compiler for C++ is not `g++` (and in CI always use `g++`).

---
___
*[.ci/lib/stage-clean-check.jenkinsfile, line 43 at r15](https://reviewable.io/reviews/gramineproject/graphene/2645#-MizC0S-3o9yvWYZ32Ss:-MjUdDp34eqTee3jeHeh:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/449288aaab7e86ff87f7a6701ae17b6b0d777ede/.ci/lib/stage-clean-check.jenkinsfile#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`itself`
</blockquote></details>

Done.
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 46 at r12](https://reviewable.io/reviews/gramineproject/graphene/2645#-MiVMmig21KFiRa7n2D5:-MjUGK2P0rGhCq_YEkZP:b-e5ztua) ([raw file](https://github.com/gramineproject/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/client.manifest.template#L46)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

To be honest I'm still not sure why we need this. From what I understand, currently this is to make `sgx_util.so` and/or mbedtls libraries available inside Graphene, and we require the user to pass a special path (`GRAPHENE_LIBRARY_PATH`) to tell Graphene where they are installed.

However, we also make Graphene's patched glibc available, and in that case Graphene knows perfectly well where they're installed, and we can use just `{{ graphene.runtimedir() }}`.

We also make Graphene's mbedtls available, and Graphene _also_ knows where it is: we use `{{ graphene.pkglibdir }}/mbedtls` (line 29 in this file).

Why, then, in this case do we require an extra user-controlled variable, instead of using something like `{{ graphene.libdir }}`? It is my understanding that in all of these cases, we deal with libraries installed by Graphene.
</blockquote></details>

These are two different things. `GRAPHENE_LIBRARY_PATH` is because in CI we don't install into `/usr` nor `/usr/local`, but somewhere arbitrary. So if we install elsewhere, we also need some other directory for libraries in addition to `/usr/lib`. This holds for every single thingy installed outside of `/usr`, not only built using our buildsystem. So long-term we need something like this for adding multiple directories to libs ad-hoc.

WRT mbedtls, previously it had to be separated from `/usr` in any case (even if `--prefix=/usr`), because soname clashed with mbedtls from distro, and wasn't possible to be merged with patched glibc, because you can't use patched glibc on normal Linux, but you can use our patched mbedtls and there are use cases for this (PF). Now that I changed soname, the separation is not needed anymore.
___
*[Examples/ra-tls-mbedtls/Makefile, line 63 at r12](https://reviewable.io/reviews/gramineproject/graphene/2645#-MiVNTPx4uqyEgwQqJCy:-MjUTzLl7f5i87j0ab6C:b-bo5x1x) ([raw file](https://github.com/gramineproject/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/Makefile#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Because there's nothing magic in installation, it's just recursive copy. In any case this is done after configuration.

The headers may get generated/altered in any of configuring/building/installing step, we can't assume what mbedtls does internally (and this may change between versions).

Please at least add a comment that this is a temporary hack and we are using wrong headers now, but should be gone when mbedtls upstreams the CMAC-enabled-by-default change.
</blockquote></details>

Done, in TODO above.
___
*[Examples/ra-tls-mbedtls/Makefile, line 32 at r15](https://reviewable.io/reviews/gramineproject/graphene/2645#-MizIj0z4CeqtQyiBcxw:-MjUTVdR8Czi1J64bhwS:bjepk8x) ([raw file](https://github.com/gramineproject/graphene/blob/449288aaab7e86ff87f7a6701ae17b6b0d777ede/Examples/ra-tls-mbedtls/Makefile#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, could you add a comment that this mbedTLS download is purely to get the `./mbedtls/include` headers? And that the mbedTLS libraries are taken from the Graphene package.
</blockquote></details>

Sure, why not.
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 7 at r12](https://reviewable.io/reviews/gramineproject/graphene/2645#-MiVNukp1DGnqJKlWyA_:-MjUU66oA5IENl3LK5vf:bu6p2fi) ([raw file](https://github.com/gramineproject/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/server.manifest.template#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The problem is that `GRAPHENE_LIBRARY_PATH` by design assumes 1-1 mapping. In "If someone wants to remap" - how would you do this remapping? You can't assume the contents of `GRAPHENE_LIBRARY_PATH`, and it lists only some host paths. This could be feasible only if `GRAPHENE_LIBRARY_PATH` was just a single path (which I think is what we should do).
</blockquote></details>

I don't think this variable should be generally used, like the `LD_LIBRARY_PATH` should also not be generally used, but there are certain cases that you want it for some reason. So if you write a production manifest, right, you should remap directories, but then you list them manually anyway, right? You won't use this variable.

So I still don't think there's a use case for this variable to be used in remapped directories. We certainly don't have a case for this in CI, and I don't think anyone else would have. Keep in mind that this variable is not needed at all if you use `--prefix=/usr` (like debs).
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 8 at r13](https://reviewable.io/reviews/gramineproject/graphene/2645#-MiuKEHU51db0T2sEW1S:-MjUWQ-B61VaIx_JMMlT:bu6i4lq) ([raw file](https://github.com/gramineproject/graphene/blob/71cd5eeef7b052405cc82dddf3912076a8190ad8/Examples/ra-tls-mbedtls/server.manifest.template#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But you removed `/libs` in `client.manifest.template`, it is inconsistent.
</blockquote></details>

OK, so removed. Thanks, I reacted reflexively.


<!-- Sent from Reviewable.io -->

2021-09-13 16:37 UTC, pwmarcz requested changes
> Reviewed 8 of 8 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2645)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2645#-MhYVu5IDdrhGt9mqTtC:-MjV05VX86q0c1h-ZBv0:bsojuv6) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, resolving. I'm not verifying manually, but this configuration (SGX and debug) is already in Jenkins, so it should get verified when you re-submit to new repo.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2645#-MifymuR9eQqbBVlJECL:-MjUwcSZDjVGllY54l6J:bqrn0d4) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

We can't hardcode GCC in meson, anyone configuring build can select a compiler. We can just skip this file if compiler for C++ is not `g++` (and in CI always use `g++`).
</blockquote></details>

Actually, can we just use GNU syntax here and compile with Clang? Having to use GCC in an otherwise-Clang configuration (such as the one for sanitizers) is worse technical debt than having to use GNU asm syntax.

---
___
*[Documentation/building.rst, line 228 at r16](https://reviewable.io/reviews/gramineproject/graphene/2645#-MjUxrr1A_-c1BU7HYE-:-MjUxrr1A_-c1BU7HYE0:b-in9dpz) ([raw file](https://github.com/gramineproject/graphene/blob/368cc220eefe0d3cb145e2a7ffcd0bdb6db31bd6/Documentation/building.rst#L228)):*
> ```reStructuredText
>   ``$PATH``                   :file:`<prefix>/bin`                               `POSIX.1-2018 8.3`_
>   ``$PYTHONPATH``             :file:`<prefix>/lib/python<version>/site-packages` :manpage:`python3(1)`
>   ``$PKG_CONFIG_PATH``        :file:`<prefix>/<libdir>/pkgconfig`                :manpage:`pkg-config(1)`
> ```

Also `GRAPHENE_LIBRARY_PATH`, right?
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 46 at r12](https://reviewable.io/reviews/gramineproject/graphene/2645#-MiVMmig21KFiRa7n2D5:-MjUyFnD1ebs2tqbZUCf:b-hqwnoo) ([raw file](https://github.com/gramineproject/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/client.manifest.template#L46)):*
>This holds for every single thingy installed outside of /usr, not only built using our buildsystem. So long-term we need something like this for adding multiple directories to libs ad-hoc.

So it's not a temporary hack for CI, but a mechanism we need for the long term? In this case I doubt it should look like this, and I suspect that when we have a "real" use case (i.e. a library that is not actually built and installed by Graphene), we will have to come up with something else.

Either way I'm OK with merging this now, we spent too much time here.
___
*[Pal/src/host/Linux-SGX/tools/common/util.c, line 234 at r16](https://reviewable.io/reviews/gramineproject/graphene/2645#-MjV-3no3cWikjfDhk01:-MjV-3no3cWikjfDhk02:b6gkgr3) ([raw file](https://github.com/gramineproject/graphene/blob/368cc220eefe0d3cb145e2a7ffcd0bdb6db31bd6/Pal/src/host/Linux-SGX/tools/common/util.c#L234)):*
> ```C
> 
> noreturn void abort(void) {
>     _Exit(131);
> ```

Can you use `ENOTRECOVERABLE` instead of 131? I had to look it up.

And out of curiosity, why `_Exit` not `_exit`?


<!-- Sent from Reviewable.io -->

2021-09-14 00:11 UTC, mkow requested changes
> Reviewed 8 of 8 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2645)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2645#-MifymuR9eQqbBVlJECL:-MjW_ugZ2qaTay-TJLQv:bkgr5vc) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Actually, can we just use GNU syntax here and compile with Clang? Having to use GCC in an otherwise-Clang configuration (such as the one for sanitizers) is worse technical debt than having to use GNU asm syntax.
</blockquote></details>

True, let's just give up and just use at&t there. We'll try to make it nicer later.

---
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 46 at r12](https://reviewable.io/reviews/gramineproject/graphene/2645#-MiVMmig21KFiRa7n2D5:-MjWbFDU8XyDXJnOKJJp:bn2x788) ([raw file](https://github.com/gramineproject/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/client.manifest.template#L46)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>This holds for every single thingy installed outside of /usr, not only built using our buildsystem. So long-term we need something like this for adding multiple directories to libs ad-hoc.

So it's not a temporary hack for CI, but a mechanism we need for the long term? In this case I doubt it should look like this, and I suspect that when we have a "real" use case (i.e. a library that is not actually built and installed by Graphene), we will have to come up with something else.

Either way I'm OK with merging this now, we spent too much time here.
</blockquote></details>

@woju: Didn't we talk about this in-person? Why can't you just create a directory with all binaries for in-enclave runtime? It would be just a single path and it would also solve the problem of the current solution, which forbids non-exact mapping from the host (i.e. the current one forces you to use the same paths on the host and inside the enclave).
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 7 at r12](https://reviewable.io/reviews/gramineproject/graphene/2645#-MiVNukp1DGnqJKlWyA_:-MjWbzaoDK2i2lRRALwo:b-fbzepa) ([raw file](https://github.com/gramineproject/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/server.manifest.template#L7)):*
> So if you write a production manifest, right, you should remap directories, but then you list them manually anyway, right? You won't use this variable.

But in such a case you don't want to hardcode the install prefix in the manifest template, or rather, why would we force users to hardcode it?

We wouldn't have this problem if `GRAPHENE_LIBRARY_PATH` was a single path, you could mount all the in-enclave binaries into `/asdf` and hardcode `LD_LIBRARY_PATH` to `/asdf` in the manifest. And then it wouldn't depend on the installation prefix.


<!-- Sent from Reviewable.io -->

2021-09-14 07:53 UTC, dimakuv submitted a review, later dismissed
> Reviewed 8 of 8 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2645)* status: all files reviewed, 7 unresolved discussions (waiting on @boryspoplawski, @pwmarcz, and @woju)



<!-- Sent from Reviewable.io -->

2021-09-15 22:37 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2645)* status: all files reviewed, 7 unresolved discussions (waiting on @boryspoplawski, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2645#-MifymuR9eQqbBVlJECL:-MjfaeWz34xsf-mBgOyY:b-x2lrnm) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

True, let's just give up and just use at&t there. We'll try to make it nicer later.
</blockquote></details>

This was fixed separately in the new repo (https://github.com/gramineproject/gramine/pull/42), resolving from my side.

---


<!-- Sent from Reviewable.io -->

2021-09-16 16:18 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2645)* status: 69 of 83 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[.ci/lib/stage-build-nosgx.jenkinsfile, line 28 at r2](https://reviewable.io/reviews/gramineproject/graphene/2645#-MhYvUP6-tDv5hOUoS1f:-MjjOGecEN_ZlBZ9H9HK:b-a2zgmv) ([raw file](https://github.com/gramineproject/graphene/blob/7c3b3b47c2fd9bbe2151e94e274b6853e840cf1f/.ci/lib/stage-build-nosgx.jenkinsfile#L28)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

For the same reason as in `stage-build-sgx.jenkinsfile`.
</blockquote></details>

Here only PKG_CONFIG_PATH remained.
___
*[Documentation/building.rst, line 228 at r16](https://reviewable.io/reviews/gramineproject/graphene/2645#-MjUxrr1A_-c1BU7HYE-:-MjZLkHv6n4-YoSw_ZDZ:b-l40cav) ([raw file](https://github.com/gramineproject/graphene/blob/368cc220eefe0d3cb145e2a7ffcd0bdb6db31bd6/Documentation/building.rst#L228)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Also `GRAPHENE_LIBRARY_PATH`, right?
</blockquote></details>

Not yet. I don't want to document this until we finish the discussion, how exactly we'd like this to work.
___
*[Examples/ra-tls-mbedtls/client.manifest.template, line 46 at r12](https://reviewable.io/reviews/gramineproject/graphene/2645#-MiVMmig21KFiRa7n2D5:-MjZM5kc0Zp9c3B1-Gdl:b4tymv5) ([raw file](https://github.com/gramineproject/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/client.manifest.template#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@woju: Didn't we talk about this in-person? Why can't you just create a directory with all binaries for in-enclave runtime? It would be just a single path and it would also solve the problem of the current solution, which forbids non-exact mapping from the host (i.e. the current one forces you to use the same paths on the host and inside the enclave).
</blockquote></details>

We can use runtimedir for things installed by us, but I don't want to generally suggest this solution that every external library has to be recompiled with `--libdir=/usr/lib/graphene/runtime`. Ultimately we'll need some mechanism for adding external libraries.

OK, so right now I removed this GRAPHENE_LIBRARY_PATH and installed symlinks, but we'll surely 
___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 7 at r12](https://reviewable.io/reviews/gramineproject/graphene/2645#-MiVNukp1DGnqJKlWyA_:-MjZ7p6TBAFMTAEp0800:bwkriyc) ([raw file](https://github.com/gramineproject/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/server.manifest.template#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> So if you write a production manifest, right, you should remap directories, but then you list them manually anyway, right? You won't use this variable.

But in such a case you don't want to hardcode the install prefix in the manifest template, or rather, why would we force users to hardcode it?

We wouldn't have this problem if `GRAPHENE_LIBRARY_PATH` was a single path, you could mount all the in-enclave binaries into `/asdf` and hardcode `LD_LIBRARY_PATH` to `/asdf` in the manifest. And then it wouldn't depend on the installation prefix.
</blockquote></details>

I don't understand the part about hardcoding. Where we hardcode the prefix? IIUC we don't, we have `{{ graphene.* }}` exactly because we have different paths in CI.

In any case we'll have standard paths (#2316), right? So there's nothing wrong with hardcoding
___
*[Pal/src/host/Linux-SGX/tools/common/util.c, line 234 at r16](https://reviewable.io/reviews/gramineproject/graphene/2645#-MjV-3no3cWikjfDhk01:-MjZ2hQE1onG1ZY3oN9W:b-89zgt7) ([raw file](https://github.com/gramineproject/graphene/blob/368cc220eefe0d3cb145e2a7ffcd0bdb6db31bd6/Pal/src/host/Linux-SGX/tools/common/util.c#L234)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Can you use `ENOTRECOVERABLE` instead of 131? I had to look it up.

And out of curiosity, why `_Exit` not `_exit`?
</blockquote></details>

Done.

No reason at all, I think they're equivalent.


<!-- Sent from Reviewable.io -->

2021-09-16 16:20 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2645)* status: 69 of 83 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[-- commits, line 3 at r17](https://reviewable.io/reviews/gramineproject/graphene/2645#-MjjOzZfCsVvRgyVrSoa):*
This commit is not part of the PR, pushed it on the bottom, because it was needed for the next commit.


<!-- Sent from Reviewable.io -->

2021-09-16 16:49 UTC, mkow requested changes
> Reviewed 14 of 14 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2645)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @pwmarcz, and @woju)

___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 7 at r12](https://reviewable.io/reviews/gramineproject/graphene/2645#-MiVNukp1DGnqJKlWyA_:-MjjRTM19u1SK7HpxFH0:bh0l0xq) ([raw file](https://github.com/gramineproject/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/server.manifest.template#L7)):*
> Where we hardcode the prefix?

there, in your proposed version:

> then you list them manually anyway

this would need to hardcode the host graphene install prefix

> In any case we'll have standard paths (#2316), right? So there's nothing wrong with hardcoding

Don't this always depend on the distro?
___
*[Pal/src/host/Linux-SGX/tools/common/meson.build, line 44 at r17](https://reviewable.io/reviews/gramineproject/graphene/2645#-MjjVTlR3-3uPrblCnvK:-MjjVTlR3-3uPrblCnvL:br5022t) ([raw file](https://github.com/gramineproject/graphene/blob/59b2c8a3f28983ce3595b59a81197e14669f3214/Pal/src/host/Linux-SGX/tools/common/meson.build#L44)):*
> ```Meson
> meson.add_install_script('/bin/sh', '-c',
>     'ln -sf ../../../libsgx_util.so ' +
>     '"$MESON_INSTALL_DESTDIR_PREFIX"/@0@/graphene/runtime/glibc/'.format(
> ```

Shouldn't you quote the whole path, not just `$MESON_INSTALL_DESTDIR_PREFIX`?
ditto for all other such places


<!-- Sent from Reviewable.io -->

2021-09-16 17:05 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2645)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 7 at r12](https://reviewable.io/reviews/gramineproject/graphene/2645#-MiVNukp1DGnqJKlWyA_:-MjjWwrA2ADiirVZic4t:bscbjcq) ([raw file](https://github.com/gramineproject/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/server.manifest.template#L7)):*
> Don't this always depend on the distro?

I think it should not, eventually, hence the official proposal.
___
*[Pal/src/host/Linux-SGX/tools/common/meson.build, line 44 at r17](https://reviewable.io/reviews/gramineproject/graphene/2645#-MjjVTlR3-3uPrblCnvK:-MjjXCf9Ee7v8-kcAiLr:bidx4lm) ([raw file](https://github.com/gramineproject/graphene/blob/59b2c8a3f28983ce3595b59a81197e14669f3214/Pal/src/host/Linux-SGX/tools/common/meson.build#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't you quote the whole path, not just `$MESON_INSTALL_DESTDIR_PREFIX`?
ditto for all other such places
</blockquote></details>

The variable itself, `$MESON_INSTALL_DESTDIR_PREFIX` should be *quoted*, and whatever is substituted in `@0@` should be *escaped*. Just quoting is not sufficient, because you could then have quote inside `@0@`. But I don't have a good primitive for escaping shell characters (the best thing I can think of is `run_program('python', '-c', 'import shutil; shutil.quote()'`), so currently if you pass whitespace or special chars in `--libdir=` option to `meson setup`, then yes, this will break.

I don't want to fix this now, because this is kinda rabbit hole (after shell special characters there are funny unicode things, and after that there are issues with invalid unicode encodings, which are valid paths). And there are already other parts of graphene that would break on funny `--libdir` anyway. There is open issue for this: #1046.


<!-- Sent from Reviewable.io -->

2021-09-16 18:00 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2645)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[Examples/ra-tls-mbedtls/server.manifest.template, line 7 at r12](https://reviewable.io/reviews/gramineproject/graphene/2645#-MiVNukp1DGnqJKlWyA_:-MjjhmtuATqZbefQHoCt:b-jt0456) ([raw file](https://github.com/gramineproject/graphene/blob/b283b85fd1a00481eab8990d31018bbe92556e87/Examples/ra-tls-mbedtls/server.manifest.template#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> Don't this always depend on the distro?

I think it should not, eventually, hence the official proposal.
</blockquote></details>

What about NixOS? ]:->
___
*[Pal/src/host/Linux-SGX/tools/common/meson.build, line 44 at r17](https://reviewable.io/reviews/gramineproject/graphene/2645#-MjjVTlR3-3uPrblCnvK:-MjjiupV44FeF0RJ5Caa:b5xowph) ([raw file](https://github.com/gramineproject/graphene/blob/59b2c8a3f28983ce3595b59a81197e14669f3214/Pal/src/host/Linux-SGX/tools/common/meson.build#L44)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

The variable itself, `$MESON_INSTALL_DESTDIR_PREFIX` should be *quoted*, and whatever is substituted in `@0@` should be *escaped*. Just quoting is not sufficient, because you could then have quote inside `@0@`. But I don't have a good primitive for escaping shell characters (the best thing I can think of is `run_program('python', '-c', 'import shutil; shutil.quote()'`), so currently if you pass whitespace or special chars in `--libdir=` option to `meson setup`, then yes, this will break.

I don't want to fix this now, because this is kinda rabbit hole (after shell special characters there are funny unicode things, and after that there are issues with invalid unicode encodings, which are valid paths). And there are already other parts of graphene that would break on funny `--libdir` anyway. There is open issue for this: #1046.
</blockquote></details>

Ouch, that sucks. But yeah, we can skip this for now if there's no easy way to do this.


<!-- Sent from Reviewable.io -->

2021-09-17 09:32 UTC, dimakuv approved these changes
> Reviewed 12 of 14 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2645)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-09-17 10:36 UTC, pwmarcz reviewed
> Reviewed 3 of 14 files at r17.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2645)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-09-20 14:29 UTC, woju commented
Moved to gramineproject/gramine#64.

2021-09-20 14:29 UTC, closed without merging