[LibOS] Fix data corruption issue in partial network writes
gramineproject/graphene pull request #2679
Opened 2021-09-06 11:08 UTC by jkr0103

Signed-off-by: Jitender Kumar <jitender.kumar@intel.com>

## Description of the changes 

If `DkStreamWrite' invocation inside sendmsg does partial write, the code simply  continues writing from the next buffer (buf[i+1]) which corrupts the data. Changes in this PR will prevent further DkStreamWrite invocations once partial write is detected.

Fixes #2664

## How to test this PR? 
Create a communication channel between client and server and send large size data for example 4194299 bytes multiple times.

2021-09-06 11:22 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2679)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2679#-MiuowmZAmQZ4Mh8q7sp):*
This commit message doesn't describe what the issue was. I suggest to rephrase like this:
```
[LibOS] Return a partial write in `do_sendmsg` if host-level write was partial

Previously, `do_sendmsg` iterated through all iovec buffers supplied by the user,
regardless of whether the host-level write to the socket (via `DkStreamWrite`) was
able to send the whole buffer or only part of the buffer. This could lead to data
corruptions: Graphene would send only some parts of the buffers (i.e., with gaps)
but would report to the user app the total sum of sent bytes (i.e., without gaps).
This commit fixes this by simply bailing out on the first encountered host-level
partial write.
```


<!-- Sent from Reviewable.io -->

2021-09-06 11:22 UTC, dimakuv commented
Jenkins, test this please

2021-09-06 11:34 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2679)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2679#-MiuowmZAmQZ4Mh8q7sp):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This commit message doesn't describe what the issue was. I suggest to rephrase like this:
```
[LibOS] Return a partial write in `do_sendmsg` if host-level write was partial

Previously, `do_sendmsg` iterated through all iovec buffers supplied by the user,
regardless of whether the host-level write to the socket (via `DkStreamWrite`) was
able to send the whole buffer or only part of the buffer. This could lead to data
corruptions: Graphene would send only some parts of the buffers (i.e., with gaps)
but would report to the user app the total sum of sent bytes (i.e., without gaps).
This commit fixes this by simply bailing out on the first encountered host-level
partial write.
```
</blockquote></details>

updated the commit message, PR Title and Description of the Changes.


<!-- Sent from Reviewable.io -->

2021-09-06 11:36 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2679)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2679#-MiuowmZAmQZ4Mh8q7sp):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

updated the commit message, PR Title and Description of the Changes.
</blockquote></details>

OK, awesome!


<!-- Sent from Reviewable.io -->

2021-09-06 11:36 UTC, dimakuv commented
Jenkins, test this please

2021-09-09 23:05 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2679)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2679#-MjBnWuSAH5YNe9_j4XG:-MjBnWuT69Er6dKfkZzi:b1ay2ug) (no related file):*
@jkr0103: Could you migrate this PR to the new repo? We can continue the review there (but the change looks good, so it shouldn't take too much time).

---


<!-- Sent from Reviewable.io -->

2021-09-13 10:44 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2679)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2679#-MjBnWuSAH5YNe9_j4XG:-MjTkKjcDuRoju1IwZA7:b-k1845h) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@jkr0103: Could you migrate this PR to the new repo? We can continue the review there (but the change looks good, so it shouldn't take too much time).
</blockquote></details>

I have migrated the PR to new repo with PR https://github.com/gramineproject/gramine/pull/30

---


<!-- Sent from Reviewable.io -->

2021-09-13 23:20 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2679)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2679#-MjBnWuSAH5YNe9_j4XG:-MjWSW7Y1UggRa18PLin:bfhfk4s) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

I have migrated the PR to new repo with PR https://github.com/gramineproject/gramine/pull/30
</blockquote></details>

Thanks, I'll close this one now.

---


<!-- Sent from Reviewable.io -->

2021-09-13 23:20 UTC, closed without merging